# -*- coding: utf-8 -*-
"""AC-AP-EN — Aeroplan Loyalty > Enrolment and Member Identity (6 processes)."""
from content_lib import P, S

P("AC-AP-EN-01",
  desc="A new Aeroplan member is enrolled and their identity established on SAP Customer Data Cloud, "
       "creating the profile that every subsequent loyalty transaction attaches to.",
  trig="A customer signs up for Aeroplan through a booking flow, the mobile app, a partner channel or the "
       "standalone enrolment page.",
  out="A verified member profile with a unique member number, ready to accrue and redeem points.",
  note="Every downstream loyalty process depends on this identity being correct and unique from the start; "
       "an error here propagates through accrual, redemption and status tracking for the life of the account.",
  phases=["Enrolment capture", "Identity verification", "Profile activation"],
  steps=[
    S("1.1","Capture enrolment details","Aeroplan Member Services Agent","SAP Customer Data Cloud",
      "Customer-entered name, contact and preference data","Captured enrolment record",
      "Enrolment captured in under 2 minutes for 90 percent of digital signups","N","N",
      "Partner-channel enrolment often arrives with less complete data than direct enrolment"),
    S("2.1","Screen for existing member profile","Aeroplan Member Services Agent","SAP Customer Data Cloud",
      "New enrolment details","Match or no-match result",
      "Duplicate screening applied to 100 percent of enrolments","Y","N",
      "Name variation and shared contact details make automated duplicate matching imperfect"),
    S("2.2","Verify identity for account security","Aeroplan Member Services Agent","SAP Customer Data Cloud",
      "Enrolment record","Verified identity",
      "Verification completed before first accrual is posted at 100 percent","N","N",
      "Verification friction that is too heavy discourages completion of enrolment at all"),
    S("3.1","Issue member number and activate profile","Aeroplan Member Services Agent","Aeroplan Platform",
      "Verified identity","Active member profile with member number",
      "Profile activated within 1 hour of verification at 100 percent","N","N",
      "A delay between verification and activation creates a window where accrual cannot be posted"),
  ],
  kpis=["Enrolment captured in under 2 minutes for 90 percent of digital signups",
        "Duplicate screening applied to 100 percent of enrolments",
        "Profile activated within 1 hour of verification at 100 percent",
        "Enrolment abandonment rate below target threshold"],
  risks=["A duplicate profile created undetected, splitting one member's accrual history across two accounts",
         "Verification friction heavy enough to discourage completion of enrolment",
         "A delay between verification and activation creating a window where legitimate accrual cannot post",
         "Partner-channel enrolment data quality being lower than direct-channel enrolment"])

P("AC-AP-EN-02",
  desc="Member consent for marketing communication, data sharing with partners, and profile preferences are "
       "captured and kept current on SAP Customer Data Cloud.",
  trig="A member enrols, updates their preferences, or a consent renewal requirement is triggered by policy "
       "or regulation.",
  out="An accurate, current consent record governing what communications and data sharing the member has "
      "actually agreed to.",
  note="Consent state is a live legal record, not a one-time checkbox; PIPEDA and Quebec Law 25 both expect "
       "it to be current and to actually govern what the airline does with member data.",
  phases=["Consent capture", "Preference management", "Ongoing currency"],
  steps=[
    S("1.1","Capture consent at enrolment","Aeroplan Member Services Agent","SAP Customer Data Cloud",
      "Member enrolment interaction","Recorded consent by category",
      "Consent captured for 100 percent of new enrolments","N","N",
      "Consent categories are granular and easy to under-specify at speed during enrolment"),
    S("2.1","Allow member self-service preference update","Aeroplan Member Services Agent","Air Canada Mobile App",
      "Member preference change request","Updated consent record",
      "Updates take effect within 24 hours of the member's change at 100 percent","N","N",
      "A preference update in one channel does not always propagate to every downstream system on the same timeline"),
    S("2.2","Screen partner data-sharing consent before transfer","Aeroplan Member Services Agent","SAP Customer Data Cloud",
      "Partner data request and member consent state","Permitted or blocked data transfer",
      "Zero data transfers made without the required consent in place","Y","Y",
      "A consent state that is not correctly current can either wrongly block or wrongly permit a transfer"),
    S("3.1","Refresh consent on a periodic or triggered basis","Aeroplan Member Services Agent","SAP Customer Data Cloud",
      "Consent expiry or policy change trigger","Refreshed consent record",
      "Refresh completed before the compliance deadline at 100 percent","N","N",
      "A missed refresh silently reverts the member to a more restrictive default that can suppress legitimate service"),
  ],
  kpis=["Consent captured for 100 percent of new enrolments",
        "Zero data transfers made without the required consent in place",
        "Refresh completed before the compliance deadline at 100 percent",
        "Preference updates taking effect within 24 hours across all systems"],
  risks=["A consent state that does not accurately reflect the member's actual choice",
         "A missed refresh silently reverting the member to a more restrictive default",
         "A preference update in one channel not propagating to every downstream system in time",
         "An incorrect consent state either wrongly blocking service or wrongly permitting a partner data transfer"])

P("AC-AP-EN-03",
  desc="A member's profile, built from bookings, contact updates and channel interactions across mobile, "
       "web and partner touchpoints, is consolidated into a single coherent record.",
  trig="A member interacts through a new channel, or the recurring profile consolidation cycle runs.",
  out="A consolidated member profile reflecting the most current and complete information across all "
      "channels.",
  note="A member who books through the contact centre, updates their address in the app, and interacts with "
      "a partner is, from the system's perspective, generating three separate data points that have to be "
      "reconciled into one profile.",
  phases=["Cross-channel data collection", "Consolidation", "Profile currency validation"],
  steps=[
    S("1.1","Collect profile-relevant data across channels","Aeroplan Member Services Agent","SAP Customer Data Cloud",
      "Interaction data from web, app, contact centre and partners","Collected multi-channel data points",
      "Collected within 24 hours of the interaction at 100 percent","N","N",
      "Channels capture different subsets of profile data with inconsistent field structures"),
    S("2.1","Resolve conflicting data points","Aeroplan Member Services Agent","SAP Customer Data Cloud",
      "Multiple data points for the same field","Resolved single value with a source of truth",
      "Conflicts resolved automatically for 90 percent of cases","Y","N",
      "Automated resolution rules can pick a stale value over a more recent but less-trusted channel"),
    S("3.1","Validate consolidated profile currency","Aeroplan Member Services Agent","Aeroplan Platform",
      "Consolidated profile","Validated current profile",
      "Validated on a recurring cycle for 100 percent of active members","N","N",
      "A profile that is technically consolidated can still be stale if the member has simply stopped updating it"),
    S("3.2","Prompt member self-verification where data is stale","Aeroplan Member Services Agent","Air Canada Mobile App",
      "Stale profile flag","Member-confirmed or updated profile",
      "Prompt issued to 100 percent of members with a profile older than the staleness threshold","N","N",
      "Members have little incentive to respond to a profile currency prompt outside a transaction"),
  ],
  kpis=["Collected within 24 hours of the interaction at 100 percent",
        "Conflicts resolved automatically for 90 percent of cases",
        "Validated on a recurring cycle for 100 percent of active members",
        "Member-reported profile inaccuracy rate below target"],
  risks=["Automated conflict resolution rules picking a stale value over a more recent but less-trusted channel",
         "Channels capturing inconsistent subsets of profile data that never fully reconcile",
         "A profile that is technically consolidated but stale because the member has stopped interacting",
         "Partner channel data arriving in a structure that does not map cleanly to the core profile schema"])

P("AC-AP-EN-04",
  desc="Duplicate member accounts, arising from re-enrolment, name variation or channel-specific sign-up, "
       "are detected and merged into a single account preserving the complete accrual and status history.",
  trig="The recurring duplicate detection cycle runs, or a member reports having more than one account.",
  out="A single merged account with complete, correctly combined accrual history, status and consent state.",
  note="A merge is functionally irreversible in practice, so the accuracy of what gets combined and what "
      "gets discarded matters more here than almost anywhere else in the loyalty platform.",
  phases=["Duplicate detection", "Merge validation", "Account consolidation"],
  steps=[
    S("1.1","Screen for duplicate accounts","Aeroplan Member Services Agent","SAP Customer Data Cloud",
      "Member identity data across the base","Flagged potential duplicate pairs",
      "Screened on a recurring cycle for 100 percent of the active base","N","N",
      "Automated matching on name and contact detail produces both false positives and false negatives"),
    S("2.1","Validate the duplicate finding with the member","Aeroplan Member Services Agent","Salesforce Service Cloud",
      "Flagged duplicate pair","Member-confirmed duplicate or dismissed flag",
      "Validation completed within 10 business days of flagging at 90 percent","Y","N",
      "Confirming with the member can take multiple contact attempts before resolution"),
    S("2.2","Determine surviving account and merge order","Aeroplan Member Services Agent","Aeroplan Platform",
      "Confirmed duplicate accounts","Determined surviving account with merge plan",
      "Merge order determined to preserve the higher-value account at 100 percent","N","N",
      "Choosing the wrong surviving account can lose a higher Altitude tier or a larger points balance"),
    S("3.1","Execute the account merge","Aeroplan Member Services Agent","Aeroplan Platform",
      "Merge plan","Merged account with combined history",
      "Merge executed within 5 business days of confirmation at 100 percent","N","N",
      "A merge error is effectively irreversible once points ledgers have been combined"),
  ],
  kpis=["Screened on a recurring cycle for 100 percent of the active base",
        "Merge order determined to preserve the higher-value account at 100 percent",
        "Merge executed within 5 business days of confirmation at 100 percent",
        "Post-merge accrual and status accuracy at 100 percent"],
  risks=["Choosing the wrong surviving account and losing a higher Altitude tier or a larger points balance",
         "A merge error being effectively irreversible once points ledgers have already been combined",
         "Automated matching producing false positives that merge two genuinely distinct members",
         "Confirming a duplicate with the member taking multiple contact attempts, delaying resolution"])

P("AC-AP-EN-05",
  desc="A member who has lost access to their account, through a forgotten password, compromised email or "
       "device change, is authenticated and restored to access their profile.",
  trig="A member submits an account recovery request through self-service or the contact centre.",
  out="Restored account access for the verified member, with security preserved against unauthorised "
      "recovery attempts.",
  note="Account recovery sits at a genuine tension point: too strict and locked-out members cannot regain "
       "access to their own points, too loose and it becomes the easiest path for account takeover fraud.",
  phases=["Recovery request intake", "Identity re-verification", "Access restoration"],
  steps=[
    S("1.1","Receive account recovery request","Aeroplan Member Services Agent","SAP Customer Data Cloud",
      "Member recovery request","Registered recovery case",
      "Requests registered within 1 business day at 100 percent","N","N",
      "Requests arrive through self-service and contact centre with different initial verification depth"),
    S("2.1","Re-verify member identity","Aeroplan Member Services Agent","SAP Customer Data Cloud",
      "Recovery request and member identity documents","Verified identity or failed verification",
      "Identity re-verified before access is restored at 100 percent","Y","N",
      "Verification depth for a self-service reset is inherently lighter than for a contact centre case"),
    S("2.2","Screen for account takeover fraud indicators","Aeroplan Member Services Agent","CyberArk",
      "Recovery request pattern","Fraud risk assessment",
      "Screened for 100 percent of contact centre recovery cases","N","Y",
      "Fraud indicators are probabilistic and can both miss genuine attacks and flag legitimate members"),
    S("3.1","Restore account access","Aeroplan Member Services Agent","SAP Customer Data Cloud",
      "Verified and screened request","Restored account access",
      "Access restored within 24 hours of verification at 95 percent","N","N",
      "Restoring access before fraud screening completes creates a window of exposure"),
  ],
  kpis=["Identity re-verified before access is restored at 100 percent",
        "Access restored within 24 hours of verification at 95 percent",
        "Screened for 100 percent of contact centre recovery cases",
        "Confirmed account takeover incidents below target threshold"],
  risks=["Verification loose enough to become the easiest path for account takeover fraud",
         "Verification strict enough to lock out a legitimate member from their own points balance",
         "Restoring access before fraud screening completes, creating a window of exposure",
         "Self-service and contact centre recovery paths carrying inconsistent verification depth"])

P("AC-AP-EN-06",
  desc="A member's request to access, correct or delete their personal data under PIPEDA or Quebec Law 25 "
       "is processed within the regulated response timeframe.",
  trig="A member submits a data access, correction or deletion request through any channel.",
  out="The member's request fulfilled within the regulated timeframe, with a documented audit trail of the "
      "action taken.",
  note="This is a hard regulatory deadline, not a service level target: Law 25 in particular imposes "
      "specific timeframes and documentation obligations that do not flex for operational convenience.",
  phases=["Request intake and identity verification", "Data action", "Response and documentation"],
  steps=[
    S("1.1","Receive and log the privacy request","Privacy Request Coordinator","SAP Customer Data Cloud",
      "Member submitted request","Logged request with regulatory deadline",
      "Requests logged within 2 business days of receipt at 100 percent","N","N",
      "Requests can arrive through channels not designed for privacy request intake, such as a general complaint form"),
    S("1.2","Verify requester identity","Privacy Request Coordinator","SAP Customer Data Cloud",
      "Logged request","Verified requester identity",
      "Identity verified before any data action at 100 percent","Y","N",
      "Verification has to be robust enough to prevent someone else accessing or deleting a member's data"),
    S("2.1","Locate all personal data across systems","Privacy Request Coordinator","Databricks Lakehouse",
      "Verified request scope","Located data across all relevant systems",
      "Data location completed within the regulatory response window at 100 percent","N","N",
      "Member data is distributed across loyalty, booking, contact centre and partner systems with no single index"),
    S("2.2","Execute the requested action","Privacy Request Coordinator","SAP Customer Data Cloud",
      "Located data and requested action","Data accessed, corrected or deleted as requested",
      "Action executed within the regulatory deadline at 100 percent","N","N",
      "Deletion has to be reconciled against legitimate retention obligations, such as unresolved financial records"),
    S("3.1","Document and respond to the member","Privacy Request Coordinator","SAP Customer Data Cloud",
      "Completed action","Documented response to the member",
      "Response issued within the regulatory deadline at 100 percent","N","N",
      "A missed regulatory deadline is a compliance failure independent of whether the underlying action was completed"),
  ],
  kpis=["Identity verified before any data action at 100 percent",
        "Data location completed within the regulatory response window at 100 percent",
        "Action executed within the regulatory deadline at 100 percent",
        "Response issued within the regulatory deadline at 100 percent"],
  risks=["Member personal data being distributed across systems with no single index to locate it completely",
         "A missed regulatory deadline constituting a compliance failure regardless of the underlying action",
         "Deletion conflicting with a legitimate retention obligation such as an unresolved financial record",
         "Insufficiently robust verification allowing someone other than the member to action the request"])
