# -*- coding: utf-8 -*-
"""AC-AP-RE — Aeroplan Loyalty > Redemption (6 processes)."""
from content_lib import P, S

P("AC-AP-RE-01",
  desc="A member books a flight award using Aeroplan points, drawing on dynamic award availability and "
       "pricing calculated against Amadeus Altea Inventory.",
  trig="A member searches and selects a flight award redemption through a self-service or contact centre "
       "channel.",
  out="A confirmed flight award booking with points deducted from the member's ledger.",
  note="Award pricing is dynamic, so the points cost a member sees can move between search and booking if "
       "demand or inventory shifts, which is one of the most common sources of redemption complaint.",
  phases=["Award search and pricing", "Booking confirmation", "Ledger settlement"],
  steps=[
    S("1.1","Search award availability","Aeroplan Member Services Agent","Aeroplan Platform",
      "Member search criteria","Available award options with points pricing",
      "Search results returned within 3 seconds at 95 percent","N","N",
      "Award availability changes in real time and a result can be stale by the time the member selects it"),
    S("2.1","Confirm points price at booking","Aeroplan Member Services Agent","Amadeus Altea Inventory",
      "Selected award option","Confirmed current points price",
      "Price re-confirmed at the point of booking for 100 percent of redemptions","Y","N",
      "A price change between search and booking is the leading cause of redemption complaints"),
    S("2.2","Verify sufficient points balance","Aeroplan Member Services Agent","Aeroplan Platform",
      "Member points balance and confirmed price","Verified sufficient balance or insufficient-balance flag",
      "Balance verified before booking confirmation at 100 percent","N","N",
      "A points-plus-cash option has to be offered correctly when the balance is insufficient"),
    S("3.1","Issue the award booking","Aeroplan Member Services Agent","Amadeus Altea Reservations",
      "Verified balance and confirmed price","Issued award ticket",
      "Booking issued within 5 minutes of confirmation at 100 percent","N","N",
      "Award ticket issuance failures leave points deducted without a valid booking if not handled atomically"),
    S("3.2","Deduct points and settle the ledger","Aeroplan Member Services Agent","Aeroplan Platform",
      "Issued booking","Points deducted from member ledger",
      "Ledger settled within the same transaction as booking issuance at 100 percent","N","N",
      "A settlement failure after ticket issuance can leave the member's ledger and booking out of sync"),
  ],
  kpis=["Price re-confirmed at the point of booking for 100 percent of redemptions",
        "Booking issued within 5 minutes of confirmation at 100 percent",
        "Ledger settled within the same transaction as booking issuance at 100 percent",
        "Redemption booking complaint rate below target threshold"],
  risks=["A points price changing between search and booking, the leading cause of redemption complaints",
         "A ticket issuance failure leaving points deducted without a corresponding valid booking",
         "A settlement failure leaving the member's ledger and booking record out of sync",
         "Stale award availability shown in search results by the time the member attempts to book"])

P("AC-AP-RE-02",
  desc="A member redeems points for an award on a Star Alliance partner carrier, requiring availability and "
       "pricing coordination across two airlines' systems.",
  trig="A member searches for and selects a partner award redemption.",
  out="A confirmed partner award booking with points deducted and the booking correctly reflected in both "
      "carriers' systems.",
  note="Partner award redemption depends on real-time availability data from a system Air Canada does not "
      "control, which makes it structurally less reliable than a mainline redemption.",
  phases=["Partner availability search", "Cross-carrier booking", "Confirmation and settlement"],
  steps=[
    S("1.1","Search partner award availability","Aeroplan Member Services Agent","Star Alliance Interline",
      "Member search criteria","Partner award availability with points pricing",
      "Partner search results returned within 8 seconds at 90 percent","N","N",
      "Partner availability data freshness depends on the partner's own system, outside Air Canada's control"),
    S("2.1","Confirm partner availability at time of booking","Aeroplan Member Services Agent","Star Alliance Interline",
      "Selected partner award","Re-confirmed partner availability",
      "Re-confirmed for 100 percent of partner redemptions before booking","Y","N",
      "A partner seat shown as available can be sold by the partner before Air Canada's booking completes"),
    S("2.2","Issue the booking across both carrier systems","Aeroplan Member Services Agent","Amadeus Altea Reservations",
      "Confirmed availability","Booking issued in both systems",
      "Both systems reflect the booking within 15 minutes at 95 percent","N","N",
      "A booking that succeeds in one carrier's system and fails in the other requires manual reconciliation"),
    S("3.1","Deduct points and settle interline accounting","Aeroplan Member Services Agent","Aeroplan Platform",
      "Confirmed cross-carrier booking","Deducted points and interline settlement record",
      "Settled within the same transaction as booking issuance at 100 percent","N","N",
      "Interline settlement between the carriers happens on a separate cycle from the member-facing points deduction"),
  ],
  kpis=["Re-confirmed for 100 percent of partner redemptions before booking",
        "Both systems reflecting the booking within 15 minutes at 95 percent",
        "Settled within the same transaction as booking issuance at 100 percent",
        "Partner redemption failure rate below target threshold"],
  risks=["A partner seat sold by the partner carrier before Air Canada's booking transaction completes",
         "A booking succeeding in one carrier's system and failing in the other, requiring manual reconciliation",
         "Partner availability data freshness being entirely outside Air Canada's own control",
         "Interline settlement running on a cycle separate from the member-facing points deduction"])

P("AC-AP-RE-03",
  desc="Members redeem points combined with cash payment for a booking, using the points-plus-cash option "
       "when a full-points redemption is not desired or the balance is insufficient.",
  trig="A member selects the points-plus-cash option during redemption booking.",
  out="A confirmed booking with a correctly calculated split between points deducted and cash charged.",
  note="The points-to-cash conversion ratio and the split calculation are a recurring source of member "
      "confusion, since the value proposition is harder to evaluate at a glance than a simple cash fare.",
  phases=["Split calculation", "Payment processing", "Confirmation"],
  steps=[
    S("1.1","Calculate the points and cash split","Aeroplan Member Services Agent","Aeroplan Platform",
      "Member-selected points-plus-cash ratio","Calculated split by points and cash amount",
      "Split calculated correctly for 100 percent of point-plus-cash bookings","N","N",
      "The conversion ratio can be genuinely difficult for a member to evaluate against a cash fare"),
    S("2.1","Process cash payment component","Aeroplan Member Services Agent","Amazon Connect",
      "Calculated cash amount","Processed cash payment",
      "Cash payment processed securely at 100 percent","N","N",
      "Payment processing failure part-way through a split transaction requires careful rollback handling"),
    S("2.2","Deduct points component from the ledger","Aeroplan Member Services Agent","Aeroplan Platform",
      "Calculated points amount","Deducted points from member ledger",
      "Points deducted within the same transaction as cash processing at 100 percent","N","N",
      "A failure between the two payment legs can leave a booking half-paid"),
    S("3.1","Confirm and issue the booking","Aeroplan Member Services Agent","Amadeus Altea Reservations",
      "Completed split payment","Issued booking confirmation",
      "Booking issued within 5 minutes of payment completion at 100 percent","N","N",
      "Confirmation has to clearly itemise both payment components for the member's record"),
  ],
  kpis=["Split calculated correctly for 100 percent of points-plus-cash bookings",
        "Points deducted within the same transaction as cash processing at 100 percent",
        "Booking issued within 5 minutes of payment completion at 100 percent",
        "Points-plus-cash payment failure rate below target threshold"],
  risks=["A failure between the points and cash payment legs leaving a booking only partially paid",
         "A conversion ratio that is genuinely difficult for a member to evaluate against a cash fare",
         "Payment processing failure part-way through requiring careful transactional rollback",
         "Confirmation that does not clearly itemise both payment components, confusing the member's record"])

P("AC-AP-RE-04",
  desc="A member redeems points to clear an upgrade to a higher cabin on an eligible booking, subject to "
       "fare class eligibility and upgrade inventory clearance rules.",
  trig="A member requests an eUpgrade against an eligible existing booking.",
  out="A confirmed cabin upgrade with points deducted, or a documented reason the upgrade could not clear.",
  note="eUpgrade clearance depends on premium cabin inventory that is also being actively managed by revenue "
       "management for paid upgrades, so the two processes compete for the same seats.",
  phases=["Eligibility check", "Clearance request", "Confirmation"],
  steps=[
    S("1.1","Verify booking eligibility for eUpgrade","Aeroplan Member Services Agent","Aeroplan Platform",
      "Existing booking and fare class","Eligibility confirmation or ineligible flag",
      "Eligibility verified within seconds of the request at 100 percent","N","N",
      "Fare class eligibility rules are not always intuitive to the member requesting the upgrade"),
    S("2.1","Submit clearance request against upgrade inventory","Aeroplan Member Services Agent","Amadeus Altea Inventory",
      "Eligible booking","Clearance request submitted",
      "Requests submitted immediately upon eligible request at 100 percent","N","N",
      "eUpgrade requests compete with revenue management's own paid upgrade clearance for the same seats"),
    S("2.2","Process waitlist for unavailable clearance","Aeroplan Member Services Agent","Aeroplan Platform",
      "Unavailable clearance at time of request","Waitlisted request with priority order",
      "Waitlist priority applied correctly by Altitude tier at 100 percent","Y","N",
      "Waitlist priority logic across tiers can be difficult for a member to understand when they see a competitor cleared first"),
    S("3.1","Confirm cleared upgrade and deduct points","Aeroplan Member Services Agent","Aeroplan Platform",
      "Cleared upgrade","Confirmed upgrade with points deducted",
      "Points deducted only upon confirmed clearance at 100 percent","N","N",
      "Deducting points before clearance is confirmed risks a member losing points for an upgrade that never clears"),
  ],
  kpis=["Eligibility verified within seconds of the request at 100 percent",
        "Waitlist priority applied correctly by Altitude tier at 100 percent",
        "Points deducted only upon confirmed clearance at 100 percent",
        "eUpgrade clearance rate meeting target for Super Elite and top-tier members"],
  risks=["eUpgrade and paid upgrade clearance competing for the same premium cabin inventory with no shared arbitration",
         "Points deducted before clearance is confirmed, risking loss for an upgrade that never clears",
         "Waitlist priority logic being difficult for a member to understand when a lower-tier member appears to clear first",
         "Fare class eligibility rules not being intuitive to the member making the request"])

P("AC-AP-RE-05",
  desc="A member requests a reversal of a points redemption, whether for a cancelled award booking or a "
       "redemption made in error, restoring points to the member's ledger.",
  trig="A member requests to cancel or reverse a completed redemption.",
  out="A correctly reversed redemption with points restored to the member's ledger and any associated "
      "booking cancelled.",
  note="A reversal has to unwind two systems together, the booking and the points ledger, and a partial "
      "reversal that only completes one side leaves the member either shortchanged or with an unintended "
      "double benefit.",
  phases=["Reversal request validation", "Booking cancellation", "Points restoration"],
  steps=[
    S("1.1","Validate reversal eligibility","Aeroplan Member Services Agent","Aeroplan Platform",
      "Reversal request and original redemption terms","Eligibility determination",
      "Eligibility determined within 1 business day of request at 100 percent","Y","N",
      "Reversal eligibility rules vary by fare rule and time since booking, and are easy to misapply"),
    S("2.1","Cancel the underlying booking","Aeroplan Member Services Agent","Amadeus Altea Reservations",
      "Eligible reversal request","Cancelled booking",
      "Cancellation processed within 1 business day of eligibility confirmation at 100 percent","N","N",
      "A booking already partially used, such as one segment flown, complicates a clean cancellation"),
    S("2.2","Calculate any applicable reversal fee","Aeroplan Member Services Agent","Aeroplan Platform",
      "Cancellation and fare rule terms","Calculated reversal fee",
      "Fee calculated correctly against the applicable fare rule at 100 percent","N","N",
      "Fee calculation depends on correctly reading a fare rule not originally designed with reversal in mind"),
    S("3.1","Restore points to the member ledger","Aeroplan Member Services Agent","Aeroplan Platform",
      "Cancelled booking and calculated fee","Points restored net of any fee",
      "Points restored within 5 business days of cancellation at 100 percent","N","N",
      "A restoration that does not match the original deduction exactly creates a ledger discrepancy"),
  ],
  kpis=["Eligibility determined within 1 business day of request at 100 percent",
        "Points restored within 5 business days of cancellation at 100 percent",
        "Fee calculated correctly against the applicable fare rule at 100 percent",
        "Reversal-related member complaint rate below target threshold"],
  risks=["A partial reversal completing on the booking side but not the points side, or the reverse",
         "A ledger discrepancy where the restored amount does not exactly match the original deduction",
         "Fee calculation misapplying a fare rule not originally designed with reversal in mind",
         "A booking with one segment already flown complicating what a clean cancellation actually means"])

P("AC-AP-RE-06",
  desc="Points breakage, the value of points issued but never redeemed, is estimated and applied to the "
       "financial valuation of the points liability, distinct from the operational redemption process itself.",
  trig="The recurring financial close cycle requires an updated breakage estimate for the points liability.",
  out="A statistically supported breakage rate applied to the points liability, reviewed for continued "
      "validity against actual member behaviour.",
  note="Breakage assumptions sit at the intersection of loyalty operations and finance, and getting them "
      "wrong in either direction misstates a liability that is material enough to matter on the balance "
      "sheet, as flagged in AC-FN-RA processes.",
  phases=["Behaviour analysis", "Breakage rate estimation", "Application and review"],
  steps=[
    S("1.1","Analyse historical redemption behaviour","Loyalty Finance Analyst","Aeroplan Platform",
      "Multi-year points issuance and redemption history","Redemption behaviour analysis",
      "Analysis refreshed each financial close cycle at 100 percent","N","N",
      "Redemption behaviour is shifting as the loyalty programme and member base both continue to evolve"),
    S("2.1","Estimate the breakage rate","Loyalty Finance Analyst","SAP Analytics Cloud",
      "Redemption behaviour analysis","Estimated breakage rate",
      "Estimate produced with documented statistical method each cycle","N","N",
      "A breakage estimate is inherently a forward-looking assumption about behaviour that has not yet occurred"),
    S("2.2","Validate estimate against actuarial review","Loyalty Finance Analyst","SAP S/4HANA",
      "Estimated rate","Actuarially reviewed and approved rate",
      "Reviewed and approved before application to the liability at 100 percent","Y","N",
      "Actuarial review timelines do not always align neatly with the financial close calendar"),
    S("3.1","Apply the rate to the points liability","Loyalty Finance Analyst","SAP S/4HANA",
      "Approved breakage rate","Updated points liability valuation",
      "Applied within the financial close timetable at 100 percent","N","N",
      "An applied rate that later proves wrong requires a retrospective liability adjustment"),
  ],
  kpis=["Analysis refreshed each financial close cycle at 100 percent",
        "Reviewed and approved before application to the liability at 100 percent",
        "Applied within the financial close timetable at 100 percent",
        "Breakage estimate variance against subsequent actual behaviour within target tolerance"],
  risks=["A breakage estimate that misstates a points liability material enough to matter on the balance sheet",
         "Redemption behaviour shifting as the programme and member base evolve, ageing the estimate quickly",
         "Actuarial review timelines not aligning with the financial close calendar",
         "A rate later proving wrong and requiring a retrospective liability adjustment"])
