# -*- coding: utf-8 -*-
"""AC-CX-CC — Contact Centre (6) and AC-CX-SS — Special Services and Accessibility (6)."""
from content_lib import P, S

# ── CC: Contact Centre ──────────────────────────────────────────────────────
P("AC-CX-CC-01",
  desc="An inbound customer service call is handled from IVR routing through resolution, on Amazon Connect "
       "with Salesforce Service Cloud Voice carrying the case record.",
  trig="A customer calls the Air Canada contact centre for booking, servicing or general enquiry support.",
  out="A resolved or appropriately escalated customer interaction, logged as a case with full context "
      "available for any follow-up.",
  note="Air Canada's contact centre handles a very high monthly IVR call volume, and the interaction record "
      "created here is what a later APPR determination or complaint investigation depends on being complete.",
  phases=["Call routing", "Servicing", "Case documentation"],
  steps=[
    S("1.1","Route call through IVR","Contact Centre Agent","Amazon Connect",
      "Inbound call and customer input","Routed call to the appropriate queue",
      "Correctly routed on first pass at 90 percent","N","N",
      "IVR menu depth that is too deep frustrates customers before they ever reach an agent"),
    S("1.2","Authenticate customer identity","Contact Centre Agent","Salesforce Service Cloud",
      "Booking reference or member number","Authenticated customer context",
      "Authenticated within 30 seconds of connection at 95 percent","N","N",
      "Authentication has to balance security against not making a distressed customer repeat information"),
    S("2.1","Retrieve booking and loyalty context","Contact Centre Agent","Amadeus Altea Customer Management",
      "Authenticated identity","Retrieved booking and member context",
      "Context retrieved within 15 seconds at 95 percent","N","N",
      "Context spans several systems and does not always assemble into one agent-facing view"),
    S("2.2","Resolve the customer's request","Contact Centre Agent","Salesforce Service Cloud",
      "Retrieved context and customer request","Resolved request or identified escalation need",
      "First contact resolution above target for 75 percent of calls","N","N",
      "Complex multi-system requests, such as an Express-operator itinerary change, exceed a single agent's system access"),
    S("3.1","Document the case record","Contact Centre Agent","Salesforce Service Cloud",
      "Resolved or escalated interaction","Complete case record",
      "Documented within 2 minutes of call end at 90 percent","N","N",
      "Documentation completeness under call-volume pressure is the first thing to suffer"),
  ],
  kpis=["Correctly routed on first pass at 90 percent",
        "First contact resolution above target for 75 percent of calls",
        "Documented within 2 minutes of call end at 90 percent",
        "Average handle time within target while maintaining resolution quality"],
  risks=["Case documentation quality degrading under call-volume pressure, weakening later APPR evidence",
         "A multi-system request such as an Express-operator change exceeding a single agent's access",
         "An IVR menu too deep for the situation, frustrating the customer before reaching an agent",
         "Context assembled from several systems failing to present as one coherent agent view"])

P("AC-CX-CC-02",
  desc="IVR self-service containment is optimised so routine requests, such as flight status or simple "
       "rebooking, are resolved without requiring a live agent.",
  trig="A customer call enters the IVR and matches a self-service-eligible intent.",
  out="The customer's request resolved through self-service, or correctly escalated to a live agent when "
      "self-service cannot complete the request.",
  note="Containment rate is under constant upward pressure as call volume grows, but a self-service path "
      "that fails silently, rather than escalating cleanly, produces a worse customer experience than never "
      "offering the option at all.",
  phases=["Intent detection", "Self-service execution", "Escalation fallback"],
  steps=[
    S("1.1","Detect customer intent","Contact Centre Agent","Nuance IVR",
      "Customer speech or keypad input","Detected intent classification",
      "Intent correctly classified at 88 percent","N","N",
      "Speech recognition accuracy degrades with background noise and accented speech"),
    S("2.1","Execute self-service transaction","Contact Centre Agent","Amadeus Altea Customer Management",
      "Classified intent","Completed self-service transaction or failure",
      "Successfully completed for 80 percent of eligible intents","N","N",
      "A self-service transaction that partially completes and then fails is harder to recover from than one that never starts"),
    S("2.2","Confirm completion with the customer","Contact Centre Agent","Nuance IVR",
      "Completed transaction","Confirmed customer acknowledgement",
      "Confirmation delivered clearly for 100 percent of completed transactions","N","N",
      "A transaction that completes silently leaves the customer uncertain whether it actually worked"),
    S("3.1","Escalate to a live agent on failure","Contact Centre Agent","Amazon Connect",
      "Failed or ineligible self-service attempt","Escalated call with context preserved",
      "Escalation preserves full context for 100 percent of escalated calls","Y","N",
      "Context loss at escalation forces the customer to repeat information already given to the IVR"),
  ],
  kpis=["Intent correctly classified at 88 percent",
        "Successfully completed for 80 percent of eligible intents",
        "Escalation preserves full context for 100 percent of escalated calls",
        "Overall self-service containment rate meeting target"],
  risks=["A self-service transaction that partially completes and then fails, harder to recover than a clean failure",
         "Speech recognition accuracy degrading with background noise or accented speech",
         "Context loss at escalation forcing the customer to repeat information already provided",
         "A transaction that completes silently, leaving the customer uncertain whether it worked"])

P("AC-CX-CC-03",
  desc="Conversations with the Air Canada virtual assistant are handled and escalated to a human agent when "
       "the assistant's confidence or authority is insufficient to resolve the request safely.",
  trig="A customer initiates a chat conversation with the virtual assistant through the website or app.",
  out="A resolved conversation within the assistant's governed scope, or a clean escalation to a human agent "
      "with context preserved.",
  note="Every response the assistant gives is subject to the human-in-loop governance established in "
      "AC-IT-AI-03, following the Moffatt ruling. The escalation threshold here is a compliance control, not "
      "just a service design choice.",
  phases=["Conversation handling", "Confidence and scope assessment", "Escalation or resolution"],
  steps=[
    S("1.1","Process customer message","Contact Centre Agent","Air Canada Virtual Assistant",
      "Customer message","Interpreted intent and context",
      "Intent interpreted within 2 seconds at 90 percent","N","N",
      "Ambiguous customer phrasing produces a lower-confidence interpretation more often than clear requests"),
    S("1.2","Ground response against approved policy sources","Contact Centre Agent","Air Canada Virtual Assistant",
      "Interpreted intent","Response grounded in allow-listed sources",
      "100 percent of responses grounded within the approved source set","Y","N",
      "A response drawing on unapproved or outdated content risks repeating the Moffatt failure mode"),
    S("2.1","Assess response confidence against escalation threshold","Contact Centre Agent","Air Canada Virtual Assistant",
      "Grounded response","Confidence score against threshold",
      "Below-threshold responses escalated at 100 percent","Y","N",
      "A threshold set too low still lets an uncertain answer reach the customer"),
    S("3.1","Escalate to a live agent when required","Contact Centre Agent","Salesforce Service Cloud",
      "Below-threshold or out-of-scope request","Escalated conversation with full context",
      "Context preserved for 100 percent of escalations at handoff","N","N",
      "A conversation history that does not transfer cleanly forces the customer to restart with a human agent"),
  ],
  kpis=["100 percent of responses grounded within the approved source set",
        "Below-threshold responses escalated at 100 percent",
        "Context preserved for 100 percent of escalations at handoff",
        "Zero confirmed cases of the assistant stating an incorrect policy position"],
  risks=["A response drawing on unapproved or outdated content, repeating the Moffatt failure mode",
         "An escalation threshold set too low, letting an uncertain answer reach the customer directly",
         "Conversation history not transferring cleanly at escalation, forcing the customer to restart",
         "Ambiguous customer phrasing producing lower-confidence interpretations more often than clear requests"])

P("AC-CX-CC-04",
  desc="Contact centre agents are supported with grounded knowledge suggestions drawn from policy sources "
       "during a live interaction, drafting responses the agent reviews and approves before sending.",
  trig="An agent is handling a customer interaction requiring policy-specific information.",
  out="An agent-approved response grounded in current policy, delivered faster than manual policy lookup "
      "would allow.",
  note="Agent-assist is deliberately designed with the agent, not the tool, as the decision-maker, which "
      "keeps the same human-in-loop principle established for the virtual assistant applied to the agent "
      "desktop.",
  phases=["Suggestion generation", "Agent review", "Response delivery"],
  steps=[
    S("1.1","Detect the policy question in the live interaction","Contact Centre Agent","Salesforce Service Cloud",
      "Live customer interaction","Detected policy question requiring grounded support",
      "Detected within the live interaction for 85 percent of eligible questions","N","N",
      "Detection accuracy depends on interaction content that is not always structured or explicit"),
    S("2.1","Generate grounded response suggestion","Contact Centre Agent","Air Canada Virtual Assistant",
      "Detected question","Draft suggested response with source citation",
      "Suggestion generated within 3 seconds at 90 percent","N","N",
      "A suggestion without a visible source citation is harder for the agent to trust and verify quickly"),
    S("2.2","Agent reviews and edits the suggestion","Contact Centre Agent","Salesforce Service Cloud",
      "Draft suggestion","Agent-approved or edited response",
      "100 percent of suggestions reviewed by the agent before use","Y","N",
      "Agents under time pressure can accept a suggestion without genuinely reviewing it"),
    S("3.1","Deliver the approved response to the customer","Contact Centre Agent","Salesforce Service Cloud",
      "Approved response","Delivered response",
      "Delivered without material delay to the interaction at 100 percent","N","N",
      "The tool's value depends entirely on genuine review happening, not on the tool alone"),
  ],
  kpis=["Suggestion generated within 3 seconds at 90 percent",
        "100 percent of suggestions reviewed by the agent before use",
        "Average handle time reduced against the pre-tool baseline",
        "Zero confirmed cases of an unreviewed suggestion reaching a customer"],
  risks=["Agents under time pressure accepting a suggestion without genuinely reviewing it",
         "A suggestion without a visible source citation being harder to trust and verify quickly",
         "Detection accuracy depending on interaction content that is not always structured",
         "The tool's governance value collapsing if genuine agent review stops actually happening"])

P("AC-CX-CC-05",
  desc="Contact centre staffing and shift scheduling are planned using a digital twin simulation to model "
       "capacity against forecast call volume, balancing service level against labour cost.",
  trig="The recurring workforce planning cycle runs, or a forecast volume change requires a schedule "
       "revision.",
  out="A staffing schedule that meets target service levels at forecast volume, validated through "
      "simulation before commitment.",
  note="A digital twin lets Air Canada test a staffing scenario against simulated volume before committing "
      "real labour cost to it, which is a materially different discipline from scheduling against a simple "
      "average.",
  phases=["Volume forecasting", "Simulation and scenario testing", "Schedule commitment"],
  steps=[
    S("1.1","Forecast call volume by interval","Workforce Planning Analyst","Simul8",
      "Historical volume and known demand drivers","Forecast volume by interval",
      "Forecast produced for 100 percent of scheduling intervals each cycle","N","N",
      "Volume spikes around irregular operations events are the hardest pattern to forecast reliably"),
    S("2.1","Simulate staffing scenarios against forecast","Workforce Planning Analyst","Simul8",
      "Volume forecast and candidate staffing levels","Simulated service level by scenario",
      "Multiple scenarios simulated before schedule commitment at 100 percent","N","N",
      "Simulation accuracy depends on how well the model reflects real agent skill mix and shrinkage"),
    S("2.2","Select staffing scenario against cost and service target","Workforce Planning Analyst","Simul8",
      "Simulated scenarios","Selected staffing plan",
      "Selected plan meets target service level in simulation at 100 percent","Y","N",
      "The cost-service trade-off decision has genuine commercial consequence either way it is resolved"),
    S("3.1","Publish shift schedules","Workforce Planning Analyst","Amazon Connect",
      "Selected staffing plan","Published agent shift schedules",
      "Published within the required lead time before the schedule period at 100 percent","N","N",
      "A late-published schedule reduces agents' ability to plan around it"),
  ],
  kpis=["Forecast produced for 100 percent of scheduling intervals each cycle",
        "Multiple scenarios simulated before schedule commitment at 100 percent",
        "Selected plan meets target service level in simulation at 100 percent",
        "Actual service level tracking within tolerance of the simulated forecast"],
  risks=["Volume spikes around irregular operations events being the hardest pattern to forecast reliably",
         "Simulation accuracy depending on how well the model reflects real agent skill mix and shrinkage",
         "The cost-service trade-off decision carrying genuine commercial consequence either way",
         "A late-published schedule reducing agents' ability to plan their availability around it"])

P("AC-CX-CC-06",
  desc="Payment card details are captured and processed securely within the contact centre interaction, "
       "meeting PCI-DSS requirements while an agent remains on the call.",
  trig="A customer needs to provide payment during a live contact centre interaction.",
  out="A securely processed payment with cardholder data never exposed to the agent or retained outside "
      "the compliant payment pathway.",
  note="Secure payment capture exists specifically so the agent handling the call never sees or hears the "
      "full card number, which is what keeps a live voice interaction compliant with PCI-DSS.",
  phases=["Secure capture initiation", "Isolated payment processing", "Confirmation"],
  steps=[
    S("1.1","Initiate secure payment capture","Contact Centre Agent","Amazon Connect",
      "Customer readiness to pay","Initiated secure capture session",
      "Initiated within the interaction without material delay at 100 percent","N","N",
      "A customer unfamiliar with the secure capture flow can be confused by the handoff from voice to keypad entry"),
    S("2.1","Capture card data outside agent access","Contact Centre Agent","Amazon Connect",
      "Customer keypad input","Captured card data in the isolated payment channel",
      "100 percent of card data captured outside agent audio and screen access","Y","N",
      "Any leakage of card data into the agent's audio or screen path is a direct PCI-DSS violation"),
    S("2.2","Process payment authorisation","Contact Centre Agent","SAP S/4HANA",
      "Captured card data","Payment authorisation result",
      "Authorisation processed within 10 seconds at 97 percent","N","N",
      "A failed authorisation requires the customer to re-enter card data through the same secure flow"),
    S("3.1","Confirm payment to the customer and agent","Contact Centre Agent","Salesforce Service Cloud",
      "Authorisation result","Confirmed payment status visible to the agent",
      "Confirmation visible to the agent within 5 seconds of authorisation at 100 percent","N","N",
      "The agent needs confirmation of success without ever seeing the underlying card data"),
  ],
  kpis=["100 percent of card data captured outside agent audio and screen access",
        "Authorisation processed within 10 seconds at 97 percent",
        "Zero confirmed PCI-DSS scope violations from contact centre payment capture",
        "Payment capture completion rate above target"],
  risks=["Any leakage of card data into the agent's audio or screen path constituting a direct PCI-DSS violation",
         "A customer unfamiliar with the secure capture handoff abandoning the payment mid-flow",
         "A failed authorisation requiring a full re-entry through the same secure flow, frustrating the customer",
         "The agent needing payment status confirmation without ever gaining visibility into the card data itself"])

# ── SS: Special Services and Accessibility ──────────────────────────────────
P("AC-CX-SS-01",
  desc="A customer's mobility aid, including wheelchairs and other assistive devices, is accepted, tracked "
       "and handled through the journey, from booking through arrival, under ATPDR obligations.",
  trig="A customer with a mobility aid requirement books a flight or checks in for travel.",
  out="The mobility aid correctly handled and tracked through every leg of the journey, delivered to the "
      "customer intact and on time at arrival.",
  note="In-app mobility aid tracking launched in December 2023 specifically because this handling had been "
      "a significant source of customer harm and complaint; the ATPDR obligations here are not discretionary "
      "service quality, they are regulatory requirements.",
  phases=["Booking and requirement capture", "Handling and tracking", "Arrival delivery"],
  steps=[
    S("1.1","Capture mobility aid details at booking","Special Services Agent","Amadeus Altea Reservations",
      "Customer-provided device details","Captured device profile in the booking",
      "Captured for 100 percent of declared mobility aid bookings","N","N",
      "Device dimensions and battery type details are not always fully provided at initial booking"),
    S("2.1","Accept and tag the mobility aid at check-in","Special Services Agent","Amadeus Altea DCS",
      "Physical device at check-in","Tagged and accepted device",
      "Accepted and tagged within the standard check-in window at 100 percent","N","N",
      "Battery-powered devices require specific handling documentation under dangerous goods rules"),
    S("2.2","Track device through handling milestones","Special Services Agent","Air Canada Mobile App",
      "Handling scan events","Real-time device status visible to the customer",
      "Status updated within 10 minutes of each handling milestone at 90 percent","N","N",
      "Device handling scan discipline needs to match the same rigour as checked baggage"),
    S("3.1","Deliver device at arrival gate or carousel","Special Services Agent","Amadeus Altea DCS",
      "Arrived device","Delivered device to the customer",
      "Delivered within 20 minutes of aircraft arrival at 95 percent","N","N",
      "A customer without their mobility aid at arrival faces immediate and serious personal impact"),
    S("3.2","Report and remediate any damage","Special Services Agent","SITA WorldTracer",
      "Damaged device on delivery","Damage report and remediation plan",
      "Damage reported and remediation initiated within 1 hour of identification at 100 percent","N","Y",
      "Device damage is a higher-severity incident than baggage damage and requires faster remediation"),
  ],
  kpis=["Accepted and tagged within the standard check-in window at 100 percent",
        "Delivered within 20 minutes of aircraft arrival at 95 percent",
        "Status updated within 10 minutes of each handling milestone at 90 percent",
        "Zero mobility aid damage incidents unreported beyond 1 hour"],
  risks=["A customer without their mobility aid at arrival facing immediate and serious personal impact",
         "Battery-powered device handling documentation being incomplete under dangerous goods rules",
         "Device damage being a higher-severity incident than baggage damage but not always handled with matching urgency",
         "Device dimensions and battery details not being fully captured at the original booking"])

P("AC-CX-SS-02",
  desc="A customer's accessible travel request, covering communication needs, boarding assistance and "
       "in-flight accommodation, is processed and communicated to every station and crew involved in the "
       "journey.",
  trig="A customer submits an accessibility request at booking or in advance of travel.",
  out="The customer's accessibility needs correctly recorded and communicated to every touchpoint in the "
      "journey, with assistance delivered as requested.",
  note="An accessibility request has to reach several independently operating touchpoints, the booking "
      "system, the departure station, the crew and any connecting station, and a gap at any one of them "
      "means the accommodation simply does not happen.",
  phases=["Request capture", "Cross-touchpoint communication", "Assistance delivery"],
  steps=[
    S("1.1","Capture the accessibility request","Special Services Agent","Amadeus Altea Reservations",
      "Customer-stated accessibility need","Captured request in the booking record",
      "Captured for 100 percent of submitted requests at booking or pre-travel","N","N",
      "Request categories do not always map precisely to what the customer actually needs"),
    S("2.1","Communicate request to departure station","Special Services Agent","Amadeus Altea DCS",
      "Captured request","Station-level assistance instruction",
      "Communicated at least 24 hours before departure for 95 percent of requests","N","N",
      "Late-submitted requests compress the notice window available to the station"),
    S("2.2","Communicate request to the flight crew","Special Services Agent","Jeppesen Crew",
      "Captured request","Crew briefing on the accessibility need",
      "Crew briefed before boarding for 100 percent of flagged requests","N","N",
      "Crew briefing has to reach the specific crew assigned to that flight, not a general notice"),
    S("2.3","Communicate request to connecting stations","Special Services Agent","Amadeus Altea DCS",
      "Captured request and connecting itinerary","Connecting station assistance instruction",
      "Communicated to 100 percent of connecting stations before the connection","Y","N",
      "A gap at a connecting station is a common single point of failure for the whole journey"),
    S("3.1","Deliver assistance at each touchpoint","Special Services Agent","Amadeus Altea DCS",
      "Station and crew instructions","Delivered assistance",
      "Delivered as requested for 95 percent of flagged interactions","N","N",
      "Assistance delivery quality depends on staffing levels the accessibility process itself does not control"),
  ],
  kpis=["Captured for 100 percent of submitted requests at booking or pre-travel",
        "Communicated at least 24 hours before departure for 95 percent of requests",
        "Communicated to 100 percent of connecting stations before the connection",
        "Delivered as requested for 95 percent of flagged interactions"],
  risks=["A gap at any single touchpoint, booking, station, crew or connection, meaning the accommodation does not happen",
         "A connecting station being a common single point of failure for an otherwise well-communicated request",
         "Late-submitted requests compressing the notice window available to the departure station",
         "Assistance delivery quality depending on station staffing levels outside the process's own control"])

P("AC-CX-SS-03",
  desc="An unaccompanied minor is accepted, supervised and handed off through the journey, from parent or "
       "guardian check-in through receiving-party verification at arrival.",
  trig="A booking is made for an unaccompanied minor, or the child arrives at the airport for check-in.",
  out="The unaccompanied minor safely delivered to a verified receiving party at destination, with "
      "supervision maintained throughout the journey.",
  note="Chain of custody is the defining requirement of this process: at no point in the journey can there "
      "be ambiguity about who is responsible for the child's safety.",
  phases=["Acceptance and documentation", "Journey supervision", "Receiving party verification"],
  steps=[
    S("1.1","Verify guardian consent and documentation","Special Services Agent","Amadeus Altea Reservations",
      "Guardian-provided consent and identification","Verified documentation",
      "Verified before acceptance for 100 percent of unaccompanied minor bookings","N","N",
      "Documentation requirements differ by destination, particularly for international travel"),
    S("1.2","Accept the minor into Air Canada's care","Special Services Agent","Amadeus Altea DCS",
      "Verified documentation","Formal acceptance with chain of custody record",
      "Chain of custody record initiated at 100 percent of acceptances","Y","N",
      "The acceptance record has to be unambiguous about the exact moment custody transfers from guardian to airline"),
    S("2.1","Maintain supervision through connections","Special Services Agent","Amadeus Altea DCS",
      "Chain of custody record","Maintained supervision through each connection",
      "Continuous supervision maintained for 100 percent of unaccompanied minor connections","N","N",
      "A connection at a hub with tight timing is the highest-risk point for a supervision gap"),
    S("3.1","Verify receiving party at destination","Special Services Agent","Amadeus Altea DCS",
      "Arrival and expected receiving party","Verified handoff to the correct receiving party",
      "Identity verified before handoff for 100 percent of arrivals","Y","N",
      "A receiving party who cannot be verified requires an escalation path that does not leave the child unsupervised"),
    S("3.2","Close the chain of custody record","Special Services Agent","Amadeus Altea DCS",
      "Verified handoff","Closed custody record",
      "Closed within 15 minutes of confirmed handoff at 100 percent","N","N",
      "An unclosed custody record leaves ambiguity about whether the handoff was actually completed correctly"),
  ],
  kpis=["Verified before acceptance for 100 percent of unaccompanied minor bookings",
        "Continuous supervision maintained for 100 percent of unaccompanied minor connections",
        "Identity verified before handoff for 100 percent of arrivals",
        "Zero chain of custody gaps recorded"],
  risks=["A connection at a hub with tight timing being the highest-risk point for a supervision gap",
         "A receiving party who cannot be verified requiring an escalation path that avoids leaving the child unsupervised",
         "An unclosed custody record leaving ambiguity about whether handoff actually completed correctly",
         "Documentation requirements differing by destination, particularly complicating international travel"])

P("AC-CX-SS-04",
  desc="A customer's special meal request or medical travel clearance is validated and provisioned through "
       "the booking and catering chain, or a fitness-to-fly clearance is obtained before travel is "
       "confirmed.",
  trig="A customer submits a special meal request or a medical condition requiring clearance before travel.",
  out="The special meal correctly provisioned on board, or medical clearance obtained and recorded before "
      "the booking is confirmed for travel.",
  note="A medical clearance decision is fundamentally different from a meal preference: it can determine "
      "whether a customer is permitted to travel at all, so the two threads of this process carry very "
      "different risk profiles despite sharing an intake channel.",
  phases=["Request and clearance intake", "Validation", "Provisioning or confirmation"],
  steps=[
    S("1.1","Receive special meal or medical clearance request","Special Services Agent","Amadeus Altea Reservations",
      "Customer-submitted request","Registered request",
      "Registered within 1 business day of submission at 100 percent","N","N",
      "Medical clearance requests need supporting documentation that customers do not always provide up front"),
    S("2.1","Validate medical fitness-to-fly where required","Medical Review Coordinator","Amadeus Altea Reservations",
      "Medical documentation","Fitness-to-fly determination",
      "Determined within the required lead time before travel at 95 percent","Y","N",
      "A late-arriving medical clearance can leave a booking unresolved close to the departure date"),
    S("2.2","Confirm special meal request against catering lead time","Special Services Agent","Amadeus Altea Reservations",
      "Meal request","Confirmed meal request within catering deadline",
      "Confirmed within the catering system's required lead time at 100 percent","N","N",
      "A request submitted after the catering cutoff cannot be guaranteed regardless of validity"),
    S("3.1","Provision meal or finalise medical clearance record","Special Services Agent","Amadeus Altea DCS",
      "Confirmed request or clearance","Provisioned meal or finalised clearance on the booking",
      "Finalised before departure for 98 percent of requests","N","N",
      "A clearance recorded in the booking system has to actually reach the operating crew for the flight"),
  ],
  kpis=["Registered within 1 business day of submission at 100 percent",
        "Determined within the required lead time before travel at 95 percent",
        "Confirmed within the catering system's required lead time at 100 percent",
        "Finalised before departure for 98 percent of requests"],
  risks=["A late-arriving medical clearance leaving a booking unresolved close to the departure date",
         "A meal request submitted after the catering cutoff being unable to be guaranteed regardless of validity",
         "A clearance recorded in the booking system not actually reaching the operating crew for the flight",
         "Medical documentation requirements not being provided up front, delaying a time-sensitive determination"])

P("AC-CX-SS-05",
  desc="A service animal is screened and accepted for travel under current regulatory requirements, "
       "distinct from an emotional support animal, with documentation validated before booking confirmation.",
  trig="A customer requests to travel with a service animal.",
  out="A correctly screened and accepted service animal booking, with documentation validated against "
      "current regulatory requirements.",
  note="Service animal acceptance criteria have tightened materially in recent years across the industry, "
      "which makes staying current with the regulatory definition, rather than an outdated internal policy, "
      "the main discipline in this process.",
  phases=["Documentation screening", "Regulatory validation", "Booking confirmation"],
  steps=[
    S("1.1","Receive service animal documentation","Special Services Agent","Amadeus Altea Reservations",
      "Customer-submitted documentation","Registered documentation",
      "Registered within 1 business day of submission at 100 percent","N","N",
      "Documentation formats vary and customers are not always aware of current requirements before submitting"),
    S("2.1","Validate documentation against current regulatory requirements","Special Services Agent","Amadeus Altea Reservations",
      "Submitted documentation","Validated or rejected documentation",
      "Validated against the current regulatory standard at 100 percent","Y","N",
      "Outdated internal reference material can cause a valid request to be incorrectly rejected or the reverse"),
    S("2.2","Communicate outcome to the customer","Special Services Agent","Salesforce Service Cloud",
      "Validation outcome","Communicated decision with reasoning",
      "Communicated within 3 business days of documentation receipt at 100 percent","N","N",
      "A rejection without clear reasoning generates avoidable escalation and complaint"),
    S("3.1","Confirm booking with accepted service animal","Special Services Agent","Amadeus Altea Reservations",
      "Accepted documentation","Confirmed booking with service animal flag",
      "Confirmed before travel for 100 percent of accepted requests","N","N",
      "The service animal flag has to reach the departure station and crew, not remain only in the booking record"),
  ],
  kpis=["Validated against the current regulatory standard at 100 percent",
        "Communicated within 3 business days of documentation receipt at 100 percent",
        "Confirmed before travel for 100 percent of accepted requests",
        "Zero decisions based on outdated regulatory reference material"],
  risks=["Outdated internal reference material causing a valid request to be rejected or an invalid one accepted",
         "A rejection communicated without clear reasoning generating avoidable escalation and complaint",
         "The service animal flag not reaching the departure station and crew despite being in the booking record",
         "Documentation format variability making consistent validation harder to apply"])

P("AC-CX-SS-06",
  desc="Group and event travel is serviced from booking through the travel date, coordinating a block of "
       "individual passengers with a shared itinerary and often shared special requirements.",
  trig="A confirmed group booking approaches its travel date, or a group-specific servicing request is "
       "received.",
  out="The group's travel serviced smoothly as a coordinated block, with individual passenger needs within "
      "the group correctly handled.",
  note="A group booking servicing failure is amplified: an issue affecting one group booking can affect "
      "dozens of passengers simultaneously, which raises the stakes on getting the group-level coordination "
      "right rather than treating it as many individual bookings.",
  phases=["Group finalisation", "Individual passenger detail collection", "Travel day coordination"],
  steps=[
    S("1.1","Finalise group passenger list","Group Sales Coordinator","Amadeus Altea Reservations",
      "Confirmed group booking","Finalised individual passenger names",
      "Finalised by the fare rule deadline at 100 percent","N","N",
      "Name changes and passenger substitutions within a group are common right up to the deadline"),
    S("2.1","Collect individual special requirements","Group Sales Coordinator","Amadeus Altea Reservations",
      "Group passenger list","Individual requirements captured within the group booking",
      "Captured for 100 percent of individual requirements before travel","N","N",
      "Individual special requirements within a group booking are easier to lose track of than for a standalone passenger"),
    S("2.2","Coordinate seat assignment for the group","Group Sales Coordinator","Amadeus Altea Inventory",
      "Group booking and preferences","Coordinated seat assignment",
      "Group seating coordinated before check-in opens at 95 percent","N","N",
      "Seat coordination for a large group competes with individual passenger seat selection on the same flight"),
    S("3.1","Coordinate group check-in and boarding","Group Sales Coordinator","Amadeus Altea DCS",
      "Confirmed group arrangements","Coordinated group check-in and boarding",
      "Group check-in completed without disrupting the standard boarding process at 100 percent","N","N",
      "A large group at check-in or boarding can create a bottleneck for individual passengers if not managed"),
  ],
  kpis=["Finalised by the fare rule deadline at 100 percent",
        "Captured for 100 percent of individual requirements before travel",
        "Group seating coordinated before check-in opens at 95 percent",
        "Group check-in completed without disrupting standard boarding at 100 percent"],
  risks=["Individual special requirements within a group booking being easier to lose track of than standalone",
         "Seat coordination for a large group competing with individual passenger selection on the same flight",
         "A large group creating a check-in or boarding bottleneck for other passengers if not managed",
         "Name changes and substitutions within a group persisting right up to the fare rule deadline"])
