# -*- coding: utf-8 -*-
"""AC-CX-DC — Customer Experience and Channels > Digital Channels (6 processes)."""
from content_lib import P, S

P("AC-CX-DC-01",
  desc="A customer searches, selects and completes a booking through aircanada.com or the mobile app, from "
       "initial search through payment confirmation.",
  trig="A customer initiates a flight search on a direct digital channel.",
  out="A confirmed booking with payment processed and confirmation delivered to the customer.",
  note="The direct channel booking flow is the highest-traffic transaction in the entire estate, so a "
       "friction point here is amplified across a very large number of customers before anyone notices a "
       "pattern.",
  phases=["Search and selection", "Booking and payment", "Confirmation"],
  steps=[
    S("1.1","Process flight search request","Digital Platform Engineer","Amadeus Altea NDC",
      "Search criteria from the customer","Returned fare and availability options",
      "Search results returned within 3 seconds at 95 percent","N","N",
      "Peak search volume periods can push response time beyond the target"),
    S("1.2","Present ancillary offers during selection","Digital Platform Engineer","Amadeus Anytime Merchandising",
      "Selected fare","Presented ancillary bundle options",
      "Offers presented without materially slowing the selection flow at 100 percent","N","N",
      "Too many ancillary prompts in sequence measurably reduces booking completion"),
    S("2.1","Capture passenger and contact details","Digital Platform Engineer","aircanada.com",
      "Customer-entered details","Captured booking details",
      "Form completion rate above target for 90 percent of sessions","N","N",
      "Required field validation that is too strict abandons otherwise valid bookings"),
    S("2.2","Process payment securely","Digital Platform Engineer","aircanada.com",
      "Payment details","Processed payment authorisation",
      "Payment processed within 5 seconds at 98 percent","N","Y",
      "Payment gateway timeouts during peak periods are the leading cause of abandoned bookings at this step"),
    S("3.1","Issue booking confirmation","Digital Platform Engineer","Amadeus Altea Reservations",
      "Authorised payment","Issued PNR with confirmation",
      "Confirmation issued within 10 seconds of payment at 99 percent","N","N",
      "A confirmation delay after payment has already been captured creates real customer anxiety"),
    S("3.2","Deliver confirmation across channels","Digital Platform Engineer","Air Canada Mobile App",
      "Issued booking","Delivered confirmation email and app notification",
      "Delivered within 2 minutes of issuance at 98 percent","N","N",
      "Email delivery depends on infrastructure outside Air Canada's direct control"),
  ],
  kpis=["Search results returned within 3 seconds at 95 percent",
        "Payment processed within 5 seconds at 98 percent",
        "Booking completion rate from search to confirmation meeting target",
        "Confirmation delivered within 2 minutes of issuance at 98 percent"],
  risks=["Payment gateway timeouts during peak periods being the leading cause of abandoned bookings",
         "Too many sequential ancillary prompts measurably reducing overall booking completion",
         "A confirmation delay after payment capture creating real customer anxiety and contact volume",
         "Strict field validation abandoning otherwise valid bookings at the details capture step"])

P("AC-CX-DC-02",
  desc="A customer checks in and receives a boarding pass through the mobile app, from eligibility opening "
       "through boarding pass issuance.",
  trig="Online check-in opens for a booked flight, typically 24 hours before departure.",
  out="An issued digital boarding pass, with the customer checked in and any applicable seat or bag "
      "selection completed.",
  note="Mobile check-in has to work reliably at scale in the exact hour before a bank of departures, which "
      "makes it one of the highest-consequence peak-load moments in the digital estate.",
  phases=["Eligibility and identity", "Check-in processing", "Boarding pass delivery"],
  steps=[
    S("1.1","Confirm check-in eligibility","Digital Platform Engineer","Amadeus Altea DCS",
      "Booking and current time against departure","Eligibility confirmation",
      "Eligibility correctly assessed for 100 percent of check-in attempts","N","N",
      "Eligibility rules differ by fare class, destination and international document requirements"),
    S("1.2","Verify travel document requirements","Digital Platform Engineer","CBSA API and PNR",
      "Destination and passenger document data","Document verification result",
      "Verified before check-in completes for 100 percent of international itineraries","Y","N",
      "Document requirements change by destination and are not always current in the verification logic"),
    S("2.1","Process check-in and seat confirmation","Digital Platform Engineer","Amadeus Altea DCS",
      "Verified eligibility","Checked-in passenger with confirmed seat",
      "Check-in completed within 5 seconds at 97 percent","N","N",
      "Peak check-in volume in the hour before a large departure bank strains system response time"),
    S("3.1","Generate and issue boarding pass","Digital Platform Engineer","Air Canada Mobile App",
      "Completed check-in","Issued digital boarding pass",
      "Boarding pass issued within 5 seconds of check-in completion at 98 percent","N","N",
      "A boarding pass that fails to generate leaves the customer with no proof of check-in"),
    S("3.2","Sync boarding pass across devices and channels","Digital Platform Engineer","Air Canada Mobile App",
      "Issued boarding pass","Synced boarding pass availability",
      "Synced within 30 seconds across app and wallet integrations at 95 percent","N","N",
      "A boarding pass visible on one device but not another creates confusion at the gate"),
  ],
  kpis=["Check-in completed within 5 seconds at 97 percent",
        "Boarding pass issued within 5 seconds of check-in completion at 98 percent",
        "Eligibility correctly assessed for 100 percent of check-in attempts",
        "Peak-hour check-in system availability at 99.9 percent"],
  risks=["Peak check-in volume in the hour before a large departure bank straining system response time",
         "A boarding pass failing to generate, leaving the customer with no proof of check-in",
         "Document requirement logic not staying current with destination-specific changes",
         "A boarding pass visible on one device but not synced to another, causing gate confusion"])

P("AC-CX-DC-03",
  desc="A customer tracks their checked baggage through the mobile app, from bag tag scan at acceptance "
       "through delivery confirmation at the destination carousel.",
  trig="A bag is tagged and accepted at check-in for a customer who has enabled bag tracking.",
  out="Real-time bag status visible to the customer through each handling milestone, correctly reflecting "
      "the bag's actual physical location.",
  note="In-app bag tracking was launched specifically to reduce the anxiety and contact volume around "
      "checked baggage, so its value is entirely dependent on the underlying scan events actually being "
      "captured and surfaced promptly.",
  phases=["Bag tag and scan capture", "Status tracking", "Delivery confirmation"],
  steps=[
    S("1.1","Capture bag tag scan events","Digital Platform Engineer","Baggage Reconciliation System",
      "Physical scan at each handling milestone","Captured scan event",
      "Scan events captured for 95 percent of handling milestones","N","N",
      "Manual handling steps at some stations do not consistently generate a scan event"),
    S("2.1","Update bag status in real time","Digital Platform Engineer","Air Canada Mobile App",
      "Captured scan events","Updated bag status visible to the customer",
      "Status updated within 5 minutes of each scan event at 90 percent","N","N",
      "A missing scan event leaves the customer's tracking view showing a stale status"),
    S("2.2","Flag bags with anomalous handling patterns","Digital Platform Engineer","SITA WorldTracer",
      "Bag status history","Flagged anomaly for proactive customer contact",
      "Anomalies flagged within 30 minutes of the missed expected scan at 85 percent","Y","N",
      "Distinguishing a genuinely mishandled bag from a delayed but normal scan event requires tuning"),
    S("3.1","Confirm delivery at destination","Digital Platform Engineer","Baggage Reconciliation System",
      "Carousel delivery scan","Confirmed delivery status",
      "Delivery confirmed within 5 minutes of the carousel scan at 90 percent","N","N",
      "A missing final scan leaves the app showing the bag as still in transit after the customer already has it"),
  ],
  kpis=["Scan events captured for 95 percent of handling milestones",
        "Status updated within 5 minutes of each scan event at 90 percent",
        "Anomalies flagged within 30 minutes of a missed expected scan at 85 percent",
        "Customer contact volume for bag status enquiries reduced against pre-launch baseline"],
  risks=["Manual handling steps at some stations not consistently generating the scan event the app depends on",
         "A missing scan leaving the customer's tracking view stale or showing an inaccurate status",
         "A missing final scan showing a bag as in transit after the customer has already collected it",
         "Anomaly detection tuning that is too loose or too tight relative to genuine mishandling"])

P("AC-CX-DC-04",
  desc="Web and app content, including fare rules, policy pages and campaign content, is published and "
       "maintained with full English and French parity as required under the Official Languages Act.",
  trig="A content update is required for a policy change, campaign launch or scheduled review.",
  out="Published content live in both official languages simultaneously, accurate and consistent with the "
      "underlying policy or system state.",
  note="Bilingual parity is a legal obligation on every customer-facing content flow, not a translation "
      "nicety, and content published in one language before the other is a compliance gap even if brief.",
  phases=["Content authoring", "Bilingual production", "Publication and verification"],
  steps=[
    S("1.1","Author source content","Digital Content Editor","Adobe Experience Manager",
      "Content requirement and policy input","Authored source content",
      "Authored within the content request lead time at 100 percent","N","N",
      "Source content is usually authored in one language first, which structurally risks a parity gap"),
    S("2.1","Produce the parallel-language version","Digital Content Editor","Adobe Experience Manager",
      "Authored source content","Parallel-language content",
      "Parallel version produced before either language is published at 100 percent","Y","N",
      "Translation quality assurance is a distinct step from translation itself and is sometimes skipped under deadline"),
    S("2.2","Validate content accuracy against policy","Digital Content Editor","Adobe Experience Manager",
      "Both language versions","Validated accurate content",
      "Validated for 100 percent of policy-related content before publication","N","N",
      "A content error that is caught in one language is not automatically caught in the other"),
    S("3.1","Publish both languages simultaneously","Digital Content Editor","aircanada.com",
      "Validated bilingual content","Live bilingual content",
      "Both languages published within the same publication event at 100 percent","N","N",
      "A publishing tool limitation can cause one language to go live before the other despite the intent"),
    S("3.2","Verify parity post-publication","Digital Content Editor","aircanada.com",
      "Published content","Verified parity confirmation",
      "Verified within 24 hours of publication at 100 percent","N","N",
      "Parity verification is often manual and does not scale well to a large content volume"),
  ],
  kpis=["Both languages published within the same publication event at 100 percent",
        "Validated for 100 percent of policy-related content before publication",
        "Verified within 24 hours of publication at 100 percent",
        "Zero confirmed parity gaps open for more than 24 hours"],
  risks=["Source content structurally authored in one language first, creating a risk of a parity gap",
         "A publishing tool limitation causing one language to go live before the other despite the intent",
         "A content error caught in one language not automatically being caught in the other",
         "Manual parity verification not scaling well to a large and continuous content volume"])

P("AC-CX-DC-05",
  desc="Digital experiences are personalised and A/B tested using Adobe Target, tailoring content and offer "
       "presentation to customer segments and measuring the impact of variant changes.",
  trig="A personalisation or experimentation opportunity is identified, or a scheduled test concludes and "
       "requires a rollout decision.",
  out="A validated personalisation rule or winning test variant rolled out to the full customer base.",
  note="Personalisation and testing on a channel this high-traffic carries real commercial stakes: a "
       "poorly designed test can degrade conversion for a meaningful customer volume before the result is "
       "even known.",
  phases=["Test design", "Execution and measurement", "Rollout decision"],
  steps=[
    S("1.1","Design the test hypothesis and variants","Digital Product Manager","Adobe Target",
      "Personalisation or conversion opportunity","Designed test with control and variant",
      "Test design reviewed and approved before launch at 100 percent","N","N",
      "A poorly isolated variant can be affected by an unrelated concurrent change on the same page"),
    S("2.1","Launch and run the test","Digital Product Manager","Adobe Target",
      "Approved test design","Live test collecting data",
      "Statistically significant sample reached within the planned test window at 85 percent","N","N",
      "Traffic allocation has to balance statistical power against limiting exposure to an underperforming variant"),
    S("2.2","Monitor for early negative signal","Digital Product Manager","Adobe Analytics",
      "Live test performance","Early stop decision or continuation",
      "Reviewed daily during the test window at 100 percent","N","Y",
      "Stopping too early on noisy early data risks a wrong rollout decision"),
    S("3.1","Analyse results and decide rollout","Digital Product Manager","Adobe Analytics",
      "Completed test data","Rollout, iteration or discard decision",
      "Decision made within 5 business days of test conclusion at 100 percent","N","N",
      "A result that is statistically significant is not always commercially meaningful at the observed magnitude"),
  ],
  kpis=["Test design reviewed and approved before launch at 100 percent",
        "Statistically significant sample reached within the planned test window at 85 percent",
        "Reviewed daily during the test window at 100 percent",
        "Decision made within 5 business days of test conclusion at 100 percent"],
  risks=["A poorly isolated test variant being affected by an unrelated concurrent page change",
         "Stopping a test too early on noisy data and making the wrong rollout decision",
         "A statistically significant result that is not commercially meaningful at the observed magnitude",
         "Traffic allocation exposing too many customers to an underperforming variant before detection"])

P("AC-CX-DC-06",
  desc="Digital channel incidents, including outages and degraded performance on aircanada.com or the "
       "mobile app, are detected, communicated and resolved, with a fallback path activated for affected "
       "customers.",
  trig="A monitoring alert detects a digital channel outage or material performance degradation.",
  out="Restored digital channel service, with affected customers informed and directed to an alternative "
      "channel during the incident.",
  note="A digital channel outage does not stop customer demand, it just displaces it onto the contact "
      "centre and airport counters, so the incident response has to plan for that displacement, not only for "
      "the technical restoration.",
  phases=["Detection and triage", "Customer communication and fallback", "Restoration and review"],
  steps=[
    S("1.1","Detect and triage the incident","Digital Platform Engineer","Dynatrace",
      "Monitoring alert","Triaged incident with severity classification",
      "Triaged within 5 minutes of detection at 100 percent","N","N",
      "Distinguishing a genuine customer-impacting outage from a monitoring false positive under pressure is difficult"),
    S("1.2","Activate the incident response","Digital Platform Engineer","ITSM Platform",
      "Triaged incident","Activated incident response with an incident commander",
      "Activated within 10 minutes of triage for severity 1 incidents at 100 percent","N","N",
      "Weekend and overnight incident response depends on on-call coverage that can be thinner than business hours"),
    S("2.1","Communicate status to affected customers","Digital Platform Engineer","aircanada.com",
      "Active incident","Published status update",
      "First status update published within 15 minutes of activation at 90 percent","N","N",
      "A status page hosted on the same infrastructure as the outage may itself be unavailable"),
    S("2.2","Redirect customers to a fallback channel","Digital Platform Engineer","Amazon Connect",
      "Active incident","Customers directed to contact centre or airport counter",
      "Fallback guidance published within 20 minutes of activation at 90 percent","N","N",
      "Fallback redirection increases contact centre and airport volume that those channels may not be staffed to absorb"),
    S("3.1","Restore service and confirm resolution","Digital Platform Engineer","Dynatrace",
      "Applied fix","Confirmed restored service",
      "Restoration confirmed with monitoring evidence at 100 percent","N","N",
      "A fix that resolves the symptom without addressing the root cause risks recurrence"),
    S("3.2","Conduct post-incident review","Digital Platform Engineer","ITSM Platform",
      "Resolved incident","Documented review with root cause and follow-up actions",
      "Review conducted within 5 business days of resolution for severity 1 incidents at 100 percent","N","N",
      "Follow-up actions from a review are not always tracked through to actual completion"),
  ],
  kpis=["Triaged within 5 minutes of detection at 100 percent",
        "First status update published within 15 minutes of activation at 90 percent",
        "Restoration confirmed with monitoring evidence at 100 percent",
        "Review conducted within 5 business days of resolution for severity 1 incidents at 100 percent"],
  risks=["A digital outage displacing demand onto a contact centre and airport counters not staffed to absorb it",
         "A status page hosted on the same infrastructure as the outage becoming unavailable at the worst moment",
         "A fix resolving the symptom without addressing root cause, risking recurrence",
         "Follow-up actions from a post-incident review not being tracked through to actual completion"])
