# -*- coding: utf-8 -*-
"""AC-FO-FD — Flight Planning and Dispatch (6) and AC-FO-WX — Weather, NOTAM and Nav Data (6)."""
from content_lib import P, S

# ── FD: Flight Planning and Dispatch ────────────────────────────────────────
P("AC-FO-FD-01",
  desc="An operational flight plan is constructed in NetLine Ops for each flight, covering route, altitude, "
       "fuel and alternate airport selection before dispatch release.",
  trig="A flight's dispatch preparation window opens ahead of scheduled departure.",
  out="A complete, validated operational flight plan ready for dispatch release and crew briefing.",
  note="The flight plan is the technical foundation every subsequent dispatch decision builds on; an error "
       "here propagates into fuel policy, alternate selection and ultimately the dispatch release itself.",
  phases=["Route and altitude planning", "Fuel and performance calculation", "Plan validation"],
  steps=[
    S("1.1","Select route and cruise altitude","Flight Dispatcher","NetLine/Ops",
      "Flight schedule and available routings","Selected route and altitude profile",
      "Route selected within the planning window at 100 percent","N","N",
      "Route optimisation for wind and airspace can conflict with published preferred routings"),
    S("1.2","Calculate fuel requirement","Flight Dispatcher","NetLine/Ops",
      "Route, altitude and weather data","Calculated fuel load",
      "Fuel calculated within regulatory reserve requirements at 100 percent","N","N",
      "Fuel calculation depends on weather data that can change materially between planning and departure"),
    S("2.1","Select alternate airports","Flight Dispatcher","NetLine/Ops",
      "Route and destination weather forecast","Selected alternates meeting regulatory minimums",
      "Alternates selected meeting regulatory minimums at 100 percent","Y","N",
      "Marginal destination weather can require an alternate selection that adds meaningful fuel burden"),
    S("2.2","Verify aircraft performance limits","Flight Dispatcher","Weight and Balance System",
      "Planned weight and runway conditions","Verified performance within limits",
      "Verified before plan finalisation at 100 percent","Y","N",
      "Performance limits at high-elevation or short-runway destinations require careful margin verification"),
    S("3.1","Validate the complete flight plan","Flight Dispatcher","NetLine/Ops",
      "Assembled plan components","Validated flight plan",
      "Validated within the planning window at 100 percent","N","N",
      "A plan validated against stale weather data needs to be re-checked closer to departure"),
    S("3.2","Transmit plan for dispatch release","Flight Dispatcher","NAV CANADA",
      "Validated plan","Filed flight plan",
      "Filed within the required lead time before departure at 100 percent","N","N",
      "A late filing compresses the time available for NAV CANADA processing"),
  ],
  kpis=["Fuel calculated within regulatory reserve requirements at 100 percent",
        "Alternates selected meeting regulatory minimums at 100 percent",
        "Filed within the required lead time before departure at 100 percent",
        "Plan revision rate due to late weather change tracked against target"],
  risks=["Fuel calculation depending on weather data that can change materially before departure",
         "Marginal destination weather requiring an alternate that adds meaningful fuel burden late in planning",
         "A plan validated against data that goes stale before it is actually used for dispatch release",
         "Performance limit verification at a high-elevation or short-runway destination requiring careful margin checks"])

P("AC-FO-FD-02",
  desc="Fuel policy, including tankering decisions where fuel is carried from a cheaper origin to avoid a "
       "more expensive destination purchase, is applied within safety and performance constraints.",
  trig="Flight planning reaches the fuel decision point for a route with a material fuel price differential.",
  out="A fuel loading decision that captures available cost savings without compromising performance "
      "margins or regulatory reserves.",
  note="Tankering trades fuel cost savings against the extra fuel burn from carrying additional weight, so "
      "the decision only pays off within a defined price differential and performance envelope.",
  phases=["Tankering evaluation", "Performance constraint check", "Fuel loading decision"],
  steps=[
    S("1.1","Evaluate fuel price differential","Flight Dispatcher","NetLine/Ops",
      "Origin and destination fuel prices","Calculated price differential",
      "Evaluated for 100 percent of eligible routes each planning cycle","N","N",
      "Fuel price data currency affects the accuracy of the tankering economics"),
    S("2.1","Assess performance impact of additional fuel weight","Flight Dispatcher","Weight and Balance System",
      "Candidate tankering fuel load","Performance impact assessment",
      "Assessed before the tankering decision is finalised at 100 percent","Y","N",
      "Additional weight can push a marginal-runway departure outside its performance limit"),
    S("2.2","Confirm reserve and regulatory compliance","Flight Dispatcher","NetLine/Ops",
      "Candidate fuel load","Confirmed compliance with reserve requirements",
      "Confirmed for 100 percent of tankering decisions","N","N",
      "Tankering fuel must not be confused with or substitute for mandatory reserve fuel"),
    S("3.1","Finalise fuel loading decision","Flight Dispatcher","NetLine/Ops",
      "Assessed and confirmed factors","Finalised fuel load in the flight plan",
      "Finalised within the planning window at 100 percent","N","N",
      "A tankering decision made too early can be invalidated by a later performance-limiting factor"),
  ],
  kpis=["Evaluated for 100 percent of eligible routes each planning cycle",
        "Confirmed for 100 percent of tankering decisions against reserve requirements",
        "Net fuel cost savings from the tankering programme tracked against target",
        "Zero tankering decisions that compromised a performance limit"],
  risks=["Additional tankering weight pushing a marginal-runway departure outside its performance limit",
         "Tankering fuel being confused with or substituted for mandatory regulatory reserve fuel",
         "A tankering decision made early in planning being invalidated by a later performance-limiting factor",
         "Fuel price data currency affecting the accuracy of the underlying tankering economics"])

P("AC-FO-FD-03",
  desc="ETOPS extended-range routings and oceanic tracks are planned for long-haul flights, incorporating "
       "the specific diversion and communication requirements of remote-area operation.",
  trig="A long-haul flight plan requires an ETOPS or oceanic routing.",
  out="A validated ETOPS or oceanic flight plan with diversion airports, communication procedures and fuel "
      "reserves meeting the specific extended-range requirements.",
  note="Extended-range operation carries a materially different risk profile than a domestic sector, since "
      "a diversion decision may need to be executed with far fewer alternate options within reach.",
  phases=["Diversion planning", "Communication and oceanic clearance", "ETOPS compliance validation"],
  steps=[
    S("1.1","Identify eligible diversion airports along the route","Flight Dispatcher","NetLine/Ops",
      "Planned oceanic or extended-range route","Identified diversion airport set",
      "Diversion airports identified for 100 percent of ETOPS sectors","N","N",
      "Diversion airport availability and suitability can change with local weather or operational status"),
    S("1.2","Calculate ETOPS entry point and time to alternate","Flight Dispatcher","NetLine/Ops",
      "Route and diversion airports","Calculated ETOPS entry point and diversion time",
      "Calculated within the aircraft's certified ETOPS rating at 100 percent","Y","N",
      "The calculation depends on aircraft-specific certification limits that must not be exceeded"),
    S("2.1","Obtain oceanic clearance","Flight Dispatcher","NAV CANADA",
      "Filed oceanic route","Confirmed oceanic clearance",
      "Clearance obtained before entering oceanic airspace at 100 percent","N","N",
      "Oceanic clearance timing is coordinated with multiple air traffic control authorities across the route"),
    S("2.2","Confirm communication and datalink procedures","Flight Dispatcher","ACARS Datalink",
      "Route and clearance","Confirmed communication procedure for the sector",
      "Confirmed for 100 percent of oceanic sectors before departure","N","N",
      "Communication procedure requirements vary by oceanic region and are not uniform across the route"),
    S("3.1","Validate complete ETOPS compliance","Flight Dispatcher","NetLine/Ops",
      "Assembled plan components","Validated ETOPS-compliant flight plan",
      "Validated before dispatch release for 100 percent of ETOPS flights","N","N",
      "A late change to diversion airport status has to trigger a full ETOPS re-validation"),
  ],
  kpis=["Diversion airports identified for 100 percent of ETOPS sectors",
        "Calculated within the aircraft's certified ETOPS rating at 100 percent",
        "Validated before dispatch release for 100 percent of ETOPS flights",
        "Clearance obtained before entering oceanic airspace at 100 percent"],
  risks=["A diversion airport becoming unsuitable due to weather or operational status after planning completes",
         "A late change to diversion airport status not triggering a full ETOPS re-validation",
         "Communication procedure requirements varying by oceanic region in ways easy to miss",
         "Oceanic clearance timing depending on coordination across multiple air traffic control authorities"])

P("AC-FO-FD-04",
  desc="The dispatch release is issued and jointly signed by the dispatcher and the flight's captain, "
       "formalising the shared responsibility for the flight's operational plan before departure.",
  trig="The operational flight plan is finalised and ready for dispatch release ahead of departure.",
  out="A signed dispatch release with joint dispatcher and captain sign-off, authorising the flight to "
      "proceed.",
  note="Dispatch release under joint operational control is a defining feature of how Air Canada, like most "
       "major carriers, splits authority: the dispatcher and captain are both accountable, and either can "
       "decline to release the flight.",
  phases=["Release preparation", "Captain briefing and review", "Joint sign-off"],
  steps=[
    S("1.1","Prepare the dispatch release package","Flight Dispatcher","NetLine/Ops",
      "Finalised flight plan","Assembled dispatch release package",
      "Package assembled within the required lead time before departure at 100 percent","N","N",
      "A late-changing weather or NOTAM factor can require the package to be reassembled close to departure"),
    S("2.1","Brief the captain on the flight plan","Flight Dispatcher","ACARS Datalink",
      "Dispatch release package","Captain briefing delivered",
      "Briefing delivered before the captain's review at 100 percent","N","N",
      "Briefing has to convey the material risk factors, not just the mechanical plan details"),
    S("2.2","Captain reviews and raises questions","Flight Dispatcher","NetLine/Ops",
      "Delivered briefing","Resolved captain questions or requested plan revision",
      "Questions resolved before sign-off for 100 percent of releases","Y","N",
      "A captain's requested revision close to departure time can compress the remaining planning window"),
    S("3.1","Execute joint sign-off","Flight Dispatcher","NetLine/Ops",
      "Reviewed release","Signed dispatch release",
      "Signed before scheduled departure at 100 percent","N","N",
      "Either party declining to sign halts the flight until the underlying concern is resolved"),
  ],
  kpis=["Package assembled within the required lead time before departure at 100 percent",
        "Questions resolved before sign-off for 100 percent of releases",
        "Signed before scheduled departure at 100 percent",
        "Zero flights released without complete joint sign-off"],
  risks=["A late-changing weather or NOTAM factor requiring the release package to be reassembled close to departure",
         "A captain's requested revision close to departure compressing the remaining planning window",
         "Briefing that conveys mechanical plan details without adequately communicating material risk factors",
         "Either party declining to sign halting the flight until the underlying concern is genuinely resolved"])

P("AC-FO-FD-05",
  desc="Final passenger, cargo and fuel weight is confirmed and the load plan calculated, feeding the "
       "loadsheet that governs the aircraft's centre of gravity for departure.",
  trig="Boarding and cargo loading approach completion ahead of a flight's scheduled departure.",
  out="A calculated, validated load plan within centre of gravity limits, ready for loadsheet issuance.",
  note="Load planning sits at the convergence of several independently changing inputs, passenger count, "
       "cargo weight and fuel load, arriving from different systems on their own timelines right up to the "
       "close of loading.",
  phases=["Load data collection", "Centre of gravity calculation", "Load plan finalisation"],
  steps=[
    S("1.1","Confirm final passenger count and distribution","Weight and Balance Coordinator","Amadeus Altea DCS",
      "Check-in and boarding data","Confirmed passenger count and cabin distribution",
      "Confirmed within the standard pre-departure window at 100 percent","N","N",
      "Late passenger changes right up to door close affect a calculation already in progress"),
    S("2.1","Confirm cargo and baggage weight","Weight and Balance Coordinator","Baggage Reconciliation System",
      "Loaded cargo and baggage data","Confirmed cargo and baggage weight",
      "Confirmed before final load calculation at 100 percent","N","N",
      "Actual loaded weight can differ from the planned weight communicated earlier in the process"),
    S("2.2","Calculate centre of gravity","Weight and Balance Coordinator","Weight and Balance System",
      "Passenger, cargo and fuel weight data","Calculated centre of gravity position",
      "Calculated within centre of gravity limits at 100 percent","Y","N",
      "A late weight change close to departure requires a fast recalculation under time pressure"),
    S("3.1","Finalise the load plan","Weight and Balance Coordinator","Weight and Balance System",
      "Validated centre of gravity calculation","Finalised load plan",
      "Finalised before loadsheet issuance at 100 percent","N","N",
      "A finalised plan that does not match actual loading requires correction before the aircraft can depart"),
  ],
  kpis=["Calculated within centre of gravity limits at 100 percent",
        "Confirmed before final load calculation at 100 percent",
        "Finalised before loadsheet issuance at 100 percent",
        "Late load-change recalculation completed within the departure window at target rate"],
  risks=["Late passenger or cargo changes right up to door close affecting a calculation already in progress",
         "Actual loaded weight differing from the planned weight communicated earlier",
         "A fast recalculation under time pressure introducing an error close to departure",
         "A finalised plan not matching actual loading, requiring correction before the aircraft can depart"])

P("AC-FO-FD-06",
  desc="The final loadsheet is issued to the flight crew, confirming the aircraft's actual weight and "
       "balance for departure, and any last-minute change is incorporated before off-block.",
  trig="The load plan is finalised and ready for loadsheet issuance ahead of departure.",
  out="A confirmed loadsheet delivered to the flight crew, with the aircraft cleared to depart within its "
      "weight and balance limits.",
  note="The loadsheet is the last document in the chain before the aircraft can leave the gate, so it is "
      "also where every upstream planning error, if any survived this far, becomes visible.",
  phases=["Loadsheet generation", "Crew delivery and acknowledgement", "Last-minute change handling"],
  steps=[
    S("1.1","Generate the loadsheet","Weight and Balance Coordinator","Weight and Balance System",
      "Finalised load plan","Generated loadsheet",
      "Generated within the required lead time before off-block at 100 percent","N","N",
      "Loadsheet generation timing has to fit within the remaining window before scheduled departure"),
    S("2.1","Deliver loadsheet to the flight crew","Weight and Balance Coordinator","ACARS Datalink",
      "Generated loadsheet","Delivered loadsheet",
      "Delivered before off-block for 100 percent of flights","N","N",
      "Datalink delivery depends on connectivity that can be degraded at some stations"),
    S("2.2","Obtain crew acknowledgement","Weight and Balance Coordinator","ACARS Datalink",
      "Delivered loadsheet","Crew acknowledgement",
      "Acknowledged before pushback clearance at 100 percent","Y","N",
      "An unacknowledged loadsheet has to be actively followed up rather than assumed received"),
    S("3.1","Process last-minute weight changes","Weight and Balance Coordinator","Weight and Balance System",
      "Change after loadsheet issuance","Revised loadsheet",
      "Revised loadsheet issued within 5 minutes of a material change at 90 percent","N","Y",
      "A last-minute change after the crew has already begun departure preparation requires urgent recalculation"),
  ],
  kpis=["Delivered before off-block for 100 percent of flights",
        "Acknowledged before pushback clearance at 100 percent",
        "Revised loadsheet issued within 5 minutes of a material change at 90 percent",
        "Zero departures with an unacknowledged final loadsheet"],
  risks=["Datalink delivery being degraded at some stations, delaying loadsheet receipt",
         "An unacknowledged loadsheet being assumed received rather than actively followed up",
         "A last-minute weight change after departure preparation has begun requiring urgent recalculation",
         "Every upstream planning error, if any survived this far, becoming visible only at this final step"])

# ── WX: Weather, NOTAM and Nav Data ─────────────────────────────────────────
P("AC-FO-WX-01",
  desc="A comprehensive weather briefing package is assembled for each flight, covering departure, en "
       "route and destination conditions along with significant weather phenomena along the route.",
  trig="Flight planning reaches the weather briefing stage ahead of dispatch release.",
  out="A complete weather briefing package incorporated into the flight plan and available to the crew.",
  note="Weather data currency is the defining quality attribute here: a briefing package assembled too "
       "early in the planning cycle can already be stale by the time the flight actually departs.",
  phases=["Data compilation", "Significant weather assessment", "Package delivery"],
  steps=[
    S("1.1","Compile departure, en route and destination weather","Flight Dispatcher","NAV CANADA",
      "Current weather observations and forecasts","Compiled weather data by phase of flight",
      "Compiled within the standard pre-dispatch window at 100 percent","N","N",
      "Weather forecast confidence decreases the further out the observation window extends"),
    S("1.2","Assess significant weather along the route","Flight Dispatcher","NAV CANADA",
      "Route and compiled weather data","Assessed significant weather phenomena",
      "Assessed for 100 percent of flights before dispatch","Y","N",
      "Convective weather along a route can develop faster than the standard briefing refresh cycle"),
    S("2.1","Incorporate weather into the flight plan","Flight Dispatcher","NetLine/Ops",
      "Assessed weather","Weather-adjusted flight plan",
      "Incorporated before dispatch release at 100 percent","N","N",
      "A weather-driven route change can cascade into a fuel and performance recalculation"),
    S("3.1","Deliver briefing package to the crew","Flight Dispatcher","Jeppesen FliteDeck Pro",
      "Finalised weather-adjusted plan","Delivered briefing package",
      "Delivered before crew briefing at 100 percent","N","N",
      "A package delivered too early can already be superseded by an update at the actual briefing time"),
  ],
  kpis=["Compiled within the standard pre-dispatch window at 100 percent",
        "Assessed for 100 percent of flights before dispatch",
        "Incorporated before dispatch release at 100 percent",
        "Weather-related flight plan revision rate tracked against target"],
  risks=["A briefing package assembled early in planning already being stale by actual departure",
         "Convective weather developing along the route faster than the standard briefing refresh cycle",
         "A weather-driven route change cascading into a fuel and performance recalculation under time pressure",
         "Forecast confidence decreasing materially the further out the observation window extends"])

P("AC-FO-WX-02",
  desc="NOTAMs relevant to a flight's route and destinations are reviewed and screened for operational "
       "applicability, distinguishing genuinely relevant restrictions from routine administrative notices.",
  trig="Flight planning reaches NOTAM review ahead of dispatch release.",
  out="A screened set of operationally relevant NOTAMs incorporated into the flight plan and crew briefing.",
  note="NOTAM volume for a given route can be very high, and most of it is not operationally significant, "
       "which makes screening for genuine relevance the actual skill in this process rather than simply "
       "reading every notice.",
  phases=["NOTAM retrieval", "Applicability screening", "Incorporation into planning"],
  steps=[
    S("1.1","Retrieve NOTAMs for route and destinations","Flight Dispatcher","NAV CANADA",
      "Filed route and destination airports","Retrieved NOTAM set",
      "Retrieved for 100 percent of flights before briefing","N","N",
      "NOTAM volume for a busy international route can run into dozens of individual notices"),
    S("2.1","Screen for operational applicability","Flight Dispatcher","NAV CANADA",
      "Retrieved NOTAM set","Screened operationally relevant NOTAMs",
      "Screening completed within the planning window at 100 percent","Y","N",
      "A genuinely significant NOTAM can be missed within a high volume of routine administrative notices"),
    S("2.2","Assess runway and approach restriction impact","Flight Dispatcher","NetLine/Ops",
      "Screened NOTAMs affecting destination","Assessed operational impact",
      "Assessed for 100 percent of destination-affecting NOTAMs","N","N",
      "A runway or approach restriction can materially affect the performance and alternate planning already completed"),
    S("3.1","Incorporate into flight plan and crew briefing","Flight Dispatcher","Jeppesen FliteDeck Pro",
      "Assessed NOTAMs","Incorporated briefing content",
      "Incorporated before dispatch release at 100 percent","N","N",
      "A NOTAM that changes after incorporation requires an active update to the crew, not a passive republish"),
  ],
  kpis=["Retrieved for 100 percent of flights before briefing",
        "Screening completed within the planning window at 100 percent",
        "Assessed for 100 percent of destination-affecting NOTAMs",
        "Incorporated before dispatch release at 100 percent"],
  risks=["A genuinely significant NOTAM being missed within a high volume of routine administrative notices",
         "A runway or approach restriction materially affecting performance and alternate planning already completed",
         "A NOTAM changing after incorporation requiring an active crew update rather than a passive republish",
         "NOTAM volume for a busy international route straining the time available for genuine screening"])

P("AC-FO-WX-03",
  desc="Navigation database cycles are updated on the required 28-day AIRAC schedule, keeping route, "
       "airport and procedure data current across flight planning and the electronic flight bag.",
  trig="The AIRAC 28-day navigation database cycle comes due for update.",
  out="A current navigation database deployed across flight planning systems and the electronic flight bag "
      "fleet-wide before the new cycle takes effect.",
  note="Navigation database currency is a hard operational dependency: flying with an expired cycle is not "
      "permitted, which makes this recurring update a fixed, non-negotiable deadline every 28 days.",
  phases=["Database receipt and validation", "Deployment", "Currency confirmation"],
  steps=[
    S("1.1","Receive the new AIRAC cycle data","Navigation Data Coordinator","Jeppesen Charts",
      "Vendor-supplied navigation database","Received database update",
      "Received before the cycle effective date at 100 percent","N","N",
      "Vendor delivery timing leaves a fixed and sometimes tight window before the effective date"),
    S("1.2","Validate database integrity","Navigation Data Coordinator","NetLine/Ops",
      "Received database","Validated database",
      "Validated before deployment at 100 percent","Y","N",
      "A validation failure this close to the effective date leaves little time for vendor remediation"),
    S("2.1","Deploy to flight planning systems","Navigation Data Coordinator","NetLine/Ops",
      "Validated database","Deployed database in flight planning",
      "Deployed before the cycle effective date at 100 percent","N","N",
      "Deployment has to complete across every planning system before the old cycle expires"),
    S("2.2","Deploy to the electronic flight bag fleet-wide","Navigation Data Coordinator","Electronic Flight Bag",
      "Validated database","Deployed database across the EFB fleet",
      "Deployed to 100 percent of the fleet before the cycle effective date","N","N",
      "Fleet-wide EFB deployment depends on each aircraft's connectivity opportunity before the deadline"),
    S("3.1","Confirm currency across all systems","Navigation Data Coordinator","NetLine/Ops",
      "Deployment across all systems","Confirmed fleet-wide currency",
      "Confirmed before the new cycle takes effect at 100 percent","N","N",
      "An aircraft that missed the deployment window cannot legally operate on the expired cycle"),
  ],
  kpis=["Received before the cycle effective date at 100 percent",
        "Deployed to 100 percent of the fleet before the cycle effective date",
        "Confirmed before the new cycle takes effect at 100 percent",
        "Zero flights operated on an expired navigation database cycle"],
  risks=["An aircraft missing the deployment window and being unable to legally operate on the expired cycle",
         "A validation failure close to the effective date leaving little time for vendor remediation",
         "Fleet-wide EFB deployment depending on each aircraft's connectivity opportunity before the deadline",
         "Vendor delivery timing leaving a fixed and sometimes tight window before the effective date"])

P("AC-FO-WX-04",
  desc="A volcanic ash advisory or space weather event affecting the network is assessed and an operational "
       "response, including route avoidance or altitude restriction, is coordinated across affected flights.",
  trig="A volcanic ash advisory or significant space weather event is issued affecting Air Canada's network.",
  out="An operational response protecting affected flights, with route or altitude adjustments coordinated "
      "across every affected flight in the network.",
  note="These events are rare but high-consequence, and the response has to move faster than the standard "
       "planning cycle, which means a defined escalation path matters more here than in routine operations.",
  phases=["Event assessment", "Network-wide impact identification", "Coordinated response"],
  steps=[
    S("1.1","Assess the advisory or event","Flight Dispatcher","NAV CANADA",
      "Volcanic ash advisory or space weather alert","Assessed event severity and affected airspace",
      "Assessed within 30 minutes of advisory issuance at 100 percent","N","N",
      "Advisory information quality and update frequency varies by the issuing authority"),
    S("2.1","Identify affected flights across the network","Flight Dispatcher","NetLine/Ops",
      "Affected airspace and network schedule","Identified affected flight list",
      "Identified within 1 hour of assessment at 100 percent","N","N",
      "A widespread event can affect flights across multiple simultaneous phases of flight"),
    S("2.2","Determine route or altitude adjustment","Flight Dispatcher","NetLine/Ops",
      "Affected flight list and advisory boundary","Determined adjustment by flight",
      "Determined for 100 percent of affected flights before their departure or continued operation","Y","N",
      "A route adjustment for one flight can create a knock-on capacity constraint on an adjacent airway"),
    S("3.1","Coordinate response across dispatch and operations control","Flight Dispatcher","Jeppesen OCC",
      "Determined adjustments","Coordinated network-wide response",
      "Coordinated within the event's operational timeframe at 100 percent","N","N",
      "A fast-moving event requires coordination faster than the standard planning communication cadence"),
  ],
  kpis=["Assessed within 30 minutes of advisory issuance at 100 percent",
        "Identified within 1 hour of assessment at 100 percent",
        "Determined for 100 percent of affected flights before their departure or continued operation",
        "Zero flights operated in violation of an active volcanic ash or space weather restriction"],
  risks=["A widespread event affecting flights across multiple simultaneous phases of flight at once",
         "A route adjustment for one flight creating a knock-on capacity constraint on an adjacent airway",
         "Advisory information quality and update frequency varying by the issuing authority",
         "Response coordination needing to move faster than the standard planning communication cadence"])

P("AC-FO-WX-05",
  desc="Winter operations de-icing and anti-icing procedures are coordinated between flight dispatch, "
       "ground operations and the flight crew, managing holdover time against actual weather conditions.",
  trig="Winter precipitation conditions require de-icing or anti-icing treatment before departure.",
  out="Aircraft correctly de-iced or anti-iced within valid holdover time, departing with contamination-free "
      "critical surfaces.",
  note="Holdover time is a hard safety limit that starts counting down the moment treatment begins, which "
      "makes the coordination between ground crew, dispatch and the flight deck genuinely time-critical in a "
      "way few other winter operations decisions are.",
  phases=["Treatment decision", "Holdover time management", "Departure clearance"],
  steps=[
    S("1.1","Assess precipitation type and treatment need","Ground Operations Coordinator","NAV CANADA",
      "Current precipitation observation","Treatment type determination",
      "Determined before treatment begins at 100 percent","N","N",
      "Precipitation type can change during the treatment process itself"),
    S("1.2","Select fluid type and holdover time table","Ground Operations Coordinator","NAV CANADA",
      "Determined precipitation and temperature","Selected fluid and holdover time",
      "Selected against the current published holdover table at 100 percent","Y","N",
      "Holdover time tables are temperature and precipitation-rate specific and easy to misread under time pressure"),
    S("2.1","Apply treatment and record start time","Ground Operations Coordinator","TRAX",
      "Selected fluid","Applied treatment with recorded start time",
      "Start time recorded for 100 percent of treatments","N","N",
      "An inaccurate start time record undermines the entire holdover time calculation that follows"),
    S("2.2","Monitor holdover time against departure sequence","Ground Operations Coordinator","NetLine/Ops",
      "Treatment start time and departure queue","Holdover time status against departure",
      "Monitored continuously until off-block for 100 percent of treated aircraft","N","Y",
      "A departure delay after treatment can push the aircraft past its holdover window, requiring re-treatment"),
    S("3.1","Confirm contamination-free critical surfaces before departure","Flight Crew","Jeppesen FliteDeck Pro",
      "Holdover status at departure","Confirmed clean aircraft or re-treatment triggered",
      "Confirmed before takeoff clearance for 100 percent of winter departures","N","N",
      "The final visual and tactile check before takeoff is the last safety barrier against a treatment lapse"),
  ],
  kpis=["Determined against the current published holdover table at 100 percent",
        "Start time recorded for 100 percent of treatments",
        "Monitored continuously until off-block for 100 percent of treated aircraft",
        "Zero departures beyond a valid holdover time without re-treatment"],
  risks=["A departure delay after treatment pushing the aircraft past its holdover window without re-treatment",
         "An inaccurate treatment start time record undermining the entire holdover calculation",
         "Precipitation type changing during the treatment process itself",
         "Holdover time tables being misread under time pressure given their temperature and rate specificity"])

P("AC-FO-WX-06",
  desc="Runway condition reports and braking action assessments are incorporated into performance "
       "calculations for departure and arrival, adjusting for contaminated runway surfaces.",
  trig="A runway condition report is issued or updated for a departure or arrival airport with "
       "contamination present.",
  out="Departure and arrival performance calculations correctly adjusted for actual runway surface "
      "condition.",
  note="A performance calculation run against an outdated runway condition report can understate the actual "
      "stopping distance required, which makes report currency a direct safety input rather than an "
      "administrative detail.",
  phases=["Condition report retrieval", "Performance adjustment", "Crew communication"],
  steps=[
    S("1.1","Retrieve current runway condition report","Flight Dispatcher","NAV CANADA",
      "Departure or arrival airport","Retrieved current condition report",
      "Retrieved before performance calculation at 100 percent","N","N",
      "Runway condition reports can go stale quickly during active precipitation"),
    S("2.1","Adjust performance calculation for surface condition","Flight Dispatcher","Weight and Balance System",
      "Condition report and planned weight","Adjusted performance calculation",
      "Adjusted for 100 percent of flights with a reported contamination","Y","N",
      "Braking action assessments can vary between different parts of the same runway"),
    S("2.2","Assess weight or fuel adjustment requirement","Flight Dispatcher","NetLine/Ops",
      "Adjusted performance calculation","Determined weight or fuel adjustment if required",
      "Determined before dispatch release for 100 percent of affected flights","N","N",
      "A performance-limiting condition can require a weight reduction that displaces payload"),
    S("3.1","Communicate condition and adjustment to the crew","Flight Dispatcher","ACARS Datalink",
      "Determined adjustment","Delivered crew communication",
      "Delivered before departure or descent planning at 100 percent","N","N",
      "A condition report update after the crew briefing requires an active follow-up communication"),
  ],
  kpis=["Retrieved before performance calculation at 100 percent",
        "Adjusted for 100 percent of flights with a reported contamination",
        "Determined before dispatch release for 100 percent of affected flights",
        "Delivered before departure or descent planning at 100 percent"],
  risks=["A performance calculation run against an outdated runway condition report understating stopping distance",
         "Braking action assessments varying between different parts of the same runway",
         "A performance-limiting condition requiring a weight reduction that displaces revenue payload",
         "A condition report updating after the crew briefing without an active follow-up communication"])
