# -*- coding: utf-8 -*-
"""AC-GO-CI — Check-In, DCS and Boarding (6) and AC-GO-BA — Baggage (6)."""
from content_lib import P, S

# ── CI: Check-In, DCS and Boarding ──────────────────────────────────────────
P("AC-GO-CI-01",
  desc="A passenger is checked in and their bag accepted at the airport counter, verifying identity, "
       "documents and baggage compliance before issuing a boarding pass on Amadeus Altea DCS.",
  trig="A passenger presents at the airport check-in counter for their flight.",
  out="A checked-in passenger with a valid boarding pass and correctly tagged and accepted baggage.",
  note="Counter check-in remains the fallback for every passenger who cannot or does not complete self-"
       "service, which means the counter has to absorb both routine volume and every edge case the digital "
       "channel could not handle.",
  phases=["Identity and document verification", "Baggage acceptance", "Boarding pass issuance"],
  steps=[
    S("1.1","Verify passenger identity and travel documents","Airport Check-In Agent","Amadeus Altea DCS",
      "Passenger identification and booking","Verified identity and document compliance",
      "Verified for 100 percent of check-ins at 100 percent","N","N",
      "Document requirements vary by destination and are not always known in advance by the passenger"),
    S("2.1","Weigh and tag checked baggage","Airport Check-In Agent","Baggage Reconciliation System",
      "Presented baggage","Weighed, tagged and accepted baggage",
      "Accepted within the standard counter service time at 95 percent","N","N",
      "Baggage exceeding weight or dimension limits requires a fee calculation that can extend the transaction"),
    S("2.2","Apply excess or special baggage fees","Airport Check-In Agent","Amadeus Anytime Merchandising",
      "Baggage exceeding standard allowance","Applied correct fee",
      "Fee applied correctly against fare family entitlement at 100 percent","N","N",
      "Fee calculation has to correctly reflect Altitude tier and fare family inclusions"),
    S("3.1","Issue boarding pass","Airport Check-In Agent","Amadeus Altea DCS",
      "Verified check-in and accepted baggage","Issued boarding pass",
      "Issued within 3 minutes of transaction start at 90 percent","N","N",
      "A slow counter transaction compounds queue length during a peak departure bank"),
  ],
  kpis=["Verified for 100 percent of check-ins at 100 percent",
        "Accepted within the standard counter service time at 95 percent",
        "Fee applied correctly against fare family entitlement at 100 percent",
        "Issued within 3 minutes of transaction start at 90 percent"],
  risks=["A slow counter transaction compounding queue length during a peak departure bank",
         "Document requirements varying by destination without the passenger being aware in advance",
         "Fee calculation not correctly reflecting Altitude tier and fare family baggage entitlements",
         "The counter absorbing every self-service edge case, straining capacity beyond routine volume"])

P("AC-GO-CI-02",
  desc="A passenger completes check-in through a self-service kiosk, using the common-use CUPPS platform "
       "shared across airlines at the airport.",
  trig="A passenger approaches a self-service kiosk to check in.",
  out="A checked-in passenger with an issued boarding pass, or a clean handoff to a staffed counter where "
      "self-service cannot complete the transaction.",
  note="Kiosk check-in runs on shared common-use infrastructure that Air Canada does not fully control, "
      "which means kiosk availability and performance depend partly on the airport authority's own "
      "infrastructure management.",
  phases=["Kiosk session initiation", "Self-service check-in", "Completion or handoff"],
  steps=[
    S("1.1","Initiate kiosk session","Airport Check-In Agent","CUPPS",
      "Passenger booking reference or document scan","Initiated kiosk session",
      "Session initiated within 10 seconds at 95 percent","N","N",
      "Common-use kiosk performance depends partly on infrastructure Air Canada does not directly control"),
    S("2.1","Process self-service check-in","Airport Check-In Agent","Amadeus Altea DCS",
      "Initiated session","Completed check-in or identified exception",
      "Completed without agent assistance for 80 percent of eligible passengers","N","N",
      "International document verification at a kiosk is inherently less thorough than an agent review"),
    S("2.2","Print baggage tags for self-tagging","Airport Check-In Agent","CUPPS",
      "Completed check-in with checked baggage","Printed self-service baggage tags",
      "Tags printed within 15 seconds of check-in completion at 95 percent","N","N",
      "Self-service tagging accuracy depends on the passenger correctly applying the tag"),
    S("3.1","Route exceptions to a staffed counter","Airport Check-In Agent","Amadeus Altea DCS",
      "Exception at self-service","Routed passenger with preserved check-in progress",
      "Exceptions routed with context preserved for 100 percent of handoffs","N","Y",
      "A handoff that loses check-in progress forces the passenger to restart at the counter"),
  ],
  kpis=["Session initiated within 10 seconds at 95 percent",
        "Completed without agent assistance for 80 percent of eligible passengers",
        "Exceptions routed with context preserved for 100 percent of handoffs",
        "Kiosk availability across the network meeting target uptime"],
  risks=["Kiosk availability and performance depending partly on shared common-use infrastructure Air Canada does not control",
         "International document verification at a kiosk being inherently less thorough than an agent review",
         "A handoff to the counter losing check-in progress and forcing the passenger to restart",
         "Self-service baggage tagging accuracy depending on the passenger applying the tag correctly"])

P("AC-GO-CI-03",
  desc="Advance passenger information is transmitted to CBSA, CATSA and destination-country authorities "
       "ahead of departure, meeting the specific timing and data requirements of each regulator.",
  trig="A passenger completes check-in for a flight requiring advance passenger information transmission.",
  out="Complete, accurate advance passenger information transmitted within each regulator's required "
      "timeframe, clearing the passenger for travel.",
  note="Different regulators have different timing and data requirements for the same passenger, which "
      "means this process has to satisfy several independent, non-negotiable compliance regimes "
      "simultaneously rather than a single unified standard.",
  phases=["Data compilation", "Regulatory transmission", "Clearance confirmation"],
  steps=[
    S("1.1","Compile passenger information for transmission","Airport Check-In Agent","Amadeus Altea DCS",
      "Check-in data and passenger document","Compiled API and PNR data",
      "Compiled for 100 percent of applicable flights at check-in completion","N","N",
      "Data completeness depends on the accuracy of the document scan or manual entry at check-in"),
    S("2.1","Transmit to CBSA and US CBP Secure Flight","Airport Check-In Agent","CBSA API and PNR",
      "Compiled information","Transmitted regulatory data",
      "Transmitted within each regulator's required window at 100 percent","N","N",
      "Different destination regulators have different transmission timing requirements for the same flight"),
    S("2.2","Transmit to CATSA where applicable","Airport Check-In Agent","CBSA API and PNR",
      "Compiled information","Transmitted CATSA data",
      "Transmitted within the required window at 100 percent","N","N",
      "CATSA requirements are distinct from CBSA and US requirements despite overlapping data"),
    S("3.1","Confirm passenger clearance before boarding","Airport Check-In Agent","Amadeus Altea DCS",
      "Transmitted data","Confirmed clearance or flagged hold",
      "Confirmed before boarding for 100 percent of applicable passengers","Y","N",
      "A clearance hold received close to boarding time compresses the resolution window before departure"),
  ],
  kpis=["Compiled for 100 percent of applicable flights at check-in completion",
        "Transmitted within each regulator's required window at 100 percent",
        "Confirmed before boarding for 100 percent of applicable passengers",
        "Zero flights delayed due to a missed regulatory transmission deadline"],
  risks=["Different destination regulators having different transmission timing requirements for the same flight",
         "Data completeness depending on the accuracy of a document scan or manual entry at check-in",
         "A clearance hold received close to boarding time compressing the resolution window before departure",
         "CATSA and CBSA requirements being distinct despite substantially overlapping underlying data"])

P("AC-GO-CI-04",
  desc="Boarding is controlled and sequenced at the gate, verifying boarding passes and managing priority "
       "boarding groups against Altitude tier and fare class entitlements.",
  trig="The boarding process opens for a departing flight.",
  out="All passengers boarded in the correct sequence, verified against their boarding pass, with the "
      "flight ready for door closure on schedule.",
  note="Boarding sequence has direct commercial and status-recognition consequences, since priority boarding "
      "is one of the most visible Altitude tier and Star Alliance Gold benefits a member actually experiences "
      "on every single flight.",
  phases=["Boarding preparation", "Sequenced boarding", "Door closure readiness"],
  steps=[
    S("1.1","Prepare gate for boarding","Gate Agent","Amadeus Altea DCS",
      "Flight ready for boarding","Prepared gate with boarding sequence loaded",
      "Prepared before the scheduled boarding time at 100 percent","N","N",
      "A gate change close to boarding time compresses preparation time"),
    S("2.1","Board priority groups by tier and fare class","Gate Agent","Amadeus Altea DCS",
      "Loaded boarding sequence","Boarded priority groups",
      "Priority sequence correctly applied at 100 percent","Y","N",
      "Priority boarding recognition has to correctly reflect both Altitude tier and Star Alliance Gold status simultaneously"),
    S("2.2","Board general boarding groups","Gate Agent","Amadeus Altea DCS",
      "Completed priority boarding","Boarded general groups",
      "General boarding completed within the target window at 90 percent","N","N",
      "General boarding pace directly determines whether the flight can achieve an on-time departure"),
    S("3.1","Confirm boarding complete and close the door","Gate Agent","Amadeus Altea DCS",
      "Boarded passenger count","Confirmed complete boarding and door closure readiness",
      "Confirmed boarding count matches the manifest at 100 percent","N","N",
      "A count discrepancy at door closure requires resolution before the flight can depart"),
  ],
  kpis=["Priority sequence correctly applied at 100 percent",
        "General boarding completed within the target window at 90 percent",
        "Confirmed boarding count matches the manifest at 100 percent",
        "On-time door closure rate meeting target"],
  risks=["Priority boarding recognition failing to correctly reflect both Altitude tier and Star Alliance Gold status",
         "A gate change close to boarding time compressing preparation time and risking a late departure",
         "A boarding count discrepancy at door closure requiring resolution before the flight can depart",
         "General boarding pace being the direct determinant of whether the flight achieves on-time departure"])

P("AC-GO-CI-05",
  desc="A denied boarding or oversale situation is managed at the gate, following the volunteer solicitation "
       "and involuntary denial process required under the Air Passenger Protection Regulations.",
  trig="A flight is oversold and boarding reaches capacity with more confirmed passengers than available "
       "seats.",
  out="The oversale resolved through volunteers where possible, with any involuntary denial handled in full "
      "compliance with APPR requirements.",
  note="This is one of the most directly regulated moments in ground operations, since APPR sets a specific "
      "order of operations, solicit volunteers first, and specific compensation requirements for any "
      "involuntary denial that follows.",
  phases=["Oversale identification", "Volunteer solicitation", "Involuntary denial handling"],
  steps=[
    S("1.1","Identify the oversale at boarding","Gate Agent","Amadeus Altea DCS",
      "Confirmed passenger count against seat capacity","Identified oversale quantity",
      "Identified before boarding begins at 100 percent","N","N",
      "Late no-shows can sometimes resolve an apparent oversale before it requires action"),
    S("2.1","Solicit volunteers with compensation offer","Gate Agent","Amadeus Altea DCS",
      "Identified oversale","Volunteer response",
      "Volunteers solicited before any involuntary denial at 100 percent","Y","N",
      "APPR requires volunteer solicitation before involuntary denial can even be considered"),
    S("2.2","Rebook volunteering passengers","Gate Agent","Amadeus Passenger Recovery",
      "Accepted volunteers","Rebooked volunteer itineraries",
      "Rebooked with confirmed alternative travel at 100 percent","N","N",
      "Volunteer rebooking has to provide a genuinely viable alternative, not just a nominal one"),
    S("3.1","Handle involuntary denial per APPR requirements","Gate Agent","Amadeus Passenger Recovery",
      "Insufficient volunteers","APPR-compliant involuntary denial with compensation",
      "100 percent compliant with APPR compensation and process requirements","N","Y",
      "An involuntary denial handled outside the required process creates immediate regulatory exposure"),
  ],
  kpis=["Volunteers solicited before any involuntary denial at 100 percent",
        "Rebooked with confirmed alternative travel at 100 percent",
        "100 percent compliant with APPR compensation and process requirements",
        "Involuntary denial rate as a share of total oversales tracked and minimised"],
  risks=["An involuntary denial handled outside the required APPR process creating immediate regulatory exposure",
         "Volunteer rebooking failing to provide a genuinely viable alternative itinerary",
         "The volunteer solicitation step being skipped or rushed under gate time pressure",
         "Late no-show resolution not being properly accounted for before committing to a denial decision"])

P("AC-GO-CI-06",
  desc="Departure control operates in degraded or manual mode when Amadeus Altea DCS is unavailable, using "
       "documented fallback procedures to keep check-in and boarding functioning at reduced capacity.",
  trig="Amadeus Altea DCS becomes unavailable or materially degraded at one or more stations.",
  out="Continued check-in and boarding operation under manual fallback procedures until DCS service is "
      "restored.",
  note="The February 2023 DCS and intranet outage at Toronto is the direct reference point for this "
      "process: manual fallback capability is what stands between a system outage and a station-wide "
      "operational stop.",
  phases=["Outage detection and fallback activation", "Manual operation", "Restoration and reconciliation"],
  steps=[
    S("1.1","Detect DCS outage or degradation","Station Operations Duty Manager","Amadeus Altea DCS",
      "System monitoring alert","Detected outage or degradation",
      "Detected within 5 minutes of onset at 100 percent","N","N",
      "A partial degradation is harder to detect and characterise than a complete outage"),
    S("1.2","Activate manual check-in and boarding procedure","Station Operations Duty Manager","ITSM Platform",
      "Detected outage","Activated manual procedure",
      "Activated within 15 minutes of detection at 90 percent","N","N",
      "Manual procedure familiarity cannot be assumed given how rarely it is actually used"),
    S("2.1","Process check-in manually","Airport Check-In Agent","Amadeus Altea DCS",
      "Activated manual procedure","Manually checked-in passengers",
      "Manual throughput sustained at a defined minimum rate during the outage","N","N",
      "Manual throughput is materially lower than the automated system it temporarily replaces"),
    S("2.2","Process boarding manually with paper manifest","Gate Agent","Amadeus Altea DCS",
      "Manual check-in records","Manually boarded passengers with paper manifest",
      "Manifest reconciled against actual boarding for 100 percent of manual-mode flights","N","Y",
      "A paper manifest reconciliation gap creates uncertainty about who actually boarded"),
    S("3.1","Restore system operation and reconcile data","Station Operations Duty Manager","Amadeus Altea DCS",
      "Restored DCS and manual records","Reconciled operational data",
      "Reconciled within 24 hours of restoration at 100 percent","N","N",
      "Manual-mode data captured on paper has to be accurately re-entered into the restored system"),
  ],
  kpis=["Detected within 5 minutes of onset at 100 percent",
        "Activated within 15 minutes of detection at 90 percent",
        "Manifest reconciled against actual boarding for 100 percent of manual-mode flights",
        "Reconciled within 24 hours of restoration at 100 percent"],
  risks=["Manual procedure familiarity not being safely assumed given how rarely the fallback is actually used",
         "Manual throughput being materially lower than the automated system it temporarily replaces",
         "A paper manifest reconciliation gap creating genuine uncertainty about who actually boarded",
         "Manual-mode data not being accurately re-entered into the restored system after recovery"])

# ── BA: Baggage ──────────────────────────────────────────────────────────────
P("AC-GO-BA-01",
  desc="Checked baggage is accepted at check-in and physically tagged, with the tag data linked to the "
       "passenger's booking to enable tracking through every subsequent handling step.",
  trig="A passenger presents checked baggage at check-in.",
  out="Baggage correctly tagged, weighed and linked to the booking, ready for sortation and loading.",
  note="The tag applied here is the single physical link between a bag and its owner for the rest of the "
      "journey, so an error at this first step, a misapplied or duplicate tag, propagates through every "
      "downstream handling process.",
  phases=["Baggage presentation", "Weighing and tagging", "System linkage"],
  steps=[
    S("1.1","Receive presented baggage","Airport Check-In Agent","Baggage Reconciliation System",
      "Passenger-presented bag","Received bag for processing",
      "Received within the standard check-in transaction at 100 percent","N","N",
      "Bag condition at acceptance needs to be noted to avoid a later damage dispute"),
    S("2.1","Weigh baggage against allowance","Airport Check-In Agent","Amadeus Anytime Merchandising",
      "Presented bag","Weighed bag against fare and tier allowance",
      "Weighed for 100 percent of checked bags at 100 percent","N","N",
      "Allowance calculation has to correctly reference the specific fare family and Altitude tier"),
    S("2.2","Apply physical bag tag","Airport Check-In Agent","Baggage Reconciliation System",
      "Weighed bag","Tagged bag with unique tag number",
      "Tagged correctly for 100 percent of accepted bags at 100 percent","Y","N",
      "A duplicate or misread tag number breaks the tracking link for the rest of the journey"),
    S("3.1","Link tag to booking record","Airport Check-In Agent","Amadeus Altea DCS",
      "Applied tag","Tag linked to passenger booking",
      "Linked within seconds of tagging at 100 percent","N","N",
      "A linkage failure leaves a physically tagged bag invisible to the tracking system"),
  ],
  kpis=["Weighed for 100 percent of checked bags at 100 percent",
        "Tagged correctly for 100 percent of accepted bags at 100 percent",
        "Linked within seconds of tagging at 100 percent",
        "Tag-to-booking linkage error rate below target"],
  risks=["A duplicate or misread tag number breaking the tracking link for the entire remaining journey",
         "A linkage failure leaving a physically tagged bag invisible to the tracking system",
         "Bag condition at acceptance not being noted, complicating a later damage dispute",
         "Allowance calculation not correctly referencing the specific fare family and Altitude tier"])

P("AC-GO-BA-02",
  desc="Checked baggage is sorted and its handling reconciled against the flight manifest, confirming every "
       "bag loaded matches a boarded passenger under IATA Resolution 753.",
  trig="Baggage arrives at sortation ahead of a scheduled departure.",
  out="All checked baggage sorted, loaded and reconciled against the boarded passenger manifest, meeting "
      "Resolution 753 tracking obligations.",
  note="Resolution 753 requires bag-to-passenger matching at load, which is a direct control against the "
      "long-standing safety and security principle that a bag should not fly without its owner on the same "
      "aircraft.",
  phases=["Sortation", "Load reconciliation", "Manifest confirmation"],
  steps=[
    S("1.1","Sort baggage by flight and destination","Ramp Baggage Handler","Baggage Reconciliation System",
      "Tagged baggage stream","Sorted baggage by flight",
      "Sorted correctly for 99 percent of bags at 100 percent","N","N",
      "Sortation errors at a high-volume hub compound during a peak bank of simultaneous departures"),
    S("2.1","Scan baggage at load point","Ramp Baggage Handler","Baggage Reconciliation System",
      "Sorted baggage","Scanned load event",
      "Scanned for 100 percent of loaded bags at load point","N","N",
      "A missed scan at load is the single most common gap in Resolution 753 compliance"),
    S("2.2","Reconcile loaded bags against boarded passengers","Ramp Baggage Handler","Amadeus Altea DCS",
      "Scanned load events and boarding manifest","Reconciled bag-to-passenger match",
      "Reconciled before door closure for 100 percent of flights at 100 percent","Y","N",
      "An unresolved reconciliation gap at door closure requires immediate offload of the unmatched bag"),
    S("3.1","Offload unmatched baggage","Ramp Baggage Handler","Baggage Reconciliation System",
      "Unmatched bag","Offloaded bag with documented reason",
      "Offloaded before departure for 100 percent of unmatched bags at 100 percent","N","Y",
      "Offload at the last minute before departure creates real time pressure on the ramp team"),
  ],
  kpis=["Scanned for 100 percent of loaded bags at load point",
        "Reconciled before door closure for 100 percent of flights at 100 percent",
        "Offloaded before departure for 100 percent of unmatched bags at 100 percent",
        "Sortation accuracy rate meeting target"],
  risks=["A missed scan at load being the single most common gap in Resolution 753 compliance",
         "An unresolved reconciliation gap at door closure requiring immediate, time-pressured offload",
         "Sortation errors at a high-volume hub compounding during a peak bank of simultaneous departures",
         "Offload at the last minute before departure creating genuine time pressure on the ramp team"])

P("AC-GO-BA-03",
  desc="Transfer baggage connecting between flights at Toronto is handled and rerouted within the connect "
      "time window, distinct from originating baggage handling at the departure point.",
  trig="A passenger's checked baggage requires transfer between connecting flights at Toronto.",
  out="Transfer baggage correctly rerouted and loaded onto the connecting flight within the available "
      "connect time.",
  note="Transfer baggage handling is where the minimum connect time standards established in the network "
      "planning process in AC-NP-SP-03 actually get tested against physical reality: whether a bag can move "
      "between two aircraft in the time the schedule assumed it could.",
  phases=["Transfer identification", "Physical rerouting", "Connecting flight load"],
  steps=[
    S("1.1","Identify transfer baggage on arrival","Ramp Baggage Handler","Baggage Reconciliation System",
      "Arriving flight's baggage","Identified transfer bags with connecting flight",
      "Identified within 10 minutes of arrival at 95 percent","N","N",
      "Identification speed directly consumes the available connect time window"),
    S("2.1","Reroute transfer baggage to the connecting flight","Ramp Baggage Handler","Baggage Reconciliation System",
      "Identified transfer bags","Rerouted baggage",
      "Rerouted within the available connect time for 90 percent of transfers","N","N",
      "A short connect time leaves very little margin for any handling delay"),
    S("2.2","Screen for infeasible connections","Ramp Baggage Handler","Baggage Reconciliation System",
      "Rerouted bags and connect time remaining","Flagged infeasible transfer",
      "Infeasible transfers flagged before the connecting flight closes at 90 percent","Y","N",
      "A bag flagged too late has already missed its connecting flight regardless of the flag"),
    S("3.1","Load transfer baggage onto the connecting flight","Ramp Baggage Handler","Baggage Reconciliation System",
      "Rerouted bags within connect time","Loaded transfer baggage",
      "Loaded before the connecting flight's door closure at 90 percent","N","N",
      "A late-arriving transfer bag competes with the connecting flight's own on-time departure pressure"),
  ],
  kpis=["Rerouted within the available connect time for 90 percent of transfers",
        "Loaded before the connecting flight's door closure at 90 percent",
        "Infeasible transfers flagged before the connecting flight closes at 90 percent",
        "Transfer baggage misconnect rate below target"],
  risks=["A short connect time leaving very little margin for any handling delay along the way",
         "A late-flagged infeasible transfer having already missed its connecting flight regardless of the flag",
         "A late-arriving transfer bag competing with the connecting flight's own on-time departure pressure",
         "Identification speed on arrival directly consuming the connect time window available for the transfer"])

P("AC-GO-BA-04",
  desc="A mishandled bag is traced using SITA WorldTracer, from initial passenger report through location "
       "and return, coordinating across the network of stations a bag may have moved through.",
  trig="A passenger reports a bag that did not arrive with them, or a station identifies an unclaimed bag "
      "without a matched owner.",
  out="The mishandled bag located and returned to its owner, with the PIR file closed on completion.",
  note="Mishandled bag tracing depends on a global network of stations correctly using WorldTracer, so a "
      "bag's actual location is only as knowable as the weakest station in the chain it passed through.",
  phases=["PIR creation", "Location tracing", "Delivery and closure"],
  steps=[
    S("1.1","Create the property irregularity report","Baggage Services Agent","SITA WorldTracer",
      "Passenger report and bag details","Created PIR file",
      "Created within the standard reporting window at 100 percent","N","N",
      "PIR quality depends on the completeness of the passenger's description and the original tag data"),
    S("2.1","Trace bag location across the network","Baggage Services Agent","SITA WorldTracer",
      "PIR and tag data","Located bag or ongoing trace",
      "Located within 24 hours for 70 percent of mishandled bags","N","N",
      "Tracing depends on every station in the bag's possible route correctly scanning and reporting"),
    S("2.2","Coordinate return routing","Baggage Services Agent","SITA WorldTracer",
      "Located bag","Return routing arranged",
      "Return routing arranged within 4 hours of location at 90 percent","N","N",
      "Return routing has to reach the passenger's actual current location, which may differ from their original destination"),
    S("3.1","Deliver bag and close the PIR","Baggage Services Agent","SITA WorldTracer",
      "Returned bag","Closed PIR file",
      "Closed within 5 business days of location for 85 percent of cases","N","N",
      "A PIR closed prematurely before actual delivery confirmation understates true return time performance"),
  ],
  kpis=["Located within 24 hours for 70 percent of mishandled bags",
        "Return routing arranged within 4 hours of location at 90 percent",
        "Closed within 5 business days of location for 85 percent of cases",
        "Mishandled bags per 1,000 passengers tracked against industry benchmark"],
  risks=["Tracing depending on every station in the bag's possible route correctly scanning and reporting",
         "A PIR closed prematurely before actual delivery confirmation understating true return time performance",
         "Return routing needing to reach the passenger's actual current location rather than their original destination",
         "PIR quality depending on the completeness of the passenger's description and the original tag data"])

P("AC-GO-BA-05",
  desc="A traced or delivered bag is repatriated to the passenger, coordinating final delivery logistics "
       "when the passenger has already left the airport.",
  trig="A mishandled bag is located and the passenger has already departed the airport.",
  out="The bag delivered to the passenger's actual location, whether a hotel, residence or onward "
      "destination, with delivery confirmed.",
  note="Repatriation logistics have to reach wherever the passenger actually is, which is frequently not "
      "the airport and not always even the city the passenger was originally travelling to.",
  phases=["Delivery location confirmation", "Courier coordination", "Delivery confirmation"],
  steps=[
    S("1.1","Confirm passenger's current delivery location","Baggage Services Agent","SITA WorldTracer",
      "Located bag and passenger contact","Confirmed delivery address",
      "Confirmed within 4 hours of bag location at 95 percent","N","N",
      "A passenger continuing onward travel may have a delivery location that changes again before the bag arrives"),
    S("2.1","Arrange courier delivery","Baggage Services Agent","SITA WorldTracer",
      "Confirmed delivery address","Arranged courier delivery",
      "Arranged within 24 hours of location for 90 percent of cases","N","N",
      "Courier availability and delivery timeframes vary significantly by geography"),
    S("2.2","Track delivery progress","Baggage Services Agent","SITA WorldTracer",
      "Arranged delivery","Tracked delivery status",
      "Tracked continuously until confirmed delivery at 100 percent","N","N",
      "A delivery that fails at the first attempt requires prompt rescheduling to avoid extending the delay further"),
    S("3.1","Confirm delivery and close repatriation","Baggage Services Agent","SITA WorldTracer",
      "Delivery confirmation","Closed repatriation record",
      "Closed within 24 hours of confirmed delivery at 100 percent","N","N",
      "A repatriation not properly closed leaves ambiguity about whether the bag actually reached the passenger"),
  ],
  kpis=["Confirmed within 4 hours of bag location at 95 percent",
        "Arranged within 24 hours of location for 90 percent of cases",
        "Tracked continuously until confirmed delivery at 100 percent",
        "Average time from bag location to confirmed delivery meeting target"],
  risks=["A passenger continuing onward travel changing their delivery location again before the bag arrives",
         "Courier availability and delivery timeframes varying significantly by geography",
         "A failed first delivery attempt requiring prompt rescheduling to avoid extending the delay further",
         "A repatriation not properly closed leaving ambiguity about whether the bag actually reached the passenger"])

P("AC-GO-BA-06",
  desc="Baggage handling performance is measured and reported against IATA Resolution 753 obligations and "
       "internal targets, feeding both regulatory reporting and operational improvement.",
  trig="The recurring baggage performance reporting cycle runs.",
  out="A consolidated baggage handling performance report against mishandling rate, tracking compliance and "
      "delivery time targets, with findings routed for operational action.",
  note="Resolution 753 reporting sits alongside internal performance management as a genuinely dual-purpose "
      "process, one output for the regulator and industry benchmarking, and a separate practical output for "
      "operational improvement at the station level.",
  phases=["Data compilation", "Performance analysis", "Reporting and action routing"],
  steps=[
    S("1.1","Compile mishandling and delivery time data","Baggage Performance Analyst","SITA WorldTracer",
      "PIR and delivery records across the period","Compiled performance data",
      "Compiled within 5 business days of period close at 100 percent","N","N",
      "Data spans multiple systems, WorldTracer and the reconciliation system, that need consistent joining"),
    S("2.1","Analyse performance by station and route","Baggage Performance Analyst","SITA WorldTracer",
      "Compiled data","Performance analysis by station and route",
      "Analysed for 100 percent of material stations each cycle","N","N",
      "A network-wide average can mask a specific station's persistent underperformance"),
    S("2.2","Compare against Resolution 753 tracking obligations","Baggage Performance Analyst","Baggage Reconciliation System",
      "Performance data","Resolution 753 compliance assessment",
      "Assessed for 100 percent of tracking touchpoints each cycle","Y","N",
      "Tracking touchpoint compliance is distinct from mishandling rate and needs its own separate assessment"),
    S("3.1","Route findings for operational action","Baggage Performance Analyst","ITSM Platform",
      "Analysis and compliance assessment","Routed findings with an owner",
      "Routed within 10 business days of period close at 100 percent","N","N",
      "Findings without a clear operational owner risk being reported repeatedly without ever being acted on"),
  ],
  kpis=["Compiled within 5 business days of period close at 100 percent",
        "Assessed for 100 percent of tracking touchpoints each cycle",
        "Routed within 10 business days of period close at 100 percent",
        "Mishandled bags per 1,000 passengers trending against target"],
  risks=["A network-wide average masking a specific station's persistent underperformance",
         "Findings without a clear operational owner being reported repeatedly without ever being acted on",
         "Data spanning multiple systems that need consistent joining before analysis can be trusted",
         "Resolution 753 tracking touchpoint compliance needing separate assessment from the mishandling rate"])
