# -*- coding: utf-8 -*-
"""AC-NP-FA — Network Planning and Scheduling > Fleet Assignment and Rotation (8 processes)."""
from content_lib import P, S

P("AC-NP-FA-01",
  desc="Fleet assignment matches aircraft gauge to route demand across the mainline fleet types, "
       "reconciling revenue optimisation against fleet availability during a multi-year renewal programme.",
  trig="Seasonal schedule build reaches fleet assignment, or a fleet delivery or retirement changes the "
       "available type mix mid-cycle.",
  out="A leg-by-leg fleet assignment that maximises contribution within the available fleet, feasible for "
      "rotation building.",
  note="Air Canada is mid-renewal across 777, 787, 737 MAX, A220, A319, A320 and A321, so the assignable "
       "fleet itself moves between seasons. Assignment has to optimise against a target that is not fixed.",
  phases=["Demand and fleet input", "Assignment optimisation", "Feasibility and commitment"],
  steps=[
    S("1.1","Compile route demand by cabin","Fleet Planner","PROS Revenue Management",
      "Seasonal demand forecast","Demand by route and cabin class",
      "Demand compiled before assignment cycle opens","N","N",
      "Demand forecasts for new routes carry no comparable-market anchor"),
    S("1.2","Confirm fleet delivery and retirement schedule","Fleet Planner","NetLine/Plan",
      "Fleet delivery contracts and retirement plan","Available fleet count by type and week",
      "Fleet count confirmed for the full assignment horizon","N","N",
      "Delivery slippage is common and not always reflected in the planning system in time"),
    S("2.1","Run gauge optimisation by route","Fleet Planner","NetLine/Plan",
      "Demand and available fleet","Optimised gauge assignment",
      "Optimisation run completed within the assignment window at 100 percent","N","N",
      "Optimiser output favours revenue and ignores rotation and maintenance feasibility"),
    S("2.2","Evaluate narrowbody widebody swap options","Fleet Planner","PROS Revenue Management",
      "Marginal routes near the gauge boundary","Swap recommendation with revenue delta",
      "Swap evaluated for all borderline routes","Y","N",
      "Swap value depends on connecting traffic that the point to point model does not see"),
    S("2.3","Assess A220 fit on thin transcontinental routes","Fleet Planner","NetLine/Plan",
      "Thin route demand profile","A220 deployment recommendation",
      "A220 fit assessed for all eligible transcontinental routes","N","N",
      "A220 range and payload trade-offs are route specific and not captured by a single rule"),
    S("2.4","Allocate Express operator capacity","Fleet Planner","Lufthansa Systems NetLine",
      "Capacity purchase agreement limits","Express capacity allocation",
      "Express allocation within contracted limits at 100 percent","N","N",
      "Express capacity is contractually fixed and cannot absorb overflow from mainline swaps"),
    S("3.1","Test rotation feasibility of the assignment","Schedule Planner","NetLine/Plan",
      "Draft gauge assignment","Feasibility exceptions by tail",
      "Assignment feasible for rotation building above 80 percent","Y","N",
      "Infeasible assignments are only discovered once rotation building starts"),
    S("3.2","Resolve assignment conflicts","Fleet Planner","NetLine/Plan",
      "Feasibility exception list","Resolved assignment",
      "Conflicts resolved before schedule freeze at 100 percent","N","Y",
      "Resolution usually means giving up the highest-revenue gauge choice"),
    S("3.3","Commit fleet assignment to the schedule","Fleet Planner","NetLine/Plan",
      "Resolved assignment","Committed fleet assignment",
      "Assignment committed on the published cycle date","N","N",
      "Late fleet delivery changes force reopening a committed assignment"),
  ],
  kpis=["Optimisation run completed within the assignment window at 100 percent",
        "Assignment feasible for rotation building above 80 percent",
        "A220 fit assessed for all eligible transcontinental routes",
        "Express capacity allocated within contracted limits at 100 percent",
        "Assignment conflicts resolved before schedule freeze at 100 percent"],
  risks=["Optimiser output favouring revenue while ignoring rotation and maintenance feasibility",
         "Fleet delivery slippage invalidating an assignment already committed",
         "Narrowbody-widebody swap decisions missing connecting traffic value visible only at the network level",
         "Express capacity unable to absorb overflow when a mainline swap is forced late"],
  extra_systems=["Amadeus Altea Inventory"])

P("AC-NP-FA-02",
  desc="Individual tail rotations are built from the fleet assignment, sequencing each aircraft through its "
       "flying pattern so the rotation closes at a maintenance base with feasible ground time.",
  trig="Fleet assignment is committed for the season, or an in-season fleet or route change requires "
       "rotation rebuild.",
  out="A feasible rotation for every tail, closing at an appropriate maintenance base within the required "
      "check interval.",
  note="A rotation is where gauge assignment becomes a physical, closeable sequence. A rotation that never "
       "returns a tail to a maintenance base within its check interval is not a schedule, it is a liability.",
  phases=["Rotation construction", "Maintenance and turn validation", "Commitment"],
  steps=[
    S("1.1","Sequence legs into candidate rotations","Schedule Planner","NetLine/Plan",
      "Committed fleet assignment","Candidate tail rotations",
      "Candidate rotations generated for 100 percent of assigned legs","N","N",
      "Sequencing optimises block time and can ignore where the tail needs to end up"),
    S("1.2","Validate minimum ground time by station","Schedule Planner","Airport Resource Management",
      "Candidate rotations and station turn standards","Ground time validated rotations",
      "Turn times meet station minimums at 100 percent","Y","N",
      "Minimum turn time varies by station and aircraft type and is not uniformly applied"),
    S("2.1","Check maintenance check interval compliance","Technical Services Planner","TRAX",
      "Rotation length and check due dates","Compliance flag by tail",
      "Zero rotations exceeding a check interval at commitment","Y","N",
      "Check due dates shift as flying accumulates differently than planned"),
    S("2.2","Confirm rotation closes at a maintenance base","Technical Services Planner","TRAX",
      "Candidate rotation end points","Base-closing confirmation or exception",
      "Rotations close at a maintenance base at 100 percent","Y","N",
      "A rotation can be commercially efficient and never return the tail to base"),
    S("2.3","Validate crew base compatibility","Crew Planning Liaison","Jeppesen Crew",
      "Rotation pattern","Crew base feasibility flag",
      "Rotation compatible with crew basing above 90 percent","N","N",
      "Rotation and crew base optimisation are performed in separate systems"),
    S("3.1","Resolve infeasible rotations","Schedule Planner","NetLine/Plan",
      "Exception list","Resolved rotation or accepted exception",
      "Infeasible rotations resolved before freeze at 100 percent","N","Y",
      "Resolution often trades block time efficiency for maintenance access"),
    S("3.2","Commit rotations to the schedule","Schedule Planner","NetLine/Plan",
      "Resolved rotations","Committed tail rotations",
      "Rotations committed on the published cycle date","N","N",
      "Late in-season fleet swaps require re-validating the whole rotation set"),
  ],
  kpis=["Rotations closing at a maintenance base at 100 percent",
        "Zero rotations exceeding a check interval at commitment",
        "Turn times meeting station minimums at 100 percent",
        "Rotation compatible with crew basing above 90 percent",
        "Infeasible rotations resolved before freeze at 100 percent"],
  risks=["A rotation that never returns its tail to a maintenance base within the check interval",
         "Ground time built to the station minimum with no buffer for routine delay",
         "Rotation and crew base optimisation happening in separate systems, producing conflicting outcomes",
         "In-season fleet swaps invalidating rotations without full re-validation"],
  extra_systems=["Lufthansa Systems NetLine"])

P("AC-NP-FA-03",
  desc="Scheduled and unscheduled maintenance opportunity is embedded into aircraft rotations so that check "
       "intervals are met without an unplanned removal from service.",
  trig="Rotation building reaches maintenance embedding, or a check comes due earlier than planned because "
       "of higher than forecast utilisation.",
  out="Rotations with protected ground time at a maintenance base sufficient for the check due in that "
      "period, without unplanned schedule disruption.",
  note="Maintenance ground time is the first thing traded away when a schedule is tight, because giving it "
       "up produces no visible short-term cost. The cost appears later as an unplanned removal.",
  phases=["Check forecast", "Ground time embedding", "Validation and buffer"],
  steps=[
    S("1.1","Forecast check due dates by tail","Technical Services Planner","TRAX",
      "Utilisation history and check intervals","Forecast check due date by tail",
      "Check due dates forecast for the full rotation horizon","N","N",
      "Utilisation running ahead of plan pulls check dates forward unpredictably"),
    S("1.2","Identify required ground time by check type","Technical Services Planner","TRAX",
      "Check type and scope","Required ground time by tail",
      "Ground time requirement documented for 100 percent of forecast checks","N","N",
      "Required ground time is a estimate until the actual work scope is known"),
    S("2.1","Embed ground time into the rotation","Schedule Planner","NetLine/Plan",
      "Rotation draft and ground time requirement","Rotation with embedded maintenance slot",
      "Ground time embedded for 100 percent of forecast checks","Y","N",
      "Embedding a long check slot can force an otherwise efficient rotation to be rebuilt"),
    S("2.2","Confirm maintenance base capacity for the period","Technical Services Planner","TRAX",
      "Embedded maintenance slots across the fleet","Base capacity confirmation or conflict",
      "Base capacity sufficient for all embedded slots at 100 percent","Y","N",
      "Multiple tails can converge on the same base in the same window"),
    S("3.1","Validate against unplanned removal risk","Technical Services Planner","TRAX",
      "Embedded rotation and reliability data","Risk-validated rotation",
      "Unplanned removal risk assessed for 100 percent of near-due tails","N","N",
      "Reliability trend data arrives after the rotation is already committed"),
    S("3.2","Commit maintenance-protected rotation","Technical Services Planner","NetLine/Plan",
      "Validated rotation","Committed rotation with protected maintenance ground time",
      "Zero checks missed due to unavailable ground time","N","Y",
      "A missed check forces an unplanned aircraft removal mid-season"),
  ],
  kpis=["Zero checks missed due to unavailable ground time",
        "Ground time embedded for 100 percent of forecast checks",
        "Base capacity sufficient for all embedded slots at 100 percent",
        "Unplanned removal risk assessed for 100 percent of near-due tails"],
  risks=["Maintenance ground time traded away under schedule pressure, producing an unplanned removal later",
         "Multiple tails converging on the same base capacity in the same window",
         "Utilisation running ahead of plan and pulling a check date forward unpredictably",
         "Embedding a long check slot forcing rebuild of an otherwise efficient rotation"],
  extra_systems=["TRAX eMobility"])

P("AC-NP-FA-04",
  desc="Marginal routes near the gauge boundary are evaluated for a narrowbody to widebody swap or the "
       "reverse, balancing unit cost, connecting traffic value and fleet availability.",
  trig="A route's demand profile shifts toward a gauge boundary, or fleet availability changes make a swap "
       "newly feasible or newly infeasible.",
  out="A swap decision with quantified revenue and cost impact, including the connecting traffic effect "
      "that a point to point view misses.",
  note="Swap value is systematically underestimated when connecting traffic is ignored, because the direct "
       "route's own economics can look marginal while its contribution to the hub bank is not.",
  phases=["Candidate identification", "Impact quantification", "Decision"],
  steps=[
    S("1.1","Identify routes near the gauge boundary","Fleet Planner","PROS Revenue Management",
      "Load factor and spill data by route","Candidate swap route list",
      "Candidate list refreshed each planning cycle","N","N",
      "Boundary routes shift between seasons and the candidate list goes stale quickly"),
    S("1.2","Quantify direct route economics for each gauge","Revenue Management Analyst","PROS Revenue Management",
      "Demand and cost by gauge option","Direct economics comparison",
      "Direct comparison completed for 100 percent of candidates","N","N",
      "Direct economics alone understate the case for keeping a connecting-heavy route on larger gauge"),
    S("1.3","Quantify connecting traffic contribution","Network Planning Analyst","NetLine/Plan",
      "Connecting itineraries through the route","Connecting contribution by gauge option",
      "Connecting contribution quantified for 100 percent of hub-touching candidates","N","N",
      "Connecting value is the input most often left out of a gauge decision"),
    S("2.1","Assess fleet availability for the swap","Fleet Planner","NetLine/Plan",
      "Candidate swap and fleet plan","Feasibility of the swap within available fleet",
      "Feasibility confirmed before the decision is taken","Y","N",
      "A swap that is economically right can be infeasible simply for lack of an available tail"),
    S("2.2","Model rotation and crew impact of the swap","Schedule Planner","Jeppesen Crew",
      "Candidate swap","Rotation and crew feasibility assessment",
      "Feasibility assessed for 100 percent of candidates before decision","N","N",
      "A swap decided on route economics can break a rotation or crew base elsewhere in the network"),
    S("3.1","Decide and commit the swap","Fleet Planner","NetLine/Plan",
      "Full impact assessment","Committed swap decision",
      "Decisions taken within the planning cycle at 100 percent","Y","N",
      "A deferred swap decision leaves the route on suboptimal gauge for another season"),
  ],
  kpis=["Connecting contribution quantified for 100 percent of hub-touching candidates",
        "Feasibility confirmed before the swap decision is taken",
        "Rotation and crew feasibility assessed for 100 percent of candidates",
        "Swap decisions taken within the planning cycle at 100 percent"],
  risks=["Direct route economics alone systematically undervaluing a connecting-heavy route",
         "A swap decided on route economics breaking a rotation or crew base elsewhere in the network",
         "Fleet unavailability blocking an economically justified swap",
         "Deferred decisions leaving a route on suboptimal gauge for a full season"])

P("AC-NP-FA-05",
  desc="The A220 is deployed on thin transcontinental routes where its range, payload and unit cost profile "
       "outperform larger narrowbody gauge, using a route-specific rather than a blanket rule.",
  trig="Seasonal fleet assignment identifies a thin transcontinental route as an A220 candidate, or A220 "
       "fleet availability changes.",
  out="A validated A220 deployment decision on routes where its economics genuinely fit, with range and "
      "payload confirmed for the specific sector.",
  note="A220 economics are route specific: range and payload trade-offs at maximum sector length differ "
       "from a mid-length transcontinental sector, so a single deployment rule misallocates the fleet.",
  phases=["Route candidacy", "Range and payload validation", "Deployment decision"],
  steps=[
    S("1.1","Screen thin transcontinental routes","Fleet Planner","PROS Revenue Management",
      "Route demand and load factor history","Screened candidate list",
      "Screening completed each planning cycle","N","N",
      "Thin route demand is volatile and a single season's data can mislead"),
    S("1.2","Validate range at planned payload","Fleet Planner","NetLine/Plan",
      "Sector distance and typical payload","Range and payload validation",
      "Range validated for 100 percent of candidate sectors","Y","N",
      "Winter headwind routings can reduce effective range below the summer assumption"),
    S("2.1","Compare unit cost against incumbent gauge","Revenue Management Analyst","PROS Revenue Management",
      "A220 and incumbent gauge cost per seat mile","Unit cost comparison",
      "Comparison completed for 100 percent of validated candidates","N","N",
      "Unit cost comparison at typical load factor can mask a poor result in the shoulder season"),
    S("2.2","Assess fleet availability against other A220 demands","Fleet Planner","NetLine/Plan",
      "A220 fleet size and competing deployment candidates","Availability assessment",
      "Availability confirmed before commitment at 100 percent","Y","N",
      "A220 deployment candidates compete against each other for a limited fleet"),
    S("3.1","Decide and commit A220 deployment","Fleet Planner","NetLine/Plan",
      "Validated candidate with confirmed economics","Committed A220 assignment",
      "Deployment decisions taken within the planning cycle at 100 percent","N","N",
      "A committed A220 assignment is hard to reverse mid-season without disrupting the route"),
    S("3.2","Monitor in-service performance against the case","Fleet Planner","Databricks Lakehouse",
      "In-service load factor and cost data","Performance review against the deployment case",
      "Performance reviewed within 60 days of season end","N","N",
      "Underperformance is rarely traced back to correct or reverse the original deployment call"),
  ],
  kpis=["Range validated for 100 percent of candidate sectors",
        "Unit cost comparison completed for 100 percent of validated candidates",
        "Availability confirmed before commitment at 100 percent",
        "Deployment decisions taken within the planning cycle at 100 percent"],
  risks=["Winter headwind routings reducing effective range below the summer planning assumption",
         "A single deployment rule misallocating a fleet whose economics are genuinely route specific",
         "A220 candidates competing against each other for a fleet too small to serve them all",
         "Unit cost comparison at typical load factor masking a poor shoulder-season result"])

P("AC-NP-FA-06",
  desc="Express operator capacity purchased from Jazz Aviation and PAL Airlines is allocated across regional "
       "routes within the contracted capacity purchase agreement limits.",
  trig="Seasonal schedule build reaches Express allocation, or a change in regional demand requires "
       "reallocation within the contract.",
  out="Regional route capacity allocated to Express operators within contracted limits, feeding correctly "
      "into the mainline connecting banks.",
  note="Express capacity is contractually fixed, not commercially flexible: it cannot absorb overflow from "
       "a mainline decision made elsewhere in the schedule, which makes allocation a hard constraint rather "
       "than an optimisation input.",
  phases=["Demand and contract review", "Allocation", "Bank alignment"],
  steps=[
    S("1.1","Review regional route demand","Network Planning Analyst","Databricks Lakehouse",
      "Regional O and D demand data","Regional demand by route",
      "Demand reviewed at the start of the allocation cycle","N","N",
      "Regional demand data is thinner than mainline and harder to forecast confidently"),
    S("1.2","Confirm capacity purchase agreement limits","Fleet Planner","Lufthansa Systems NetLine",
      "Jazz and PAL contracted capacity","Confirmed contract limits by operator",
      "Limits confirmed before allocation begins at 100 percent","N","N",
      "Contract limits and actual operator fleet availability are not always the same number"),
    S("2.1","Allocate routes within contracted limits","Fleet Planner","Lufthansa Systems NetLine",
      "Regional demand and contract limits","Route allocation by operator",
      "Allocation within contracted limits at 100 percent","Y","N",
      "Demand can exceed contracted capacity on a specific route with no immediate remedy"),
    S("2.2","Assign aircraft type within operator fleet","Fleet Planner","Lufthansa Systems NetLine",
      "Operator fleet types and route requirements","Aircraft type assignment by route",
      "Type assignment matched to route requirements at 100 percent","N","N",
      "Operator fleet type mix is set by the operator, not chosen route by route"),
    S("3.1","Align Express timings to mainline connecting banks","Network Planning Analyst","NetLine/Plan",
      "Express schedule draft and bank windows","Bank-aligned Express schedule",
      "Express feed aligned to bank windows on 85 percent of connections","N","N",
      "Operator scheduling constraints can conflict with the mainline bank window"),
    S("3.2","Commit Express allocation to the schedule","Fleet Planner","Lufthansa Systems NetLine",
      "Aligned allocation","Committed Express capacity allocation",
      "Allocation committed on the published cycle date","N","N",
      "Late demand shifts cannot be absorbed once the contracted allocation is committed"),
  ],
  kpis=["Allocation within contracted capacity purchase agreement limits at 100 percent",
        "Express feed aligned to mainline bank windows on 85 percent of connections",
        "Type assignment matched to route requirements at 100 percent",
        "Limits confirmed before allocation begins at 100 percent"],
  risks=["Regional demand exceeding contracted capacity with no immediate remedy available",
         "Operator scheduling constraints conflicting with the mainline connecting bank window",
         "Contract limits and actual operator fleet availability diverging without notice",
         "Late regional demand shifts unable to be absorbed once allocation is committed"],
  extra_systems=["Jazz and PAL Operator Interface"])

P("AC-NP-FA-07",
  desc="Air Canada's multi-year fleet renewal programme, spanning 777, 787, 737 MAX, A220 and A320 family "
       "deliveries and retirements, is translated into its schedule and network planning impact each season.",
  trig="A fleet delivery or retirement date is confirmed or changes, or the annual renewal programme review "
       "updates the multi-year plan.",
  out="A network and schedule impact model reflecting the current renewal programme, feeding fleet "
      "assignment with an accurate available-fleet position.",
  note="Renewal timing slippage is common in any fleet transition and the practical discipline is keeping "
       "the assignable fleet position current rather than assuming the delivery plan will hold.",
  phases=["Programme tracking", "Impact modelling", "Plan update"],
  steps=[
    S("1.1","Track delivery and retirement schedule","Fleet Planner","NetLine/Plan",
      "Manufacturer delivery position and retirement plan","Current delivery and retirement schedule",
      "Schedule refreshed monthly at 100 percent","N","N",
      "Manufacturer delivery slippage is communicated on the manufacturer's cycle, not Air Canada's"),
    S("1.2","Assess network capacity impact of timing changes","Network Planning Analyst","NetLine/Plan",
      "Updated delivery schedule","Capacity impact assessment by season",
      "Impact assessed within 5 business days of a confirmed change","N","N",
      "A delivery slip cascades into every route case already assuming the new type"),
    S("2.1","Model transition period fleet mix","Fleet Planner","NetLine/Plan",
      "Overlapping old and new type operations","Transition fleet mix by season",
      "Transition mix modelled for every season with overlapping types","N","N",
      "Operating two types on one route during transition raises crew and spares cost not captured here"),
    S("2.2","Assess crew training and certification runway","Crew Planning Liaison","Jeppesen Crew",
      "New type introduction timeline","Crew readiness assessment",
      "Crew readiness confirmed before entry into service at 100 percent","Y","N",
      "Type rating training capacity is a hard constraint on how fast a new type can scale"),
    S("3.1","Update the multi-year network plan","Network Strategy Manager","NetLine/Plan",
      "Impact and readiness assessments","Updated multi-year network plan",
      "Plan updated within 10 business days of a confirmed programme change","N","N",
      "The multi-year plan is a living document but updates are not always propagated to route cases already committed"),
    S("3.2","Communicate impact to affected route cases","Network Planning Analyst","NetLine/Plan",
      "Updated multi-year plan","Notified route case owners with revised assumptions",
      "Affected route case owners notified within 5 business days of a plan update","N","N",
      "Notification is informal, so a route case can proceed on a superseded fleet assumption"),
  ],
  kpis=["Delivery and retirement schedule refreshed monthly at 100 percent",
        "Impact assessed within 5 business days of a confirmed change",
        "Crew readiness confirmed before entry into service at 100 percent",
        "Multi-year plan updated within 10 business days of a confirmed programme change"],
  risks=["Delivery slippage cascading into route cases that already assumed the new type",
         "Transition-period dual-type operation raising crew and spares cost not captured in the network model",
         "Type rating training capacity constraining how fast a new type can scale into the network",
         "Multi-year plan updates not propagating to route cases already committed on the old assumption"],
  extra_systems=["TRAX"])

P("AC-NP-FA-08",
  desc="Air Canada Jetz and other charter or premium sub-fleet capacity is scheduled separately from the "
       "core mainline assignment process, against irregular and event-driven demand.",
  trig="A charter request is received, or a premium sub-fleet block is requested for a specific event or "
       "season.",
  out="A confirmed charter or sub-fleet schedule that does not conflict with mainline rotation or "
      "maintenance commitments.",
  note="Charter demand is irregular by nature, which means it competes for aircraft and crew against a "
      "mainline schedule that is already committed months in advance.",
  phases=["Request and feasibility", "Scheduling", "Confirmation"],
  steps=[
    S("1.1","Receive and register charter request","Charter Sales Coordinator","NetLine/Plan",
      "Charter enquiry with dates and routing","Registered charter request",
      "Requests registered within 1 business day","N","N",
      "Charter requests arrive with variable notice, from months to days ahead"),
    S("1.2","Assess aircraft and crew availability","Fleet Planner","NetLine/Plan",
      "Requested dates and sub-fleet position","Availability assessment",
      "Availability assessed within 3 business days of request","Y","N",
      "Sub-fleet aircraft are also candidates for mainline recovery, creating a competing claim"),
    S("2.1","Build charter routing and timing","Schedule Planner","NetLine/Plan",
      "Confirmed availability and customer requirements","Charter schedule",
      "Charter schedule built within 5 business days of confirmed availability","N","N",
      "Charter routings can require airports outside the normal network with limited handling data"),
    S("2.2","Validate against mainline rotation conflicts","Schedule Planner","NetLine/Plan",
      "Charter schedule and mainline commitments","Conflict-free charter schedule",
      "Zero conflicts with committed mainline rotations at confirmation","Y","N",
      "A late charter confirmation can force a mainline rotation to be reworked"),
    S("3.1","Confirm and publish the charter schedule","Charter Sales Coordinator","IATA Type-B Messaging",
      "Validated schedule","Published and confirmed charter",
      "Charters confirmed to the customer within the agreed lead time at 100 percent","N","N",
      "Confirmation timing expectations differ by customer and are not standardised"),
    S("3.2","Close out and reconcile the charter operation","Charter Sales Coordinator","SAP S/4HANA",
      "Completed charter flight","Reconciled billing and operational close",
      "Charter billing reconciled within 10 business days of operation","N","N",
      "Charter-specific costs such as positioning legs are not always fully captured in billing"),
  ],
  kpis=["Zero conflicts with committed mainline rotations at confirmation",
        "Availability assessed within 3 business days of request",
        "Charter schedule built within 5 business days of confirmed availability",
        "Charters confirmed to the customer within the agreed lead time at 100 percent"],
  risks=["Sub-fleet aircraft claimed by charter demand at the same time mainline recovery needs them",
         "Late charter confirmation forcing rework of an already-committed mainline rotation",
         "Charter routings to airports outside the normal network with limited handling data on file",
         "Variable request notice, from months to days, straining the standard feasibility process"],
  extra_systems=["Amadeus Altea DCS"])
