# -*- coding: utf-8 -*-
"""AC-NP-SL — Slots, Alliance and Codeshare (7) and AC-NP-NM — Network Performance and Monitoring (7)."""
from content_lib import P, S

# ── SL ─────────────────────────────────────────────────────────────────────
P("AC-NP-SL-01",
  desc="Air Canada participates in the twice-yearly IATA Worldwide Slot Conference to secure and defend "
       "arrival and departure slots at Level 3 coordinated airports across its network.",
  trig="The IATA slot conference cycle opens for the upcoming Northern Summer or Northern Winter season.",
  out="A confirmed slot portfolio at every Level 3 airport the network requires, aligned to the committed "
      "schedule.",
  note="Slot conference outcomes constrain the schedule before commercial optimisation gets a say. A slot "
       "held at a poor time is often still worth holding, because giving it up can mean losing historic "
       "precedence permanently.",
  phases=["Slot requirement preparation", "Conference negotiation", "Confirmation and load"],
  steps=[
    S("1.1","Determine slot requirements from the schedule","Slot Coordinator","NetLine/Plan",
      "Draft seasonal schedule","Slot requirement list by airport",
      "Requirements finalised before the conference at 100 percent","N","N",
      "Requirements are drawn from a schedule that is not yet frozen"),
    S("1.2","Assess historic precedence position","Slot Coordinator","NetLine/Plan",
      "Prior season slot utilisation","Precedence position by slot",
      "Precedence position confirmed for 100 percent of held slots","N","N",
      "Utilisation shortfalls anywhere in the prior season put precedence at risk"),
    S("2.1","Attend and negotiate at the slot conference","Slot Coordinator","SITA AMS",
      "Requirement list and precedence position","Negotiated slot outcomes",
      "Priority slot requirements secured above 85 percent","Y","N",
      "New or growth slot requests compete directly against every other coordinated carrier"),
    S("2.2","Resolve slot conflicts with connecting bank needs","Network Planning Analyst","NetLine/Plan",
      "Negotiated slot times and bank design","Reconciled slot and bank position",
      "Reconciliation completed before schedule freeze at 100 percent","N","N",
      "A negotiated slot time can arrive that no longer fits the bank it was meant to serve"),
    S("3.1","Confirm final slot allocation","Slot Coordinator","SITA AMS",
      "Conference outcomes","Confirmed slot allocation",
      "Confirmation received before schedule freeze at 100 percent","N","N",
      "Confirmation can arrive after the internal schedule freeze deadline"),
    S("3.2","Load confirmed slots into the schedule","Schedule Planner","NetLine/Plan",
      "Confirmed slot allocation","Slot-aligned committed schedule",
      "Schedule matches confirmed slots at 100 percent","N","N",
      "A late slot change forces a schedule change after publication is already in motion"),
  ],
  kpis=["Priority slot requirements secured above 85 percent",
        "Precedence position confirmed for 100 percent of held slots",
        "Schedule matching confirmed slots at 100 percent",
        "Reconciliation with connecting bank needs completed before freeze at 100 percent"],
  risks=["Losing historic precedence at a key coordinated airport through a utilisation shortfall",
         "A negotiated slot time no longer fitting the connecting bank it was meant to serve",
         "Confirmation arriving after the internal schedule freeze, forcing rework",
         "New route cases blocked entirely by an inability to secure a required slot"],
  extra_systems=["Lufthansa Systems NetLine"])

P("AC-NP-SL-02",
  desc="Held slots are monitored against IATA use-it-or-lose-it thresholds throughout the season, with "
       "corrective action taken before a utilisation shortfall puts precedence at risk.",
  trig="The season is in progress and slot utilisation is tracked on a rolling basis, or an operational "
       "disruption threatens to push a slot below threshold.",
  out="A slot portfolio that retains historic precedence for the following season, with any at-risk slot "
      "identified and remediated in time.",
  note="The 80 percent use-it-or-lose-it threshold is unforgiving of operational disruption: a slot lost to "
      "an irregular operations event counts against utilisation the same as a slot lost to poor planning.",
  phases=["Utilisation tracking", "Risk identification and remediation", "Season-end reporting"],
  steps=[
    S("1.1","Track slot utilisation on a rolling basis","Slot Coordinator","SITA AMS",
      "Actual flight operation against held slots","Rolling utilisation position by slot",
      "Utilisation tracked weekly for 100 percent of held slots","N","N",
      "Utilisation tracking is manual reconciliation against the operational record"),
    S("1.2","Identify slots approaching the risk threshold","Slot Coordinator","SITA AMS",
      "Rolling utilisation position","At-risk slot list",
      "At-risk slots identified at least 6 weeks before season end","Y","N",
      "A single irregular operations event can push a slot from safe to at-risk with no warning"),
    S("2.1","Assess cause of shortfall","Slot Coordinator","NetLine/Ops",
      "At-risk slot and operational history","Shortfall cause assessment",
      "Cause assessed for 100 percent of at-risk slots","N","N",
      "Distinguishing an excusable disruption from a planning shortfall affects the waiver case"),
    S("2.2","File for justified non-use waiver where applicable","Slot Coordinator","SITA AMS",
      "Shortfall cause assessment","Filed waiver request or accepted risk",
      "Justified waivers filed within the coordinator's deadline at 100 percent","N","Y",
      "Waiver criteria are coordinator-specific and not uniform across the network"),
    S("2.3","Adjust operation to protect utilisation","Schedule Planner","NetLine/Plan",
      "At-risk slot without a waiver basis","Adjusted operation protecting the threshold",
      "At-risk slots returned above threshold above 90 percent","N","N",
      "Protecting a marginal slot can mean flying a leg that is not commercially justified on its own"),
    S("3.1","Report season-end utilisation position","Slot Coordinator","SITA AMS",
      "Final season utilisation","Season-end utilisation report",
      "Report filed within the coordinator's deadline at 100 percent","N","N",
      "Season-end reporting is the input to the following season's precedence, so an error compounds"),
  ],
  kpis=["At-risk slots identified at least 6 weeks before season end",
        "At-risk slots returned above threshold above 90 percent",
        "Justified non-use waivers filed within the coordinator's deadline at 100 percent",
        "Utilisation tracked weekly for 100 percent of held slots"],
  risks=["A slot lost to irregular operations counting against utilisation the same as one lost to poor planning",
         "Protecting a marginal slot by flying a leg with no independent commercial justification",
         "Waiver criteria varying by coordinator and being applied inconsistently",
         "Season-end reporting error compounding into the following season's precedence position"])

P("AC-NP-SL-03",
  desc="New and amended codeshare agreements with Star Alliance members and other partners are negotiated, "
       "documented and readied for schedule filing.",
  trig="A commercial opportunity for a new codeshare route is identified, or an existing agreement requires "
       "renewal or amendment.",
  out="A signed codeshare agreement with defined routes, revenue terms and operational responsibilities, "
      "ready for filing.",
  note="A codeshare agreement is a commercial contract with an operational dependency baked in: both "
       "carriers must file consistent designations or the itinerary will not construct for sale, regardless "
       "of what the contract says.",
  phases=["Opportunity and terms negotiation", "Agreement documentation", "Operational readiness"],
  steps=[
    S("1.1","Identify codeshare opportunity","Alliance Manager","NetLine/Plan",
      "Network gap or partner proposal","Documented codeshare opportunity",
      "Opportunities assessed within 10 business days of identification","N","N",
      "Opportunities can originate from either carrier with different levels of supporting analysis"),
    S("1.2","Negotiate commercial and revenue terms","Alliance Manager","Star Alliance Interline",
      "Opportunity assessment","Agreed commercial terms",
      "Terms agreed within the negotiation cycle at 100 percent","N","N",
      "Revenue-sharing terms are sensitive and negotiation can extend well beyond plan"),
    S("2.1","Document the codeshare agreement","Alliance Manager","Star Alliance Interline",
      "Agreed terms","Signed codeshare agreement",
      "Agreement signed before the required filing deadline at 100 percent","N","N",
      "Legal review timelines are not always aligned to the schedule filing calendar"),
    S("2.2","Define operational responsibilities","Alliance Manager","Star Alliance Interline",
      "Signed agreement","Documented operational responsibility split",
      "Responsibilities documented for 100 percent of new agreements","N","N",
      "Ground handling and irregular operations responsibility is often under-specified at signing"),
    S("3.1","Prepare designation filing instructions","Alliance Manager","Star Alliance Interline",
      "Documented agreement","Filing instructions to schedule publication",
      "Filing instructions issued within 5 business days of signing","N","N",
      "Filing instructions must match exactly between both carriers or construction fails"),
    S("3.2","Confirm through-check and baggage agreement","Alliance Manager","IATA Type-B Messaging",
      "Filing instructions","Confirmed through-check capability",
      "Through-check confirmed before the route goes live at 100 percent","N","N",
      "Through-check depends on station-level agreements separate from the commercial contract"),
  ],
  kpis=["Agreement signed before the required filing deadline at 100 percent",
        "Filing instructions issued within 5 business days of signing",
        "Operational responsibilities documented for 100 percent of new agreements",
        "Through-check confirmed before the route goes live at 100 percent"],
  risks=["Filing designation mismatch between carriers preventing the itinerary from constructing",
         "Ground handling and irregular operations responsibility left under-specified at signing",
         "Legal review timelines running past the schedule filing calendar",
         "Through-check unavailable at a specific station despite a signed commercial agreement"],
  extra_systems=["Amadeus Altea Inventory"])

P("AC-NP-SL-04",
  desc="Filed codeshare and interline agreements are audited against actual schedule and designation data "
       "to confirm they remain compliant and correctly constructed for sale.",
  trig="A scheduled compliance audit cycle runs, or a partner or internal report flags a construction "
       "failure on a codeshare itinerary.",
  out="A verified codeshare and interline filing position with any construction failure identified and "
      "corrected.",
  note="Filing compliance degrades quietly: a schedule change on either side can silently break a previously "
       "working designation, and the first sign is often a booking failure rather than an audit finding.",
  phases=["Filing verification", "Failure investigation", "Correction and reporting"],
  steps=[
    S("1.1","Extract current codeshare filing position","Alliance Manager","Star Alliance Interline",
      "Filed designations across active agreements","Current filing extract",
      "Extract produced for each audit cycle at 100 percent","N","N",
      "The extract spans multiple partner systems with no single consolidated source"),
    S("1.2","Compare filings against agreement terms","Alliance Manager","Star Alliance Interline",
      "Filing extract and signed agreements","Compliance comparison with variance list",
      "Variances identified for 100 percent of active agreements","N","N",
      "Agreement terms change through informal partner communication that is not always reflected in filing"),
    S("2.1","Test itinerary construction for sampled routes","Network Planning Analyst","Amadeus Altea Inventory",
      "Filed designations","Construction test results",
      "Sampled routes tested each audit cycle at 100 percent","N","N",
      "A construction failure can exist for weeks before a booking attempt surfaces it"),
    S("2.2","Investigate construction failures","Alliance Manager","Amadeus Altea Inventory",
      "Failed construction case","Root cause of the failure",
      "Root cause identified within 5 business days of detection","N","Y",
      "Root cause can sit with either carrier's filing, which slows joint diagnosis"),
    S("3.1","Correct filing discrepancies","Alliance Manager","Star Alliance Interline",
      "Root cause finding","Corrected filing",
      "Corrections filed within 5 business days of root cause confirmation","N","N",
      "A correction on one side must be matched by the partner or the fix does not take"),
    S("3.2","Report compliance position","Alliance Manager","Star Alliance Interline",
      "Corrected filings and residual issues","Compliance report",
      "Compliance report issued each audit cycle at 100 percent","N","N",
      "Historical compliance trends are not tracked, so recurring issues are not visible over time"),
  ],
  kpis=["Sampled routes tested each audit cycle at 100 percent",
        "Root cause identified within 5 business days of detection",
        "Corrections filed within 5 business days of root cause confirmation",
        "Variances identified for 100 percent of active agreements"],
  risks=["A schedule change on either carrier silently breaking a previously working codeshare designation",
         "Construction failures going undetected for weeks until a booking attempt surfaces them",
         "A correction on one side not matched by the partner, so the underlying fix does not take",
         "Recurring compliance issues invisible because historical trends are not tracked"])

P("AC-NP-SL-05",
  desc="Bilateral air service agreements and route authorities are tracked and filed with the relevant "
       "regulators to support route cases that require rights Air Canada does not already hold.",
  trig="A route case requires traffic rights not currently held, or a bilateral agreement changes in a way "
       "that affects an existing or planned route.",
  out="Confirmed route authority and traffic rights sufficient to operate the planned schedule, filed with "
      "the relevant regulators.",
  note="Route authority is a precondition, not a formality: a commercially validated route case is worthless "
       "without the underlying bilateral rights, and bilateral negotiation operates on a government timeline "
       "that Air Canada does not control.",
  phases=["Rights assessment", "Application and negotiation support", "Confirmation"],
  steps=[
    S("1.1","Assess required traffic rights against holdings","Regulatory Affairs Analyst","NetLine/Plan",
      "Route case requirements and current rights register","Rights gap assessment",
      "Gap assessed before route case approval at 100 percent","N","N",
      "The rights register is not always current with the latest bilateral text"),
    S("2.1","Prepare regulatory application","Regulatory Affairs Analyst","NetLine/Plan",
      "Rights gap and route case detail","Filed application to Transport Canada or the CTA",
      "Applications filed within the required lead time at 100 percent","N","N",
      "Application requirements differ by destination country and are not standardised"),
    S("2.2","Support bilateral negotiation where required","Regulatory Affairs Analyst","NetLine/Plan",
      "Rights gap requiring bilateral renegotiation","Negotiation support position",
      "Support provided for 100 percent of bilateral-dependent route cases","N","Y",
      "Bilateral negotiation runs on a government timeline outside Air Canada's control"),
    S("3.1","Confirm granted rights","Regulatory Affairs Analyst","NetLine/Plan",
      "Regulatory decision","Confirmed traffic rights",
      "Confirmation received before the committed launch date at 100 percent","N","N",
      "A route case can be commercially committed before rights are actually confirmed"),
    S("3.2","Update the rights register and route case status","Regulatory Affairs Analyst","NetLine/Plan",
      "Confirmed rights","Updated rights register",
      "Register updated within 5 business days of confirmation","N","N",
      "An outdated register can allow a future route case to assume rights that were never granted"),
    S("3.3","Notify network planning of confirmed rights scope","Regulatory Affairs Analyst","NetLine/Plan",
      "Updated register","Route case cleared to proceed within confirmed scope",
      "Notification issued within 2 business days of a register update","N","N",
      "Rights are sometimes granted with conditions that narrow the route case beyond its original assumption"),
  ],
  kpis=["Rights gap assessed before route case approval at 100 percent",
        "Applications filed within the required lead time at 100 percent",
        "Confirmation received before the committed launch date at 100 percent",
        "Rights register updated within 5 business days of confirmation"],
  risks=["A commercially committed route case launching before traffic rights are actually confirmed",
         "Bilateral negotiation timelines outside Air Canada's control delaying a committed launch",
         "An outdated rights register allowing a future route case to assume rights never granted",
         "Application requirements varying by destination country with no standardised process"])

P("AC-NP-SL-06",
  desc="Star Alliance-wide schedule coordination aligns Air Canada's published schedule with the broader "
       "alliance network to protect connection quality and status recognition across all 26 members.",
  trig="A Star Alliance coordination cycle runs ahead of each season, or a major member's schedule change "
       "materially affects Air Canada connections.",
  out="An Air Canada schedule coordinated with the alliance network for the season, with priority "
      "connections protected.",
  note="Star Alliance coordination is broader but shallower than the A++ joint venture: it covers 26 members "
      "rather than five, so in practice Air Canada actively coordinates only with the highest-connecting-"
      "value partners and accepts the schedule as given for the rest.",
  phases=["Alliance schedule exchange", "Priority connection protection", "Season alignment"],
  steps=[
    S("1.1","Exchange schedules across the alliance","Alliance Manager","Star Alliance Interline",
      "Air Canada published schedule","Alliance-wide schedule exchange",
      "Exchange completed ahead of each season at 100 percent","N","N",
      "26 members exchange on different cycles, so a complete picture is rarely available at once"),
    S("1.2","Identify priority connecting partners","Alliance Manager","Databricks Lakehouse",
      "Connecting traffic volume by partner","Prioritised partner list",
      "Priority list refreshed each season","N","N",
      "Connecting value is concentrated in a handful of partners but the list is not formally reviewed often"),
    S("2.1","Protect priority connections in schedule design","Network Planning Analyst","NetLine/Plan",
      "Priority partner schedules","Protected connection timings",
      "Priority connections protected on 90 percent of target markets","Y","N",
      "Protecting one partner's connections can compromise another's in the same bank"),
    S("2.2","Coordinate status recognition and lounge access","Alliance Manager","Star Alliance Interline",
      "Alliance membership terms","Confirmed reciprocal recognition",
      "Recognition confirmed for 100 percent of alliance touchpoints","N","N",
      "Recognition terms are broad but station-level implementation varies"),
    S("3.1","Align final schedule to alliance commitments","Schedule Planner","NetLine/Plan",
      "Protected connections and alliance terms","Alliance-aligned committed schedule",
      "Alignment complete before schedule freeze at 100 percent","N","N",
      "Late alliance schedule changes arrive after Air Canada's own schedule is already committed"),
    S("3.2","Report alliance coordination outcomes","Alliance Manager","Star Alliance Interline",
      "Aligned schedule","Coordination outcome report",
      "Report issued within 10 business days of schedule freeze","N","N",
      "Outcomes are reported per season with no year-over-year trend view"),
  ],
  kpis=["Priority connections protected on 90 percent of target markets",
        "Exchange completed ahead of each season at 100 percent",
        "Reciprocal recognition confirmed for 100 percent of alliance touchpoints",
        "Alignment complete before schedule freeze at 100 percent"],
  risks=["Protecting one partner's connections compromising another's in the same connecting bank",
         "26 members exchanging schedules on different cycles, leaving no single complete picture",
         "Late alliance schedule changes arriving after Air Canada's own schedule is already committed",
         "Station-level recognition implementation varying despite broad alliance-level terms"])

P("AC-NP-SL-07",
  desc="Onboarding a new codeshare or interline partner into schedule systems, covering system "
       "certification, designation testing and staff readiness before the first live booking.",
  trig="A new codeshare or interline agreement is signed and requires system-level onboarding before routes "
       "can go on sale.",
  out="A certified, tested partner interface with confirmed construction, through-check and staff readiness "
      "ahead of first sale.",
  note="Commercial agreement and system readiness are frequently on different timelines, and the gap "
      "between a signed contract and a working, tested interface is where launch dates slip.",
  phases=["Interface certification", "Construction and process testing", "Go-live readiness"],
  steps=[
    S("1.1","Certify the partner interface","Integration Analyst","Star Alliance Interline",
      "Partner system specification","Certified interface connection",
      "Certification completed before construction testing at 100 percent","N","N",
      "Partner system specifications vary in completeness and quality"),
    S("1.2","Configure designation and fare construction rules","Network Planning Analyst","Amadeus Altea Inventory",
      "Signed agreement terms","Configured construction rules",
      "Configuration matches signed agreement terms at 100 percent","N","N",
      "Configuration is a manual translation of contract language into system rules"),
    S("2.1","Test itinerary construction end to end","Network Planning Analyst","Amadeus Altea Inventory",
      "Configured rules","Construction test results",
      "All planned route pairs construct successfully before go-live","Y","N",
      "Test coverage rarely spans every fare and cabin combination the agreement permits"),
    S("2.2","Test through-check and baggage handling","Ground Operations Liaison","IATA Type-B Messaging",
      "Test itineraries","Through-check test results",
      "Through-check tested at every station with the new partner before go-live","N","N",
      "Station-level testing requires coordination the commercial timeline does not always allow for"),
    S("3.1","Brief front-line and contact centre staff","Training Coordinator","Salesforce Service Cloud",
      "New partner agreement summary","Briefed and ready staff",
      "Briefing completed before go-live at 100 percent","N","N",
      "Front-line staff often learn about a new partner from a customer booking before formal briefing"),
    S("3.2","Confirm go-live and open for sale","Alliance Manager","Amadeus Altea NDC",
      "All readiness confirmations","Partner routes open for sale",
      "Go-live occurs on the committed date at 100 percent","N","N",
      "A single failed readiness item can force a go-live delay after the commercial launch was announced"),
  ],
  kpis=["All planned route pairs constructing successfully before go-live",
        "Through-check tested at every relevant station before go-live",
        "Configuration matching signed agreement terms at 100 percent",
        "Go-live occurring on the committed date at 100 percent"],
  risks=["Commercial launch dates announced before system readiness is actually confirmed",
         "Test coverage missing a fare or cabin combination the agreement technically permits",
         "Front-line staff learning about a new partner from a customer booking rather than a briefing",
         "Station-level through-check testing not completing in time for a committed go-live date"],
  extra_systems=["Sabre GDS"])

# ── NM ─────────────────────────────────────────────────────────────────────
P("AC-NP-NM-01",
  desc="Route profitability is reviewed on a recurring cycle against the original route case, producing a "
       "network scorecard that informs whether a route continues, grows or is withdrawn.",
  trig="The recurring route review cycle runs, or a route's performance triggers an off-cycle review.",
  out="An updated profitability position for every active route, with a clear continue, grow or exit "
      "recommendation.",
  note="A route case is a point-in-time judgement; the review is what tests whether that judgement held. "
       "Routes rarely get formally closed out against their original case, so the network's collective "
       "track record on route decisions is not actually measured.",
  phases=["Performance compilation", "Case comparison", "Recommendation"],
  steps=[
    S("1.1","Compile actual route revenue and cost","Network Planning Analyst","SAP Analytics Cloud",
      "Actual traffic, revenue and cost data","Route profitability by period",
      "Profitability compiled for 100 percent of active routes each cycle","N","N",
      "Cost allocation to a single route is an estimate built on network-wide cost pools"),
    S("1.2","Compare actual to the original route case","Network Planning Analyst","NetLine/Plan",
      "Actual profitability and original case assumptions","Variance against original case",
      "Variance calculated for 100 percent of routes within their case window","N","N",
      "Original case assumptions are not always retained in a form that supports comparison"),
    S("2.1","Attribute variance to demand, price or cost drivers","Revenue Management Analyst","PROS Revenue Management",
      "Variance data","Attributed variance by driver",
      "Attribution completed for all material variances","N","N",
      "Attribution is judgement-led where drivers interact, such as a price change under weak demand"),
    S("2.2","Score routes against the network scorecard","Network Planning Analyst","NetLine/Plan",
      "Attributed performance","Scored route position",
      "Scorecard produced each review cycle at 100 percent","N","N",
      "A single scorecard metric can obscure a route whose value is mostly connecting contribution"),
    S("3.1","Recommend continue, grow or exit","Network Strategy Manager","NetLine/Plan",
      "Scored route position","Documented recommendation",
      "Recommendations issued for 100 percent of underperforming routes","Y","N",
      "Exit recommendations are commercially and politically harder to act on than grow recommendations"),
    S("3.2","Track recommendation to decision closure","Network Planning Analyst","NetLine/Plan",
      "Issued recommendation","Closed decision record",
      "Recommendations closed to a decision within 60 days at 90 percent","N","N",
      "Recommendations without a forced decision point tend to persist unresolved across cycles"),
  ],
  kpis=["Profitability compiled for 100 percent of active routes each cycle",
        "Recommendations issued for 100 percent of underperforming routes",
        "Variance calculated for 100 percent of routes within their case window",
        "Routes formally closed out against their original case above 60 percent"],
  risks=["Route cost allocation being an estimate that can misstate an individual route's true profitability",
         "Connecting contribution value obscured by a scorecard metric built for point to point routes",
         "Exit recommendations systematically deferred relative to grow recommendations",
         "The network's collective track record on route decisions never actually being measured"])

P("AC-NP-NM-02",
  desc="Competitor capacity and schedule changes are tracked continuously and benchmarked against Air "
       "Canada's own network to inform both tactical response and the next planning cycle.",
  trig="A competitor announces or files a capacity or schedule change, or the recurring benchmarking cycle "
       "runs.",
  out="A current competitive capacity picture with flagged material changes and their likely commercial "
      "impact on Air Canada's network.",
  note="Competitive intelligence here is mostly public schedule filings rather than anything proprietary, "
       "which means the discipline is in consistent tracking and fast interpretation, not data access.",
  phases=["Capacity tracking", "Impact assessment", "Response recommendation"],
  steps=[
    S("1.1","Track competitor schedule filings","Network Planning Analyst","OAG Schedule Analyser",
      "Published competitor schedules","Tracked competitor capacity position",
      "Tracking refreshed weekly for all overlapping markets","N","N",
      "Filed schedules do not always operate as filed, so tracking can overstate real competitive capacity"),
    S("1.2","Flag material capacity changes","Network Planning Analyst","OAG Schedule Analyser",
      "Tracked capacity position","Flagged material change list",
      "Material changes flagged within 3 business days of filing","N","N",
      "Materiality thresholds are judgement based and applied inconsistently"),
    S("2.1","Assess demand and share impact","Revenue Management Analyst","PROS Revenue Management",
      "Flagged competitor change","Impact assessment by overlapping route",
      "Impact assessed within 5 business days of flagging","N","N",
      "Share impact modelling assumes competitor capacity actually operates as filed"),
    S("3.1","Recommend tactical or structural response","Network Planning Analyst","NetLine/Plan",
      "Impact assessment","Response recommendation",
      "Recommendation issued within 10 business days of a material change","Y","N",
      "A tactical pricing response and a structural capacity response draw on different planning cycles"),
    S("3.2","Feed findings into the next planning cycle","Network Planning Analyst","Databricks Lakehouse",
      "Cumulative competitive findings","Input to route case and schedule build",
      "Findings incorporated into every relevant route case at 100 percent","N","N",
      "Findings are captured per incident but not consolidated into a standing competitive picture"),
    S("3.3","Maintain the standing competitive intelligence picture","Network Planning Analyst","Databricks Lakehouse",
      "Consolidated incident history","Standing competitive position by market",
      "Standing picture refreshed each planning cycle at 100 percent","N","N",
      "Without a standing view, the same competitive pattern is re-analysed from scratch each time"),
  ],
  kpis=["Material changes flagged within 3 business days of filing",
        "Impact assessed within 5 business days of flagging",
        "Response recommendation issued within 10 business days of a material change",
        "Tracking refreshed weekly for all overlapping markets"],
  risks=["Filed competitor schedules not operating as filed, overstating the real competitive threat",
         "Materiality thresholds applied inconsistently, so a real threat goes unflagged",
         "Findings captured per incident rather than consolidated into a standing competitive picture",
         "Tactical and structural response recommendations competing for the same limited planning capacity"])

P("AC-NP-NM-03",
  desc="Load factor and RASK are tracked against plan and prior year, with variance analysed to distinguish "
       "demand, price and network structure effects.",
  trig="The recurring commercial performance reporting cycle runs.",
  out="A load factor and RASK variance report with drivers attributed, feeding both tactical revenue "
      "management action and route review.",
  note="RASK variance is a single number produced by several moving parts, and the value of this process "
      "is entirely in correctly separating them rather than in the calculation itself.",
  phases=["Performance compilation", "Variance attribution", "Distribution"],
  steps=[
    S("1.1","Compile load factor and RASK by route","Revenue Management Analyst","PROS Revenue Management",
      "Actual traffic and revenue data","Load factor and RASK by route and period",
      "Compiled within 3 business days of period close at 100 percent","N","N",
      "Late-posting revenue adjustments can restate a period after it has already been reported"),
    S("2.1","Compare to plan and prior year","Revenue Management Analyst","SAP Analytics Cloud",
      "Compiled performance and plan baseline","Variance against plan and prior year",
      "Variance produced for 100 percent of routes each period","N","N",
      "Prior year comparison is distorted wherever the network structure itself has changed"),
    S("2.2","Attribute variance to demand, price and mix","Revenue Management Analyst","PROS Revenue Management",
      "Variance data","Attributed variance by driver",
      "Attribution completed for all material variances","N","N",
      "Mix effects from a schedule or gauge change are the hardest driver to isolate cleanly"),
    S("3.1","Distribute findings to revenue management and network planning","Revenue Management Analyst","SAP Analytics Cloud",
      "Attributed variance","Distributed variance report",
      "Report distributed within 5 business days of period close","N","N",
      "The report reaches two audiences with different needs from the same document"),
    S("3.2","Reconcile against late-posted revenue restatements","Revenue Management Analyst","Revenue Accounting System",
      "Restated period revenue","Reconciled and corrected variance report",
      "Restatements reconciled within 10 business days of posting","N","Y",
      "A restatement received after the report has already driven a network decision cannot easily be walked back"),
    S("3.3","Archive period findings for trend analysis","Revenue Management Analyst","Databricks Lakehouse",
      "Reconciled variance report","Archived period record",
      "Every period archived in a comparable format at 100 percent","N","N",
      "Inconsistent archiving format across periods makes multi-period trend analysis harder than it should be"),
  ],
  kpis=["Compiled within 3 business days of period close at 100 percent",
        "Report distributed within 5 business days of period close",
        "Attribution completed for all material variances",
        "Late revenue restatements affecting a reported period below 2 percent of periods"],
  risks=["Late-posting revenue adjustments restating a period after it has already been reported and acted on",
         "Mix effects from a schedule or gauge change being the hardest driver to isolate correctly",
         "Prior year comparison distorted wherever the network structure has itself changed",
         "One report serving two audiences with materially different needs"])

P("AC-NP-NM-04",
  desc="On-time performance is analysed to root cause, separating network design, airport process, crew and "
       "weather contributions so that structural fixes can be distinguished from operational ones.",
  trig="The recurring OTP reporting cycle runs, or a sustained OTP decline triggers a deep-dive review.",
  out="An OTP root cause report attributing delay to network, airport, crew, weather or aircraft causes, "
      "with recommendations addressed to the right owner.",
  note="On-time performance is reported as a single number but its causes sit in different domains, so a "
      "network-design problem, an airport turnaround problem and a crew problem can produce an identical "
      "OTP figure while needing completely different fixes.",
  phases=["Delay data compilation", "Root cause attribution", "Recommendation and routing"],
  steps=[
    S("1.1","Compile delay data by cause code","Network Planning Analyst","NetLine/Ops",
      "Operational delay records","Compiled delay data by cause code",
      "Compiled within 3 business days of period close at 100 percent","N","N",
      "Cause codes are recorded under operational time pressure and are not always precise"),
    S("2.1","Attribute delay to network design","Network Planning Analyst","NetLine/Plan",
      "Compiled delay data and schedule structure","Network-attributed delay",
      "Network attribution completed each reporting cycle","N","N",
      "Insufficient ground time built into the schedule reads as an airport delay unless traced back"),
    S("2.2","Attribute delay to airport and ground process","Network Planning Analyst","Amadeus Altea DCS",
      "Compiled delay data and station performance","Airport-attributed delay",
      "Airport attribution completed each reporting cycle","N","N",
      "Station-level process issues are masked when reported only at the network level"),
    S("2.3","Attribute delay to crew and maintenance","Network Planning Analyst","TRAX",
      "Compiled delay data","Crew and maintenance attributed delay",
      "Crew and maintenance attribution completed each reporting cycle","N","N",
      "Crew-caused and maintenance-caused delay are sometimes coded interchangeably at source"),
    S("3.1","Route structural findings to the responsible owner","Network Planning Analyst","NetLine/Plan",
      "Attributed root causes","Findings routed with an owner and target",
      "Findings routed within 10 business days of the reporting cycle","N","N",
      "A finding routed to the wrong owner sits unactioned until the next review surfaces it again"),
    S("3.2","Track structural fix implementation","Network Planning Analyst","NetLine/Plan",
      "Routed finding","Confirmed fix implementation or documented deferral",
      "Structural fixes implemented or explicitly deferred within one planning cycle at 90 percent","N","N",
      "Implementation tracking stops at the recommendation and is not closed against actual delivery"),
  ],
  kpis=["Compiled within 3 business days of period close at 100 percent",
        "Findings routed within 10 business days of the reporting cycle",
        "Network attribution completed each reporting cycle",
        "OTP root cause correctly attributed on 85 percent of material delay drivers"],
  risks=["Insufficient scheduled ground time reading as an airport delay unless explicitly traced back",
         "Crew-caused and maintenance-caused delay coded interchangeably at the point of entry",
         "A structural finding routed to the wrong owner going unactioned for a full reporting cycle",
         "Station-level process issues masked by a network-level aggregate OTP figure"])

P("AC-NP-NM-05",
  desc="The integrity of connecting banks is monitored in service to confirm the connections sold actually "
       "achieve their planned reliability, and to feed structural findings back into bank design.",
  trig="The recurring bank integrity reporting cycle runs, or a specific connecting market shows a "
       "misconnect spike.",
  out="A bank integrity report identifying connections that are structurally unreliable, distinct from "
      "those affected by a one-off disruption.",
  note="Not every misconnect is the same kind of problem: an occasional weather-driven misconnect is a "
      "different issue from a connection that is structurally too tight to work reliably, and only the "
      "second belongs back in bank design.",
  phases=["Misconnect data compilation", "Structural versus incidental classification", "Feedback to design"],
  steps=[
    S("1.1","Compile misconnect data by connecting market","Network Planning Analyst","Amadeus Altea DCS",
      "Actual connection outcomes","Misconnect data by market",
      "Compiled within 5 business days of period close at 100 percent","N","N",
      "Misconnect data spans mainline, Rouge and partner-operated legs inconsistently"),
    S("2.1","Classify misconnects as structural or incidental","Network Planning Analyst","NetLine/Ops",
      "Misconnect data and disruption records","Classified misconnect data",
      "Classification completed for 100 percent of material misconnect markets","Y","N",
      "Distinguishing a structurally tight connection from a one-off disruption requires judgement"),
    S("2.2","Identify structurally unreliable connections","Network Planning Analyst","NetLine/Plan",
      "Classified misconnect data","Structurally unreliable connection list",
      "Structural connections identified each reporting cycle at 100 percent","N","N",
      "A connection can look structurally sound on paper while consistently failing in practice"),
    S("3.1","Feed structural findings back to bank design","Network Planning Analyst","NetLine/Plan",
      "Structurally unreliable connection list","Bank design input for the next cycle",
      "Findings fed into the next seasonal build at 100 percent","N","N",
      "Bank design changes take a full season to implement, so the feedback loop is slow"),
    S("3.2","Report bank integrity trend by hub","Network Planning Analyst","SAP Analytics Cloud",
      "Structural findings history","Bank integrity trend report by hub",
      "Trend report issued each reporting cycle at 100 percent","N","N",
      "Without a trend view, an improving or worsening hub is not visible until it is already severe"),
    S("3.3","Escalate persistent structural failure to network review","Network Strategy Manager","NetLine/Plan",
      "Trend report showing persistent failure","Escalated case for the next network review",
      "Persistent structural failures escalated within one reporting cycle at 100 percent","N","Y",
      "A connection that fails structurally for multiple consecutive seasons still requires an explicit escalation to act on"),
  ],
  kpis=["Compiled within 5 business days of period close at 100 percent",
        "Classification completed for 100 percent of material misconnect markets",
        "Findings fed into the next seasonal build at 100 percent",
        "Structural misconnect rate reduced season over season on flagged markets"],
  risks=["Misconnect data spanning mainline, Rouge and partner-operated legs inconsistently",
         "A connection sold as reliable that is actually structurally too tight to work",
         "The feedback loop from in-service finding to bank redesign taking a full season",
         "One-off disruption misclassified as a structural finding, triggering an unnecessary redesign"])

P("AC-NP-NM-06",
  desc="Schedule reliability is tracked at the block-time level, tuning planned block times so they reflect "
       "achievable performance rather than an aspirational target.",
  trig="The recurring block time review cycle runs, or a route shows a persistent gap between planned and "
       "actual block time.",
  out="Tuned block times that reflect achievable performance, reducing both chronic delay and unnecessary "
      "schedule padding.",
  note="Block time sits between two failure modes: too tight and the route chronically reports as late, too "
      "generous and aircraft utilisation is wasted. Getting this right is a continuous tuning exercise, not "
      "a one-time calculation.",
  phases=["Actual performance analysis", "Block time tuning", "Validation and commitment"],
  steps=[
    S("1.1","Compile actual block time distribution","Network Planning Analyst","NetLine/Ops",
      "Actual flight time data by route","Block time distribution by route",
      "Distribution compiled for 100 percent of routes each review cycle","N","N",
      "Distribution is affected by seasonal wind patterns that a single average obscures"),
    S("1.2","Identify chronic over or under performance","Network Planning Analyst","Databricks Lakehouse",
      "Block time distribution","Flagged routes with persistent variance",
      "Flagged routes identified each review cycle at 100 percent","N","N",
      "A single flagged route can be masking a seasonal effect rather than a genuine planning error"),
    S("2.1","Propose tuned block time by season","Network Planning Analyst","NetLine/Plan",
      "Flagged routes and distribution data","Proposed block time by route and season",
      "Proposals produced for 100 percent of flagged routes","N","N",
      "Tuning to the average can still leave a route chronically late in one direction on a windy sector"),
    S("2.2","Assess rotation and gate impact of the change","Schedule Planner","NetLine/Plan",
      "Proposed block time change","Rotation feasibility assessment",
      "Feasibility assessed for 100 percent of proposed changes","Y","N",
      "A block time increase on one leg can break the rotation it is embedded in"),
    S("3.1","Validate and commit tuned block times","Network Planning Analyst","NetLine/Plan",
      "Feasibility-assessed proposal","Committed block time change",
      "Changes committed for the next applicable season at 100 percent","N","N",
      "Committed changes only take effect at the next schedule build, so correction is never immediate"),
    S("3.2","Monitor post-tuning reliability","Network Planning Analyst","NetLine/Ops",
      "Committed block time change","Post-tuning reliability confirmation",
      "Reliability confirmed within one season of the change on 90 percent of tuned routes","N","N",
      "A tuning that looked correct on historical data can still miss on the season it is applied to"),
  ],
  kpis=["Distribution compiled for 100 percent of routes each review cycle",
        "Flagged routes identified each review cycle at 100 percent",
        "Feasibility assessed for 100 percent of proposed changes",
        "Chronic block time variance reduced season over season on tuned routes"],
  risks=["Tuning to an average that still leaves a route chronically late in one direction on a windy sector",
         "A block time increase on one leg breaking the rotation it is embedded in",
         "Seasonal wind effects masked by an annual average and misread as a planning error",
         "Correction only taking effect at the next schedule build, with no immediate remedy"])

P("AC-NP-NM-07",
  desc="A structured post-implementation review is conducted after each seasonal schedule closes, comparing "
       "the delivered schedule against the plan and feeding disciplined lessons into the next build cycle.",
  trig="A seasonal schedule closes at season end.",
  out="A documented post-implementation review with findings assigned to a specific owner and traceable "
      "into the next planning cycle.",
  note="Without a structured review, lessons from a season live only in the memory of the planners who "
      "worked it, and turnover quietly erodes institutional knowledge about what actually worked.",
  phases=["Performance reconciliation", "Findings synthesis", "Action assignment"],
  steps=[
    S("1.1","Reconcile delivered schedule against plan","Network Planning Analyst","NetLine/Plan",
      "Planned and actual seasonal schedule","Delivered versus planned reconciliation",
      "Reconciliation completed within 20 business days of season end","N","N",
      "In-season changes accumulate and the final delivered schedule can differ substantially from the frozen plan"),
    S("1.2","Compile commercial and operational performance","Network Planning Analyst","SAP Analytics Cloud",
      "Route profitability, OTP and bank integrity data","Consolidated season performance",
      "Consolidated within 20 business days of season end","N","N",
      "Consolidation draws on several separate reporting processes that close on different schedules"),
    S("2.1","Synthesise structural findings","Network Strategy Manager","NetLine/Plan",
      "Consolidated performance and prior findings","Synthesised structural findings",
      "Findings synthesised within 30 business days of season end","N","N",
      "Findings from different functions are not automatically cross-referenced against each other"),
    S("2.2","Compare findings against the prior season's review","Network Strategy Manager","NetLine/Plan",
      "Current and prior season findings","Trend assessment across seasons",
      "Trend comparison completed for every recurring finding","N","N",
      "Without this comparison, the same structural issue can be rediscovered every season"),
    S("3.1","Assign findings to an owner and target cycle","Network Strategy Manager","NetLine/Plan",
      "Synthesised findings","Assigned action with owner and target",
      "100 percent of material findings assigned an owner","N","N",
      "Findings without a named owner and a target cycle default to being lost by the next season"),
    S("3.2","Publish the season review to stakeholders","Network Strategy Manager","NetLine/Plan",
      "Assigned findings and actions","Published season review",
      "Review published within 40 business days of season end at 100 percent","N","N",
      "A review that is not actively distributed is read only by the team that wrote it"),
  ],
  kpis=["Reconciliation completed within 20 business days of season end",
        "100 percent of material findings assigned an owner",
        "Findings synthesised within 30 business days of season end",
        "Recurring findings from the prior season correctly identified as recurring"],
  risks=["In-season changes accumulating until the delivered schedule differs substantially from the frozen plan",
         "The same structural issue being rediscovered every season with no year-over-year comparison",
         "Findings without a named owner and target cycle defaulting to being lost",
         "Institutional knowledge about what worked in a season eroding with planner turnover"])
