# -*- coding: utf-8 -*-
"""AC-NP-SP — Network Planning and Scheduling > Schedule Planning and Design (8 processes)."""
from content_lib import P, S

P("AC-NP-SP-01",
  desc="Air Canada develops the long-range case for entering, exiting or materially re-sizing a route, "
       "covering demand, competitive position, fleet fit, and the alliance and joint venture implications. "
       "The output is a decision paper that commits capacity two to three seasons ahead of flying.",
  trig="A network strategy cycle opens, a competitor announces a material capacity change, or a bilateral "
       "or slot opportunity creates a window that has to be taken or lost.",
  out="An approved or rejected route case with a committed fleet type, frequency and season, entered into "
      "the long-range plan and handed to seasonal schedule build.",
  note="Air Canada's network economics rest heavily on Sixth Freedom connecting traffic through Toronto, "
       "carrying passengers between the United States and Europe or Asia over a Canadian hub. A route case "
       "is therefore rarely judged on its own local demand: it is judged on what it contributes to the "
       "connecting bank. The A++ transatlantic joint venture with United and Lufthansa Group constrains "
       "transatlantic route cases before commercial optimisation begins, because capacity there is a joint "
       "decision rather than a unilateral one.",
  phases=["Opportunity framing", "Commercial and operational validation", "Decision and commitment"],
  steps=[
    S("1.1","Register route opportunity","Network Planning Analyst","NetLine/Plan",
      "Strategy cycle input or market signal","Registered opportunity with a case reference",
      "Opportunities registered within 5 business days of identification","N","N",
      "Opportunities surface informally through commercial contacts and are not consistently captured"),
    S("1.2","Build origin and destination demand estimate","Network Planning Analyst","Databricks Lakehouse",
      "Historic traffic, booking curves and market size data","O and D demand estimate by cabin",
      "Demand estimate within 10 percent of first-season actual","N","N",
      "Thin and unserved markets have no Air Canada booking history to anchor the estimate"),
    S("1.3","Assess competitive position and response","Network Planning Analyst","Databricks Lakehouse",
      "Competitor schedules and published capacity","Competitive assessment with expected response",
      "Competitive response correctly anticipated in 70 percent of cases","N","N",
      "Competitor response modelling is judgement-led and rarely revisited after the decision"),
    S("1.4","Quantify connecting contribution over the hub","Network Planning Analyst","NetLine/Plan",
      "Bank structure and connecting itinerary options","Connecting traffic contribution by hub",
      "Connecting contribution quantified for 100 percent of long-haul cases","N","N",
      "Connecting value depends on the future bank structure, which is not fixed at this point"),
    S("2.1","Test fleet and range feasibility","Fleet Planner","NetLine/Plan",
      "Candidate fleet types and sector length","Feasible fleet options with payload and range limits",
      "Fleet feasibility confirmed before commercial approval at 100 percent","Y","N",
      "Fleet availability in the target season is itself uncertain during fleet renewal"),
    S("2.2","Model revenue and unit cost","Revenue Management Analyst","PROS Revenue Management",
      "Demand estimate and fare environment","Revenue and RASK projection by season",
      "Revenue projection within 12 percent of first-season actual","N","N",
      "Projections use current fare levels and do not price the competitive response modelled earlier"),
    S("2.3","Assess joint venture and alliance implications","Alliance Manager","A++ Atlantic Joint Venture",
      "Route case and partner network","Joint venture position or partner objection",
      "Alliance position obtained before commitment at 100 percent","Y","N",
      "Transatlantic capacity is a joint decision, so the case can be commercially sound and still blocked"),
    S("2.4","Confirm slot and infrastructure availability","Slot Coordinator","NetLine/Plan",
      "Required timings at both ends","Slot feasibility assessment",
      "Slot feasibility confirmed before commitment at 100 percent","Y","N",
      "Level 3 slots at the required timing may only be obtainable at a historic-precedence disadvantage"),
    S("2.5","Assess crew and maintenance base implications","Network Strategy Manager","Jeppesen Crew",
      "Proposed pattern and base structure","Crew and engineering support assessment",
      "Support implications assessed for all new-station cases","N","N",
      "Crew base and line-station consequences surface late and can invert a marginal case"),
    S("3.1","Assemble decision paper","Network Planning Analyst","NetLine/Plan",
      "All validation outputs","Consolidated route case decision paper",
      "Decision paper complete 2 weeks before the network committee","N","N",
      "Inputs arrive from six functions in different formats and are consolidated by hand"),
    S("3.2","Take network committee decision","Network Strategy Manager","NetLine/Plan",
      "Decision paper","Approved, rejected or deferred route case",
      "Decisions taken at the scheduled committee without deferral above 80 percent","Y","N",
      "Deferral is the default outcome when one input is weak, which pushes the whole season"),
    S("3.3","Commit to the long-range plan","Network Planning Analyst","NetLine/Plan",
      "Approved route case","Capacity committed in the long-range plan",
      "Approved cases committed to plan within 5 business days","N","N",
      "A commitment made this far ahead is expensive to unwind once crew and maintenance plan against it"),
  ],
  kpis=["Route case demand estimate within 10 percent of first-season actual",
        "Revenue projection within 12 percent of first-season actual",
        "Network committee decisions taken without deferral above 80 percent",
        "Alliance and joint venture position obtained before commitment at 100 percent",
        "New routes reaching contribution target by end of second season above 70 percent"],
  risks=["Committing fleet and capacity two to three seasons ahead on a demand estimate that has no "
         "Air Canada booking history behind it",
         "Joint venture partners blocking or diluting a transatlantic case after commercial work is complete",
         "Slot unavailability at the required timing turning a viable route into an unviable one",
         "Connecting contribution assumptions failing because the bank structure changes before launch",
         "Crew base and line-station cost surfacing after approval and inverting a marginal case"],
  extra_systems=["Star Alliance Interline", "SAP Analytics Cloud"])

P("AC-NP-SP-02",
  desc="The seasonal schedule is constructed in NetLine Plan from the committed long-range plan, resolving "
       "frequency, timing, fleet assignment and rotation feasibility into a schedule that can actually be "
       "flown, crewed and maintained.",
  trig="The seasonal planning cycle opens for a Northern Summer or Northern Winter season, typically eleven "
       "to twelve months before the season starts.",
  out="A committed seasonal schedule with feasible aircraft rotations, ready for slot filing, alliance "
      "coordination and publication.",
  note="Seasonal build is where the plan meets physical reality. NetLine Plan has to reconcile four "
       "constraints that pull in different directions: revenue wants peak-time departures, the connecting "
       "bank wants coordinated arrival and departure waves, maintenance wants overnight ground time at a "
       "base, and crew wants pairings that close legally at a crew base. Air Canada runs this across "
       "mainline, Rouge and the Express operators, which means three operating models on one schedule.",
  phases=["Baseline and demand shaping", "Constraint resolution", "Schedule freeze and handover"],
  steps=[
    S("1.1","Roll forward the prior season baseline","Schedule Planner","NetLine/Plan",
      "Prior equivalent season and long-range plan","Draft baseline schedule",
      "Baseline available at cycle open at 100 percent","N","N",
      "The prior season carries forward compromises whose original reason is undocumented"),
    S("1.2","Apply committed network changes","Schedule Planner","NetLine/Plan",
      "Approved route cases and exits","Baseline updated with committed changes",
      "All committed changes applied before demand shaping","N","N",
      "Late-approved route cases arrive after the baseline is already being optimised"),
    S("1.3","Shape frequency and timing to demand","Network Planning Analyst","PROS Revenue Management",
      "O and D demand forecast by day of week","Frequency and timing proposal",
      "Schedule matched to demand profile within 1 frequency on 90 percent of routes","N","N",
      "Demand shaping and connecting bank integrity frequently want different departure times"),
    S("1.4","Design connecting wave structure","Network Planning Analyst","NetLine/Plan",
      "Timing proposal and hub bank definition","Connection wave structure by hub",
      "Connecting itineraries within the target window above 85 percent","N","N",
      "Every timing change made for local demand ripples through the connecting bank"),
    S("2.1","Assign fleet by gauge and range","Fleet Planner","NetLine/Plan",
      "Frequency proposal and fleet availability","Fleet assignment by leg",
      "Fleet assignment feasible on first pass above 80 percent","Y","N",
      "Fleet renewal means the available fleet in the target season is itself still moving"),
    S("2.2","Build aircraft rotations","Schedule Planner","NetLine/Plan",
      "Fleet assignment and turn time standards","Feasible tail rotations",
      "Rotations feasible without manual intervention above 75 percent","Y","N",
      "Rotation infeasibility is discovered late and forces timing changes back through the bank design"),
    S("2.3","Embed maintenance opportunity","Technical Services Planner","TRAX",
      "Draft rotations and maintenance requirement","Rotations with protected maintenance ground time",
      "Maintenance opportunity protected on 100 percent of tails","Y","N",
      "Maintenance ground time is the first thing traded away when the schedule is tight"),
    S("2.4","Validate crew pairing feasibility","Crew Planning Liaison","Jeppesen Crew",
      "Draft schedule","Pairing feasibility assessment with cost estimate",
      "Schedule pairs within crew cost budget above 90 percent","Y","N",
      "Crew cost consequences of a timing decision are not visible inside the scheduling tool"),
    S("2.5","Allocate Rouge and Express operating capacity","Schedule Planner","Lufthansa Systems NetLine",
      "Committed schedule and operator agreements","Legs assigned to mainline, Rouge or Express",
      "Operator allocation complete before freeze at 100 percent","N","N",
      "Express operator capacity is contractually bounded and cannot flex late in the cycle"),
    S("3.1","Resolve residual infeasibility","Schedule Planner","NetLine/Plan",
      "Constraint violation list","Resolved schedule or accepted exception",
      "Residual infeasible legs at freeze below 1 percent","N","Y",
      "Late resolution is manual and trades one constraint for another without visibility of the cost"),
    S("3.2","Freeze the seasonal schedule","Network Strategy Manager","NetLine/Plan",
      "Resolved schedule","Frozen seasonal schedule",
      "Schedule frozen on the published cycle date at 100 percent","Y","N",
      "Freeze slips when a single route case is unresolved, delaying every downstream function"),
    S("3.3","Hand over to slot filing and publication","Schedule Planner","Lufthansa Systems NetLine",
      "Frozen schedule","Schedule released to slot coordination and publication",
      "Handover within 2 business days of freeze","N","N",
      "Post-freeze changes still occur and each one re-triggers slot and publication work"),
  ],
  kpis=["Seasonal schedule frozen on the published cycle date at 100 percent",
        "Aircraft rotations feasible without manual intervention above 75 percent",
        "Maintenance opportunity protected on 100 percent of tails at freeze",
        "Connecting itineraries within the target window above 85 percent",
        "Schedule pairs within the crew cost budget above 90 percent"],
  risks=["Maintenance ground time traded away under schedule pressure, converting a planning decision "
         "into a downstream airworthiness and AOG risk",
         "Crew cost consequences invisible during build and surfacing only at pairing",
         "Fleet availability moving during fleet renewal after fleet assignment is complete",
         "Freeze slipping and compressing slot filing, alliance coordination and publication",
         "Local demand shaping degrading the connecting bank that carries Sixth Freedom traffic"],
  extra_systems=["Amadeus Altea Inventory", "Databricks Lakehouse"])

P("AC-NP-SP-03",
  desc="Toronto Pearson is designed as a connecting hub for Sixth Freedom traffic, carrying passengers "
       "between the United States and Europe or Asia over Canada. Bank design sets the arrival and departure "
       "waves so that these itineraries connect within a competitive elapsed time.",
  trig="A seasonal schedule build reaches bank design, or connecting performance degrades enough in service "
       "to trigger a structural review.",
  out="A defined bank structure at Toronto with arrival and departure waves, minimum connect times by "
      "itinerary type, and a validated set of sellable connecting itineraries.",
  note="This process is where Air Canada's network strategy is actually implemented. Sixth Freedom "
       "connecting traffic over Toronto is a core part of the airline's economics, and it only exists if "
       "the bank works: a transborder arrival wave has to land far enough ahead of the transatlantic "
       "departure wave to clear connections including customs and security, but not so far ahead that the "
       "elapsed journey stops competing with a direct routing or a US hub. Every minute of bank slack is "
       "revenue on one side and aircraft utilisation on the other.",
  phases=["Bank structure definition", "Connection feasibility validation", "Commitment and monitoring"],
  steps=[
    S("1.1","Define target connecting markets","Network Planning Analyst","Databricks Lakehouse",
      "O and D demand by connecting market","Prioritised connecting market list",
      "Top 50 connecting markets identified before bank design","N","N",
      "Connecting market value competes directly with local Toronto demand for the same timings"),
    S("1.2","Set arrival and departure wave windows","Network Planning Analyst","NetLine/Plan",
      "Target markets and long-haul departure requirements","Defined bank windows by time of day",
      "Bank windows defined for all long-haul departure waves","Y","N",
      "Wave windows are constrained by night curfews and slot availability at the far end"),
    S("1.3","Establish minimum connect times by itinerary type","Network Planning Analyst","Amadeus Altea Inventory",
      "Terminal layout and border processing times","Minimum connect time matrix",
      "Minimum connect times validated against actual transfer performance annually","Y","N",
      "Transborder and international connections cross border controls with variable processing time"),
    S("1.4","Model bank capacity against infrastructure","Schedule Planner","NetLine/Plan",
      "Bank windows and available stands","Bank capacity assessment by wave",
      "Peak wave within available stand and gate capacity at 100 percent","Y","N",
      "Peak wave demand exceeds contact stand availability, pushing aircraft to remote positions"),
    S("2.1","Generate candidate connecting itineraries","Network Planning Analyst","NetLine/Plan",
      "Draft schedule and connect time matrix","Candidate connecting itinerary set",
      "Candidate itineraries generated for 100 percent of target markets","N","N",
      "Itinerary generation does not weight the connection by its actual reliability"),
    S("2.2","Test elapsed journey competitiveness","Network Planning Analyst","Databricks Lakehouse",
      "Candidate itineraries and competitor routings","Competitiveness assessment by market",
      "Elapsed time competitive against the best alternative on 80 percent of target markets","Y","N",
      "A US hub alternative frequently offers a shorter elapsed journey on the same market"),
    S("2.3","Validate transfer feasibility with ground operations","Schedule Planner","Amadeus Altea DCS",
      "Candidate connections and terminal transfer routes","Ground-validated connection set",
      "Ground operations validate 100 percent of sub-90-minute connections","Y","N",
      "Bag transfer feasibility at tight connections is assessed separately from passenger transfer"),
    S("2.4","Assess baggage transfer capacity in the peak","Schedule Planner","Baggage Reconciliation System",
      "Peak wave connection volume","Baggage transfer capacity assessment",
      "Peak transfer bag volume within sortation capacity at 100 percent","N","N",
      "Bag transfer is the binding constraint on tight connections more often than passenger walk time"),
    S("2.5","Resolve infeasible connections","Schedule Planner","NetLine/Plan",
      "Failed feasibility list","Adjusted timings or withdrawn connections",
      "Infeasible connections removed before publication at 100 percent","N","Y",
      "Withdrawing a connection removes revenue that the route case already counted"),
    S("3.1","Commit bank structure to the schedule","Network Strategy Manager","NetLine/Plan",
      "Validated bank design","Committed bank structure in the seasonal schedule",
      "Bank structure committed before schedule freeze at 100 percent","Y","N",
      "Committing the bank constrains every subsequent timing change in the season"),
    S("3.2","Publish sellable connections to inventory","Schedule Planner","Amadeus Altea Inventory",
      "Validated connecting itinerary set","Connections available for sale",
      "Sellable connections match the validated set at 100 percent","N","N",
      "Inventory can construct connections that were never ground-validated"),
    S("3.3","Monitor connection performance in service","Network Planning Analyst","Databricks Lakehouse",
      "Actual misconnect and transfer data","Bank performance report with structural findings",
      "Misconnect rate on target connections below 3 percent","N","N",
      "Structural findings arrive too late in the season to act on and are often lost by the next cycle"),
  ],
  kpis=["Misconnect rate on target connecting markets below 3 percent",
        "Elapsed journey competitive against the best alternative on 80 percent of target markets",
        "Peak wave within available stand and gate capacity at 100 percent",
        "Ground operations validation on 100 percent of sub-90-minute connections",
        "Sellable connections matching the ground-validated set at 100 percent"],
  risks=["Inventory constructing and selling connections that ground operations never validated, "
         "producing systematic misconnects on a specific itinerary",
         "Baggage sortation capacity binding in the peak wave and driving mishandled bag volume",
         "Bank slack tuned for connection reliability at the cost of aircraft utilisation, or the reverse",
         "Border processing time variability invalidating the minimum connect time matrix in practice",
         "Peak wave exceeding contact stand availability and extending transfer times beyond the model"],
  extra_systems=["Lufthansa Systems NetLine", "Star Alliance Interline"])

P("AC-NP-SP-04",
  desc="Montreal and Vancouver operate as hubs with different roles from Toronto: Montreal carries "
       "transatlantic and francophone-market traffic, Vancouver carries transpacific traffic. Bank design "
       "for each sets wave structure appropriate to its geography and traffic mix.",
  trig="Seasonal schedule build reaches hub design for Montreal or Vancouver, or a change in transpacific "
       "or transatlantic capacity requires the bank to be restructured.",
  out="Defined bank structures at Montreal and Vancouver with wave timings, connect time standards and "
      "validated connecting itineraries appropriate to each hub's role.",
  note="Montreal and Vancouver are not smaller copies of Toronto. Vancouver's transpacific departure wave "
       "is set by Asian arrival curfews and by the very long sectors involved, which compresses the "
       "feasible departure window. Montreal serves both transatlantic connecting traffic and a distinct "
       "francophone origin and destination market, which competes for the same peak timings. Treating "
       "either hub as a Toronto template produces a bank that fits neither the geography nor the traffic.",
  phases=["Hub role definition", "Wave design and validation", "Commitment and review"],
  steps=[
    S("1.1","Define the role of each hub in the network","Network Strategy Manager","NetLine/Plan",
      "Network strategy and traffic mix analysis","Documented hub role and traffic priority",
      "Hub roles reviewed and confirmed each planning cycle","N","N",
      "Hub roles drift over time without an explicit review, so the bank stops matching the traffic"),
    S("1.2","Analyse local versus connecting traffic mix","Network Planning Analyst","Databricks Lakehouse",
      "O and D traffic by hub","Local and connecting split by time of day",
      "Traffic mix analysis completed before wave design","N","N",
      "Montreal local francophone demand and transatlantic connecting demand want the same departure slots"),
    S("1.3","Identify geography-driven timing constraints","Network Planning Analyst","NetLine/Plan",
      "Sector lengths and destination curfews","Feasible departure window by region",
      "Timing constraints documented for 100 percent of long-haul regions","Y","N",
      "Transpacific departure windows from Vancouver are tightly bounded by arrival curfews in Asia"),
    S("1.4","Set hub-specific minimum connect times","Network Planning Analyst","Amadeus Altea Inventory",
      "Terminal configuration and border processing","Minimum connect time matrix per hub",
      "Connect times validated against actual transfer performance annually","N","N",
      "Applying Toronto connect standards to a differently configured terminal produces unachievable connections"),
    S("2.1","Design arrival and departure waves","Schedule Planner","NetLine/Plan",
      "Traffic mix and timing constraints","Wave structure per hub",
      "Wave structure defined for both hubs before schedule freeze","Y","N",
      "A single long-haul departure wave leaves the rest of the day poorly utilised at a smaller hub"),
    S("2.2","Balance local demand against connecting waves","Network Planning Analyst","PROS Revenue Management",
      "Local demand profile and wave structure","Balanced timing proposal",
      "Local demand served within 30 minutes of preferred timing on 75 percent of routes","Y","N",
      "Serving connecting waves well can push local departures to commercially poor times"),
    S("2.3","Validate stand and terminal capacity","Schedule Planner","Airport Resource Management",
      "Wave structure and available infrastructure","Capacity-validated wave structure",
      "Peak wave within stand capacity at both hubs at 100 percent","Y","N",
      "Peak capacity at the secondary hubs is tighter than at Toronto relative to wave size"),
    S("2.4","Generate and test connecting itineraries","Network Planning Analyst","NetLine/Plan",
      "Wave structure and connect time matrix","Validated connecting itinerary set per hub",
      "Connecting itineraries validated for 100 percent of target markets","N","N",
      "Cross-hub itineraries via two Air Canada hubs are generated but rarely tested for reliability"),
    S("2.5","Assess Rouge and Express feed into the banks","Schedule Planner","Lufthansa Systems NetLine",
      "Regional feed schedule","Feed assessment against wave windows",
      "Regional feed aligned to wave windows on 85 percent of connections","N","N",
      "Express operator feed reliability is materially different from mainline and is not modelled separately"),
    S("3.1","Commit hub bank structures","Network Strategy Manager","NetLine/Plan",
      "Validated wave structures","Committed bank structures for both hubs",
      "Bank structures committed before schedule freeze at 100 percent","Y","N",
      "Committing both secondary hubs late compresses the Toronto bank design that depends on them"),
    S("3.2","Release connections to inventory","Schedule Planner","Amadeus Altea Inventory",
      "Validated itinerary set","Sellable connections per hub",
      "Sellable connections match the validated set at 100 percent","N","N",
      "Connection construction rules are set once and not differentiated by hub reliability"),
    S("3.3","Review hub performance against role","Network Planning Analyst","Databricks Lakehouse",
      "In-service traffic and misconnect data","Hub performance review with structural findings",
      "Hub review completed within 60 days of season end","N","N",
      "Findings are produced after the next season is already frozen"),
  ],
  kpis=["Peak wave within stand capacity at both hubs at 100 percent",
        "Regional feed aligned to wave windows on 85 percent of connections",
        "Local demand served within 30 minutes of preferred timing on 75 percent of routes",
        "Misconnect rate at secondary hubs below 4 percent",
        "Hub performance review completed within 60 days of season end"],
  risks=["Applying a Toronto bank template to hubs whose geography and traffic mix differ materially",
         "Transpacific departure windows at Vancouver being over-constrained by destination curfews",
         "Montreal local francophone demand and transatlantic connecting demand contending for the same peak",
         "Express operator feed reliability degrading connections that were modelled on mainline performance",
         "Hub performance findings arriving after the next season has already been frozen"],
  extra_systems=["Star Alliance Interline", "Amadeus Altea DCS"])

P("AC-NP-SP-05",
  desc="The frozen schedule is published to the industry in IATA SSIM format and loaded into inventory so "
       "it becomes sellable. Publication reaches global distribution systems, alliance partners, airports "
       "and the direct channels.",
  trig="A schedule freeze completes, or a post-freeze schedule change requires republication to the market.",
  out="A schedule visible and sellable in every distribution channel, consistent across inventory, the GDS "
      "estate, alliance partners and aircanada.com.",
  note="Publication is the point at which a planning decision becomes a public commitment. The mechanics "
       "are unglamorous and load-bearing: SSIM files and IATA Type-B messaging still carry schedule change "
       "across the industry, and a schedule that is inconsistent between inventory and the GDS estate "
       "produces bookings Air Canada cannot honour. Post-freeze changes are the main source of that "
       "inconsistency, because each one has to propagate through every channel in the same cycle.",
  phases=["Publication preparation", "Distribution", "Consistency assurance"],
  steps=[
    S("1.1","Extract the frozen schedule","Schedule Publication Analyst","Lufthansa Systems NetLine",
      "Frozen seasonal schedule","SSIM-format schedule extract",
      "Extract produced within 1 business day of freeze","N","N",
      "Post-freeze changes mean the extract is often already stale when it is produced"),
    S("1.2","Validate schedule data quality","Schedule Publication Analyst","Lufthansa Systems NetLine",
      "Schedule extract","Validated extract with exception list",
      "Data quality exceptions below 0.5 percent of legs","Y","N",
      "Validation catches format errors but not commercially wrong timings"),
    S("1.3","Apply codeshare and operating carrier designations","Alliance Manager","Star Alliance Interline",
      "Validated extract and codeshare agreements","Schedule with correct operating and marketing carriers",
      "Codeshare designations correct at publication at 100 percent","Y","N",
      "Operating carrier designation for Express-operated legs is a recurring source of error"),
    S("1.4","Confirm slot alignment before publication","Slot Coordinator","NetLine/Plan",
      "Schedule extract and held slots","Slot-aligned schedule or exception list",
      "Published timings match held slots at 100 percent","Y","N",
      "Publishing a timing not backed by a slot creates an obligation that cannot be met"),
    S("2.1","Load schedule to inventory","Schedule Publication Analyst","Amadeus Altea Inventory",
      "Validated schedule","Schedule loaded and sellable",
      "Inventory load completed within the publication window at 100 percent","N","N",
      "Load failures are detected by exception report rather than at the point of load"),
    S("2.2","Distribute SSIM to the industry","Schedule Publication Analyst","IATA Type-B Messaging",
      "SSIM schedule file","Schedule distributed to GDS and industry recipients",
      "SSIM distributed on the published schedule at 100 percent","N","N",
      "Recipients process on their own cycles, so market visibility lags publication unevenly"),
    S("2.3","Notify alliance and joint venture partners","Alliance Manager","Star Alliance Interline",
      "Published schedule","Partner schedule notification",
      "Partners notified within 2 business days of publication","N","N",
      "Partner notification is a separate manual step from industry distribution"),
    S("2.4","Publish to direct channels","Schedule Publication Analyst","aircanada.com",
      "Loaded inventory","Schedule visible on web and mobile",
      "Direct channels reflect published schedule within 4 hours","N","N",
      "Direct channels can show a schedule the GDS estate has not yet processed"),
    S("3.1","Reconcile inventory against published schedule","Schedule Publication Analyst","Amadeus Altea Inventory",
      "Published schedule and loaded inventory","Reconciliation with variance list",
      "Inventory to schedule variance below 0.1 percent of legs","Y","N",
      "Reconciliation is periodic, so a variance can be sellable for hours before detection"),
    S("3.2","Verify GDS and NDC channel consistency","Schedule Publication Analyst","Sabre GDS",
      "Published schedule","Channel consistency confirmation",
      "Channel consistency verified within 24 hours of publication","N","N",
      "Each distribution channel has to be checked separately with no consolidated view"),
    S("3.3","Handle post-publication schedule change","Schedule Publication Analyst","Lufthansa Systems NetLine",
      "Approved schedule change","Republished schedule across all channels",
      "Schedule changes republished to all channels within 24 hours","N","Y",
      "Each change re-triggers the full distribution chain and is the main source of channel divergence"),
    S("3.4","Trigger passenger re-protection where required","Customer Re-protection Analyst","Amadeus Passenger Recovery",
      "Schedule change affecting booked passengers","Re-protection instruction issued",
      "Affected passengers re-protected within 48 hours of the change","N","N",
      "Identifying affected bookings depends on the change being coded correctly at source"),
  ],
  kpis=["SSIM distributed on the published schedule at 100 percent",
        "Inventory to published schedule variance below 0.1 percent of legs",
        "Codeshare and operating carrier designations correct at publication at 100 percent",
        "Schedule changes republished to all channels within 24 hours",
        "Published timings matching held slots at 100 percent"],
  risks=["Schedule inconsistency between inventory and the GDS estate producing bookings that cannot be honoured",
         "Publishing a timing not backed by a held slot, creating an unmeetable obligation",
         "Operating carrier misdesignation on Express-operated legs, which also misdirects regulatory "
         "responsibility for the flight",
         "Post-freeze changes propagating unevenly and leaving channels divergent",
         "Re-protection missed because a schedule change was coded incorrectly at source"],
  extra_systems=["Amadeus Altea Reservations", "A++ Atlantic Joint Venture"])

P("AC-NP-SP-06",
  desc="Codeshare and interline schedules are aligned with Star Alliance members and the A++ transatlantic "
       "joint venture partners so that connecting itineraries are constructible, sellable and operationally "
       "achievable across carriers.",
  trig="A seasonal schedule is published, a partner announces a schedule change, or a new codeshare route "
       "is agreed and needs to be established.",
  out="Aligned schedules with agreed codeshare designations, constructible interline connections and "
      "correctly filed marketing and operating carrier data across both carriers.",
  note="Air Canada sits inside two overlapping partnership structures with different mechanics. Star "
       "Alliance provides broad interline, through-check and status recognition across 26 members. The A++ "
       "transatlantic joint venture with United, Lufthansa Group, Austrian, SWISS and Brussels goes further: "
       "it involves coordinated schedules and revenue sharing, which means transatlantic timing decisions "
       "are made jointly. A schedule change that is unilaterally optimal can be jointly unacceptable.",
  phases=["Schedule exchange and analysis", "Alignment negotiation", "Filing and validation"],
  steps=[
    S("1.1","Exchange schedules with partner carriers","Alliance Manager","Star Alliance Interline",
      "Published Air Canada schedule","Partner schedules received and loaded",
      "Partner schedules exchanged within 5 business days of publication","N","N",
      "Partners publish on different cycles, so a complete picture is rarely available at one time"),
    S("1.2","Identify connection opportunities and losses","Network Planning Analyst","NetLine/Plan",
      "Combined schedules","Connection opportunity and loss list",
      "Connection changes identified within 5 business days of exchange","N","N",
      "Connection analysis across 26 members is only performed for priority partners in practice"),
    S("1.3","Assess joint venture capacity position","Alliance Manager","A++ Atlantic Joint Venture",
      "Combined transatlantic schedules","Joint venture capacity assessment",
      "JV capacity position assessed each season at 100 percent","Y","N",
      "Joint venture coordination operates on its own governance cycle, not Air Canada's planning cycle"),
    S("1.4","Quantify revenue impact of misalignment","Revenue Management Analyst","PROS Revenue Management",
      "Lost and gained connections","Revenue impact assessment by market",
      "Revenue impact quantified for all priority connection changes","N","N",
      "Interline connection value is hard to attribute and is generally estimated rather than measured"),
    S("2.1","Propose alignment changes to partners","Alliance Manager","Star Alliance Interline",
      "Impact assessment","Alignment proposal issued to partners",
      "Proposals issued within 10 business days of analysis","N","N",
      "Air Canada is not always the party with leverage to move a timing"),
    S("2.2","Negotiate joint venture timing decisions","Alliance Manager","A++ Atlantic Joint Venture",
      "Alignment proposal and JV governance position","Agreed transatlantic timings",
      "JV timing agreement reached before the filing deadline at 100 percent","Y","N",
      "Joint decisions take longer than the schedule filing calendar allows"),
    S("2.3","Escalate unresolved misalignment","Network Strategy Manager","Star Alliance Interline",
      "Unresolved connection loss","Escalated position or accepted loss",
      "Escalations resolved before schedule filing at 80 percent","N","Y",
      "Accepting a connection loss removes revenue that the seasonal plan already counted"),
    S("2.4","Update own schedule where agreed","Schedule Planner","NetLine/Plan",
      "Agreed alignment changes","Updated Air Canada schedule",
      "Agreed changes applied within 5 business days","N","N",
      "Late alignment changes re-open rotation and crew feasibility already signed off"),
    S("3.1","File codeshare designations","Alliance Manager","Star Alliance Interline",
      "Agreed codeshare routes","Filed marketing and operating carrier designations",
      "Codeshare filings complete before the season opens at 100 percent","N","N",
      "Designations must be filed consistently by both carriers or the itinerary fails to construct"),
    S("3.2","Validate interline connection construction","Network Planning Analyst","Amadeus Altea Inventory",
      "Filed schedules and designations","Validated constructible connections",
      "Priority interline connections constructible at 100 percent","Y","N",
      "A connection can be schedule-feasible but fail to construct due to a filing mismatch"),
    S("3.3","Confirm through-check and baggage feasibility","Schedule Planner","IATA Type-B Messaging",
      "Validated connections","Through-check and baggage agreement confirmation",
      "Through-check available on 95 percent of published interline connections","N","N",
      "Through-check depends on airport-level agreements that vary by station"),
    S("3.4","Monitor partner schedule changes in season","Alliance Manager","Star Alliance Interline",
      "Partner schedule change notifications","Impact assessment and response",
      "Partner changes assessed within 3 business days of notification","N","N",
      "In-season partner changes arrive continuously and break connections already sold"),
  ],
  kpis=["Codeshare filings complete before the season opens at 100 percent",
        "Priority interline connections constructible at 100 percent",
        "Joint venture timing agreement reached before the filing deadline at 100 percent",
        "Through-check available on 95 percent of published interline connections",
        "Partner schedule changes assessed within 3 business days of notification"],
  risks=["Joint venture governance cycles running slower than the schedule filing calendar",
         "Codeshare designation mismatch between carriers preventing an otherwise valid itinerary from constructing",
         "In-season partner schedule changes breaking connections that are already sold",
         "Connection losses accepted late, removing revenue the seasonal plan already counted",
         "Through-check unavailable at specific stations, degrading a connection that was sold as seamless"],
  extra_systems=["Amadeus Altea Reservations", "Lufthansa Systems NetLine"])

P("AC-NP-SP-07",
  desc="Air Canada Rouge operates leisure routes under a separate air operator certificate with a different "
       "cabin configuration and cost structure. Its schedule is integrated with the mainline plan so that "
       "capacity is placed on the right operating platform without breaking connectivity.",
  trig="Seasonal schedule build reaches operator allocation, or a route's seasonal demand profile shifts "
       "enough to justify moving it between mainline and Rouge.",
  out="An integrated schedule with each leg allocated to the appropriate operating platform, with cabin "
      "configuration, connectivity and crew implications resolved.",
  note="Rouge shares the mainline IT backbone but runs a distinct operational configuration: separate air "
       "operator certificate, different cabin product and a different crew cost base. That creates a real "
       "process seam. Product and fare configuration diverge on a shared passenger service system, so a "
       "passenger connecting from a mainline flight onto a Rouge flight experiences two products under one "
       "brand. Rouge was also swept up in the June 2023 mainline outage, which is a reminder that "
       "operational separation does not imply IT independence.",
  phases=["Allocation assessment", "Configuration and connectivity", "Integration and commitment"],
  steps=[
    S("1.1","Assess route demand and product fit","Network Planning Analyst","Databricks Lakehouse",
      "Route demand profile and passenger mix","Leisure or mainline product fit assessment",
      "Product fit assessed for 100 percent of candidate routes","Y","N",
      "Routes with mixed business and leisure demand fit neither platform cleanly"),
    S("1.2","Compare operating economics by platform","Revenue Management Analyst","PROS Revenue Management",
      "Cost base and revenue projection by platform","Comparative economics by operating platform",
      "Platform allocation supported by economics on 100 percent of decisions","Y","N",
      "Comparative economics ignore the connectivity value that a mainline product carries"),
    S("1.3","Confirm Rouge fleet and certificate coverage","Fleet Planner","NetLine/Plan",
      "Rouge fleet availability and route requirements","Feasible Rouge allocation",
      "Rouge allocation feasible within available fleet at 100 percent","Y","N",
      "Rouge fleet is finite, so allocation is a zero-sum choice between leisure routes"),
    S("1.4","Assess seasonal switching requirement","Schedule Planner","NetLine/Plan",
      "Seasonal demand variation","Seasonal platform switching plan",
      "Seasonal switches identified before schedule freeze at 100 percent","N","N",
      "Switching platform between seasons disrupts crew basing and product expectations"),
    S("2.1","Configure cabin product and fare families","Revenue Management Analyst","Amadeus Altea Inventory",
      "Platform allocation","Cabin and fare configuration by leg",
      "Configuration correct at first publication above 95 percent","Y","N",
      "Product divergence on a shared PSS is a recurring source of misconfigured legs"),
    S("2.2","Validate connectivity onto mainline banks","Network Planning Analyst","NetLine/Plan",
      "Rouge schedule and mainline bank structure","Validated Rouge to mainline connections",
      "Rouge feed aligned to mainline waves on 85 percent of connections","N","N",
      "Rouge timings optimised for leisure demand can miss the mainline connecting wave"),
    S("2.3","Confirm crew basing and certificate compliance","Crew Planning Liaison","Jeppesen Crew",
      "Rouge schedule","Crew basing plan and certificate compliance confirmation",
      "Crew basing feasible for 100 percent of allocated Rouge flying","Y","N",
      "Separate certificate means crew cannot be interchanged with mainline to cover shortfalls"),
    S("2.4","Align maintenance support to the Rouge pattern","Technical Services Planner","TRAX",
      "Rouge rotations","Maintenance support plan",
      "Maintenance opportunity protected on Rouge rotations at 100 percent","N","N",
      "Leisure patterns concentrate flying at times that leave little overnight base ground time"),
    S("3.1","Integrate into the combined seasonal schedule","Schedule Planner","Lufthansa Systems NetLine",
      "Rouge and mainline schedules","Integrated seasonal schedule",
      "Integration complete before schedule freeze at 100 percent","N","N",
      "Rouge is integrated late in the cycle, so its constraints arrive after mainline is settled"),
    S("3.2","Resolve product and connectivity exceptions","Schedule Planner","Amadeus Altea Inventory",
      "Exception list","Resolved configuration or accepted exception",
      "Unresolved product exceptions at freeze below 1 percent","N","Y",
      "Accepted exceptions become customer-visible product inconsistency under one brand"),
    S("3.3","Publish integrated schedule with correct operator","Schedule Publication Analyst","IATA Type-B Messaging",
      "Integrated schedule","Published schedule with correct operating carrier",
      "Operating carrier correct at publication at 100 percent","N","N",
      "Operating carrier designation drives regulatory responsibility and must be exact"),
    S("3.4","Monitor platform allocation performance","Network Planning Analyst","Databricks Lakehouse",
      "In-service performance by platform","Allocation performance review",
      "Allocation review completed within 60 days of season end","N","N",
      "Review compares revenue by platform without isolating the connectivity effect"),
  ],
  kpis=["Platform allocation supported by comparative economics on 100 percent of decisions",
        "Rouge feed aligned to mainline waves on 85 percent of connections",
        "Cabin and fare configuration correct at first publication above 95 percent",
        "Operating carrier correct at publication at 100 percent",
        "Maintenance opportunity protected on Rouge rotations at 100 percent"],
  risks=["Product and fare configuration diverging on a shared passenger service system and reaching the "
         "customer as an inconsistent experience under one brand",
         "Separate air operator certificate preventing crew interchange when either platform is short",
         "Rouge timings optimised for leisure demand missing the mainline connecting wave",
         "Operating carrier misdesignation misdirecting regulatory responsibility for the flight",
         "Rouge integrated late in the planning cycle, so its constraints surface after mainline is settled"],
  extra_systems=["Amadeus Altea Reservations", "Amadeus Altea DCS"])

P("AC-NP-SP-08",
  desc="When a published schedule changes, affected bookings are identified, passengers are re-protected "
       "onto acceptable alternatives, and the change is propagated across every distribution channel. This "
       "covers planned commercial changes rather than day-of-operation disruption.",
  trig="A schedule change is approved after publication, whether a timing shift, frequency change, "
       "equipment change or route withdrawal.",
  out="A republished schedule, every affected passenger re-protected or notified, and the commercial and "
      "regulatory consequences of the change recorded.",
  note="Schedule change is where a planning decision reaches a passenger who has already bought. The "
       "regulatory position matters: a change made far enough ahead is a commercial matter, but a change "
       "close to departure moves toward the Air Passenger Protection Regulations territory, where the "
       "reason for the change and the notice given determine the airline's obligations. The reason code "
       "attached to a schedule change is therefore not administrative metadata, it is the input to a "
       "later entitlement determination.",
  phases=["Change assessment", "Passenger re-protection", "Propagation and closure"],
  steps=[
    S("1.1","Register the approved schedule change","Schedule Planner","Lufthansa Systems NetLine",
      "Approved change request","Registered change with effective date",
      "Changes registered within 1 business day of approval","N","N",
      "Changes arrive from several sources and are not always registered before being actioned"),
    S("1.2","Classify change type and notice period","Network Planning Analyst","Lufthansa Systems NetLine",
      "Change details and departure date","Change classification with notice period",
      "Change classified before passenger action at 100 percent","Y","N",
      "Classification determines the regulatory position and is applied inconsistently"),
    S("1.3","Identify affected bookings","Customer Re-protection Analyst","Amadeus Altea Reservations",
      "Change scope and effective date","Affected passenger and booking list",
      "Affected bookings identified within 24 hours of registration","N","N",
      "Connecting and interline itineraries are harder to identify than point to point bookings"),
    S("1.4","Assess connecting and interline impact","Network Planning Analyst","Star Alliance Interline",
      "Affected booking list","Broken connection assessment",
      "Broken connections identified for 100 percent of affected itineraries","Y","N",
      "Partner-operated onward legs are not visible in the same view as Air Canada legs"),
    S("2.1","Determine re-protection options","Customer Re-protection Analyst","Amadeus Passenger Recovery",
      "Affected bookings and available capacity","Re-protection option set by passenger",
      "Acceptable option available for 95 percent of affected passengers","Y","N",
      "Re-protection competes for the same seats that are still being sold"),
    S("2.2","Apply re-protection rules and priority","Customer Re-protection Analyst","Amadeus Passenger Recovery",
      "Option set and passenger status","Prioritised re-protection assignment",
      "Re-protection applied within 48 hours of change registration","N","N",
      "Priority rules balance status, fare paid and connection complexity with limited automation"),
    S("2.3","Handle passengers with no acceptable option","Customer Re-protection Analyst","Salesforce Service Cloud",
      "Unresolved passenger list","Refund, partner rebooking or negotiated alternative",
      "Unresolved passengers below 1 percent of those affected","N","Y",
      "These cases go to the contact centre and become the seed of later complaints"),
    S("2.4","Notify affected passengers","Customer Re-protection Analyst","Air Canada Mobile App",
      "Re-protection assignment","Bilingual notification of the change and new itinerary",
      "Passengers notified within 24 hours of re-protection","N","N",
      "Notification must be produced in English and French and is assembled per change type"),
    S("3.1","Republish the schedule to all channels","Schedule Publication Analyst","IATA Type-B Messaging",
      "Registered change","Republished schedule across distribution",
      "All channels reflect the change within 24 hours","N","N",
      "Each change re-triggers the full distribution chain and channels update unevenly"),
    S("3.2","Update inventory and reopen for sale","Schedule Publication Analyst","Amadeus Altea Inventory",
      "Republished schedule","Updated sellable inventory",
      "Inventory consistent with the change within 4 hours","N","N",
      "Selling the changed flight before re-protection completes creates a second conflict for the same seats"),
    S("3.3","Record the change reason for regulatory use","Network Planning Analyst","Salesforce Service Cloud",
      "Change classification","Reason recorded and available to customer relations",
      "Reason recorded for 100 percent of changes inside the regulated window","N","N",
      "A commercially framed reason can read very differently when tested against APPR"),
    S("3.4","Close the change and report the impact","Schedule Planner","Lufthansa Systems NetLine",
      "Completed re-protection and republication","Closed change record with impact summary",
      "Changes closed within 5 business days of effective date","N","N",
      "Cumulative change volume across a season is not reported, so the pattern stays invisible"),
  ],
  kpis=["Affected bookings identified within 24 hours of change registration",
        "Acceptable re-protection option available for 95 percent of affected passengers",
        "Passengers notified within 24 hours of re-protection",
        "All distribution channels reflecting the change within 24 hours",
        "Change reason recorded for 100 percent of changes inside the regulated window"],
  risks=["Schedule change reasons recorded for commercial purposes proving indefensible when tested against "
         "the Air Passenger Protection Regulations",
         "Re-protection competing for seats that are still being sold on the changed flight",
         "Connecting and interline passengers missed because partner-operated legs are not visible in one view",
         "Channels updating unevenly and leaving a withdrawn or retimed flight sellable",
         "Cumulative in-season change volume going unreported, so a systemic planning problem stays invisible"],
  extra_systems=["Amadeus Altea DCS", "aircanada.com"])
