# -*- coding: utf-8 -*-
"""AC-RM-IY — Revenue Management and Pricing > Inventory and Yield Control (8 processes)."""
from content_lib import P, S

P("AC-RM-IY-01",
  desc="Origin and destination demand is forecast by flight, date and booking class to drive the bid price "
       "and availability controls PROS pushes into Amadeus Altea Inventory.",
  trig="The nightly revenue management forecast cycle runs, or a material demand shock requires an "
       "off-cycle refresh.",
  out="An updated O and D demand forecast by flight and class, feeding same-night inventory optimisation.",
  note="Forecast quality is the foundation the entire revenue management chain rests on; every optimisation "
       "downstream is only as good as the demand number it is fed.",
  phases=["Data compilation", "Forecast generation", "Validation and release"],
  steps=[
    S("1.1","Compile historical booking curves","Revenue Management Analyst","PROS Revenue Management",
      "Historical booking and show data","Compiled booking curve history",
      "Compiled nightly for 100 percent of active flights","N","N",
      "New routes have no comparable history to build a curve from"),
    S("2.1","Generate baseline demand forecast","Revenue Management Analyst","PROS Revenue Management",
      "Booking curve history and current bookings-on-hand","Baseline forecast by flight and class",
      "Forecast generated nightly for 100 percent of flights within 90 days","N","N",
      "Baseline forecasting struggles on routes with irregular demand patterns such as charter-adjacent markets"),
    S("2.2","Adjust for known demand shocks","Revenue Management Analyst","PROS Revenue Management",
      "Event calendar and known disruptions","Adjusted forecast",
      "Known shocks incorporated before the nightly run at 95 percent","Y","N",
      "Adjustment relies on analysts manually knowing about the event in the first place"),
    S("3.1","Validate forecast against analyst judgement","Revenue Management Analyst","PROS Revenue Management",
      "Generated forecast","Validated or overridden forecast",
      "Material overrides reviewed for cause within 24 hours","N","N",
      "Override volume is not tracked in aggregate, so systemic model weaknesses stay invisible"),
    S("3.2","Release forecast to inventory optimisation","Revenue Management Analyst","Amadeus Altea Inventory",
      "Validated forecast","Forecast available for bid price calculation",
      "Released before the nightly optimisation run at 100 percent","N","N",
      "A late release delays the entire nightly inventory update"),
    S("3.3","Log forecast accuracy for the closed booking window","Revenue Management Analyst","Databricks Lakehouse",
      "Forecast versus actual bookings for departed flights","Logged accuracy record",
      "Accuracy logged for 100 percent of departed flights","N","N",
      "Accuracy logging happens well after the fact and rarely feeds back into model tuning promptly"),
  ],
  kpis=["Forecast generated nightly for 100 percent of flights within 90 days of departure",
        "Forecast accuracy within 15 percent of actual bookings at 30 days out",
        "Known demand shocks incorporated before the nightly run at 95 percent",
        "Released before the nightly optimisation run at 100 percent"],
  risks=["New and thin routes having no comparable booking history to forecast against",
         "Override volume not tracked in aggregate, hiding systemic model weakness",
         "A demand shock missed because no analyst flagged it before the nightly run",
         "A late forecast release delaying the entire nightly inventory optimisation cycle"])

P("AC-RM-IY-02",
  desc="Bid prices and class availability are optimised nightly across the network, translating the demand "
       "forecast into sell or close decisions by class and flight.",
  trig="The nightly optimisation cycle runs following forecast release, or a manual trigger follows a major "
       "inventory event.",
  out="Updated bid prices and open or closed class availability pushed to Amadeus Altea Inventory for "
      "every active flight.",
  note="Bid price optimisation is where the airline decides, in effect, the lowest fare it will accept for "
      "the next seat on every flight in the network, every night.",
  phases=["Optimisation run", "Exception handling", "Distribution"],
  steps=[
    S("1.1","Run network bid price optimisation","Revenue Management Analyst","PROS Revenue Management",
      "Released forecast and current inventory position","Optimised bid prices by flight and class",
      "Optimisation completed within the nightly batch window at 100 percent","N","N",
      "Batch window pressure means a failed run has limited time to be diagnosed and rerun"),
    S("1.2","Calculate class availability from bid prices","Revenue Management Analyst","PROS Revenue Management",
      "Optimised bid prices and fare values","Open or closed class decision by flight",
      "Availability calculated for 100 percent of active flights nightly","N","N",
      "A bid price change close to a fare boundary can flip availability on marginal cases"),
    S("2.1","Review flagged optimisation exceptions","Revenue Management Analyst","PROS Revenue Management",
      "Exception list from the optimisation run","Reviewed and resolved exceptions",
      "Exceptions resolved before the inventory push at 95 percent","N","Y",
      "Exceptions concentrate on the same handful of complex routes every night"),
    S("3.1","Push updated controls to inventory","Revenue Management Analyst","Amadeus Altea Inventory",
      "Resolved optimisation output","Live bid prices and availability in inventory",
      "Push completed before the sales day opens at 100 percent","N","N",
      "A failed push can leave a flight selling against yesterday's controls with no alert"),
    S("3.2","Confirm distribution consistency across channels","Revenue Management Analyst","Sabre GDS",
      "Pushed inventory controls","Confirmed consistent availability across channels",
      "Consistency confirmed within 2 hours of the push at 100 percent","N","N",
      "GDS channel propagation lags the direct channel by an interval that is not consistently measured"),
    S("3.3","Escalate persistent push failures","Revenue Management Analyst","ITSM Platform",
      "Repeated push failure","Escalated incident with recovery plan",
      "Push failures escalated within 30 minutes of the second consecutive failure","N","Y",
      "A recurring push failure on the same route is not distinguished from a one-off outage"),
  ],
  kpis=["Optimisation completed within the nightly batch window at 100 percent",
        "Push completed before the sales day opens at 100 percent",
        "Exceptions resolved before the inventory push at 95 percent",
        "Consistency confirmed across channels within 2 hours of the push"],
  risks=["A failed nightly push leaving a flight selling against stale controls with no automatic alert",
         "GDS channel propagation lagging the direct channel by an unmeasured interval",
         "Optimisation exceptions concentrating on the same complex routes without a structural fix",
         "A bid price near a fare boundary flipping availability in a way that is hard to explain after the fact"])

P("AC-RM-IY-03",
  desc="Overbooking levels and no-show rates are forecast by flight to protect against spoilage from "
       "no-shows while limiting the risk of denied boarding.",
  trig="The nightly overbooking forecast cycle runs as part of the inventory optimisation batch.",
  out="An overbooking authorisation by flight and class that balances spoilage risk against denied boarding "
      "exposure.",
  note="Overbooking sits directly upstream of denied boarding, which is itself a regulated APPR event, so "
      "the forecast is not purely a revenue optimisation, it is also a compliance-adjacent control.",
  phases=["No-show forecasting", "Overbooking calculation", "Authorisation and monitoring"],
  steps=[
    S("1.1","Forecast no-show rate by flight","Revenue Management Analyst","PROS Revenue Management",
      "Historical no-show data by route and day","No-show forecast by flight",
      "Forecast produced nightly for 100 percent of flights","N","N",
      "No-show behaviour differs materially between business and leisure markets on the same route"),
    S("2.1","Calculate overbooking authorisation level","Revenue Management Analyst","PROS Revenue Management",
      "No-show forecast and denied boarding cost","Overbooking level by flight and class",
      "Calculation completed nightly for 100 percent of flights","N","N",
      "Denied boarding cost inputs are not refreshed as often as fare levels change"),
    S("2.2","Flag flights at elevated denied boarding risk","Revenue Management Analyst","PROS Revenue Management",
      "Overbooking level and booking pace","Flagged high-risk flight list",
      "High-risk flights flagged at least 72 hours before departure","Y","N",
      "Risk flags rely on booking pace patterns that can shift sharply in the final 24 hours"),
    S("3.1","Authorise overbooking level to inventory","Revenue Management Analyst","Amadeus Altea Inventory",
      "Calculated level","Authorised overbooking in inventory",
      "Authorisation pushed before the sales day opens at 100 percent","N","N",
      "An authorisation error compounds daily until the next optimisation cycle corrects it"),
    S("3.2","Monitor close-in risk and adjust","Revenue Management Analyst","Amadeus Altea DCS",
      "Near-departure booking position","Adjusted overbooking or hold decision",
      "High-risk flights reviewed within 24 hours of departure at 100 percent","N","Y",
      "Close-in adjustment is manual and depends on an analyst catching the flight in time"),
    S("3.3","Record denied boarding outcomes for model tuning","Revenue Management Analyst","Databricks Lakehouse",
      "Actual denied boarding events","Logged outcome feeding the overbooking model",
      "100 percent of denied boarding events logged with cause","N","N",
      "Outcome logging happens after the regulatory obligation is already triggered, not before"),
  ],
  kpis=["Forecast produced nightly for 100 percent of flights",
        "High-risk flights flagged at least 72 hours before departure",
        "Denied boarding rate within target threshold on 98 percent of departures",
        "High-risk flights reviewed within 24 hours of departure at 100 percent"],
  risks=["Overbooking error compounding daily until the next optimisation cycle corrects it",
         "Denied boarding cost inputs lagging fare-level changes and mispricing the overbooking decision",
         "Close-in risk adjustment depending on manual review catching a flight in time",
         "No-show behaviour differing sharply between business and leisure demand on the same route"])

P("AC-RM-IY-04",
  desc="Group booking requests are evaluated for viability and quoted with terms and pricing appropriate to "
       "block size, lead time and displacement of individual passenger revenue.",
  trig="A group booking enquiry is received through sales or the group desk.",
  out="A quoted group booking with agreed terms, or a documented decline where the group would displace "
      "more revenue than it contributes.",
  note="A group quote is fundamentally a displacement calculation: the group's value has to be weighed "
      "against the individual passenger revenue it will block from the same seats.",
  phases=["Request intake and feasibility", "Displacement evaluation", "Quotation and confirmation"],
  steps=[
    S("1.1","Receive and register group request","Group Sales Coordinator","PROS Revenue Management",
      "Group enquiry with size, dates and routing","Registered group request",
      "Requests registered within 1 business day of receipt","N","N",
      "Enquiries arrive through multiple channels with inconsistent detail"),
    S("1.2","Assess seat availability for the block","Revenue Management Analyst","Amadeus Altea Inventory",
      "Requested block size and dates","Availability assessment",
      "Availability assessed within 2 business days at 100 percent","N","N",
      "Group holds compete directly with individual inventory optimisation for the same seats"),
    S("2.1","Calculate displacement cost","Revenue Management Analyst","PROS Revenue Management",
      "Forecasted individual demand for the affected flights","Displacement cost estimate",
      "Displacement calculated for 100 percent of viable requests","N","N",
      "Displacement estimation on a high-demand flight is highly sensitive to the underlying forecast"),
    S("2.2","Determine minimum acceptable group fare","Revenue Management Analyst","PROS Revenue Management",
      "Displacement cost and group terms","Minimum group fare",
      "Minimum fare set for 100 percent of quoted groups","Y","N",
      "Competitive pressure can push a quote below the calculated minimum without a clear override trail"),
    S("3.1","Issue quotation to the requester","Group Sales Coordinator","Amadeus Altea Reservations",
      "Approved terms and fare","Issued group quotation",
      "Quotations issued within 3 business days of request at 95 percent","N","N",
      "Quote validity windows are not always enforced consistently against a firming deadline"),
    S("3.2","Confirm and hold the group block","Group Sales Coordinator","Amadeus Altea Inventory",
      "Accepted quotation","Confirmed group block in inventory",
      "Blocks confirmed within 1 business day of acceptance at 100 percent","N","N",
      "An unconfirmed hold beyond its deadline still blocks individual inventory unless actively released"),
  ],
  kpis=["Availability assessed within 2 business days at 100 percent",
        "Displacement calculated for 100 percent of viable requests",
        "Quotations issued within 3 business days of request at 95 percent",
        "Confirmed group revenue meeting or exceeding the displacement cost at 90 percent"],
  risks=["Competitive pressure pushing a quote below the calculated minimum without a documented override",
         "An unconfirmed hold blocking individual inventory well past its firming deadline",
         "Displacement estimation on a high-demand flight being highly sensitive to forecast error",
         "Group demand and individual optimisation competing for the same seats with no shared arbitration rule"])

P("AC-RM-IY-05",
  desc="Nightly inventory feeds from PROS to Amadeus Altea are reconciled to confirm every optimisation "
       "decision actually took effect in the system passengers book against.",
  trig="The nightly reconciliation cycle runs after the inventory push completes.",
  out="A confirmed match between the optimisation output and live inventory, with any discrepancy corrected "
      "before the sales day.",
  note="An optimisation decision that does not actually reach inventory is invisible until a booking outcome "
       "looks wrong, by which point the revenue impact has already occurred.",
  phases=["Feed extraction", "Comparison", "Discrepancy resolution"],
  steps=[
    S("1.1","Extract optimisation output","Revenue Management Analyst","PROS Revenue Management",
      "Completed nightly optimisation run","Optimisation output extract",
      "Extract produced immediately after each nightly run at 100 percent","N","N",
      "Extract timing depends on the optimisation run completing within its batch window"),
    S("1.2","Extract live inventory position","Revenue Management Analyst","Amadeus Altea Inventory",
      "Live inventory state","Inventory extract",
      "Extract produced before the sales day opens at 100 percent","N","N",
      "Inventory can change between extraction and comparison if bookings are already occurring"),
    S("2.1","Compare optimisation output to live inventory","Revenue Management Analyst","PROS Revenue Management",
      "Both extracts","Variance report",
      "Comparison completed before the sales day opens at 100 percent","N","N",
      "Comparison logic has to account for legitimate in-flight bookings occurring during the batch window"),
    S("3.1","Investigate and correct discrepancies","Revenue Management Analyst","Amadeus Altea Inventory",
      "Variance report","Corrected inventory or documented cause",
      "Discrepancies corrected within 4 hours of detection at 95 percent","N","Y",
      "Root cause of a feed failure is not always attributable to a single step in the pipeline"),
    S("3.2","Report reconciliation status","Revenue Management Analyst","SAP Analytics Cloud",
      "Corrected position","Daily reconciliation status report",
      "Report issued daily at 100 percent","N","N",
      "Recurring discrepancy patterns are not tracked as a trend across days"),
    S("3.3","Trend discrepancy causes over time","Revenue Management Analyst","Databricks Lakehouse",
      "Daily reconciliation history","Trend report of discrepancy root causes",
      "Trend reviewed monthly at 100 percent","N","N",
      "Without a trend view a recurring pipeline defect is re-diagnosed from scratch each time it appears"),
  ],
  kpis=["Comparison completed before the sales day opens at 100 percent",
        "Discrepancies corrected within 4 hours of detection at 95 percent",
        "Zero flights selling against a materially incorrect control for more than 4 hours",
        "Report issued daily at 100 percent"],
  risks=["An optimisation decision failing to reach live inventory with no automatic alert",
         "Revenue impact from a missed sync only becoming visible after a booking outcome looks wrong",
         "Recurring discrepancy patterns not tracked as a trend across days, hiding a systemic feed issue",
         "Legitimate in-flight bookings during the batch window complicating discrepancy attribution"])

P("AC-RM-IY-06",
  desc="Analysts override system-generated availability where local knowledge or a specific event justifies "
       "a manual intervention outside the standard optimisation.",
  trig="An analyst identifies a case where system output does not reflect a known local factor, or a "
       "commercial request requires a manual availability change.",
  out="A documented, time-bound manual override with a clear rationale and an expiry that returns control to "
      "the system.",
  note="Manual overrides are a necessary release valve, but an override without an expiry becomes a silent, "
      "permanent deviation from the model that nobody remembers to review.",
  phases=["Override justification", "Application", "Expiry and review"],
  steps=[
    S("1.1","Identify the override requirement","Revenue Management Analyst","PROS Revenue Management",
      "Local knowledge or commercial request","Documented override rationale",
      "Rationale documented for 100 percent of overrides","N","N",
      "Informal requests can bypass the documentation step under time pressure"),
    S("1.2","Assess revenue impact of the override","Revenue Management Analyst","PROS Revenue Management",
      "Override rationale and current forecast","Estimated revenue impact",
      "Impact estimated before application for 100 percent of overrides","N","N",
      "Impact estimation for a novel situation has no historical comparable to anchor it"),
    S("2.1","Apply the override with a defined expiry","Revenue Management Analyst","Amadeus Altea Inventory",
      "Assessed override","Applied override with expiry date",
      "100 percent of overrides carry an explicit expiry date","Y","N",
      "An override without an expiry silently persists past the situation that justified it"),
    S("3.1","Monitor override performance against forecast","Revenue Management Analyst","PROS Revenue Management",
      "Applied override","Performance comparison against the counterfactual forecast",
      "Performance reviewed before expiry for 90 percent of material overrides","N","N",
      "The counterfactual, what would have happened without the override, is inherently unmeasurable"),
    S("3.2","Expire and return control to the system","Revenue Management Analyst","Amadeus Altea Inventory",
      "Expiry date reached","Control returned to system optimisation",
      "Zero overrides remaining active past their expiry date","N","N",
      "Expiry is a manual step and is missed when the analyst who set it is unavailable"),
    S("3.3","Audit standing overrides monthly","Revenue Management Analyst","Amadeus Altea Inventory",
      "Full override log","Audit report of standing and expired overrides",
      "Monthly audit covers 100 percent of active overrides","N","N",
      "Without a standing audit, an override with a distant or missing expiry can persist for months unnoticed"),
  ],
  kpis=["100 percent of overrides carry an explicit expiry date",
        "Zero overrides remaining active past their expiry date",
        "Rationale documented for 100 percent of overrides",
        "Performance reviewed before expiry for 90 percent of material overrides"],
  risks=["An override without an expiry silently persisting as a permanent, undocumented deviation",
         "Informal override requests bypassing documentation under commercial time pressure",
         "Expiry depending on the availability of the specific analyst who applied the override",
         "Override revenue impact being fundamentally unmeasurable against an unobservable counterfactual"])

P("AC-RM-IY-07",
  desc="Award seat inventory for Aeroplan redemptions is allocated by flight and class, balancing member "
       "redemption value against the cash revenue the same seats could otherwise generate.",
  trig="The recurring award inventory allocation cycle runs, or a redemption demand spike prompts an "
       "off-cycle review.",
  out="An award seat allocation by flight and class that balances redemption availability against protected "
      "cash revenue.",
  note="Award seats are not free capacity: every seat allocated to redemption is a seat the cash revenue "
      "optimisation does not get to sell, so the two processes are directly in tension by design.",
  phases=["Redemption demand assessment", "Allocation calculation", "Release and monitoring"],
  steps=[
    S("1.1","Assess redemption demand by route","Loyalty Operations Analyst","Aeroplan Platform",
      "Historical and forecast redemption search activity","Redemption demand estimate by route",
      "Demand estimated for 100 percent of routes each cycle","N","N",
      "Redemption search activity does not always convert to an actual booking, overstating true demand"),
    S("2.1","Calculate award allocation against cash protection","Revenue Management Analyst","PROS Revenue Management",
      "Redemption demand and cash revenue forecast","Award allocation by flight and class",
      "Allocation calculated for 100 percent of eligible flights each cycle","N","N",
      "The trade-off between member satisfaction and protected cash revenue has no single objective answer"),
    S("2.2","Set dynamic award pricing tiers","Loyalty Operations Analyst","Aeroplan Platform",
      "Allocation and cash fare position","Dynamic award pricing by flight",
      "Pricing tiers set for 100 percent of allocated flights","N","N",
      "Dynamic award pricing complexity is a recurring source of member confusion and contact volume"),
    S("3.1","Release award inventory to Aeroplan","Loyalty Operations Analyst","Amadeus Altea Inventory",
      "Calculated allocation","Released award availability",
      "Released before the redemption sales window opens at 100 percent","N","N",
      "A release failure shows to the member as no award availability with no visible explanation"),
    S("3.2","Monitor redemption uptake against allocation","Loyalty Operations Analyst","Aeroplan Platform",
      "Redemption booking activity","Uptake report against allocation",
      "Uptake reviewed weekly at 100 percent","N","N",
      "Persistent low uptake on an allocated route is not automatically fed back into the next cycle"),
    S("3.3","Feed uptake trend into the next allocation cycle","Revenue Management Analyst","PROS Revenue Management",
      "Uptake trend report","Adjusted allocation input for the next cycle",
      "Trend incorporated into 100 percent of routes with two consecutive low-uptake cycles","N","N",
      "The feedback loop between uptake and the next allocation is manual rather than systematic"),
  ],
  kpis=["Demand estimated for 100 percent of routes each cycle",
        "Released before the redemption sales window opens at 100 percent",
        "Allocation calculated for 100 percent of eligible flights each cycle",
        "Member redemption satisfaction score maintained above target"],
  risks=["Award seats allocated against protected cash revenue with no single objectively correct trade-off",
         "A release failure appearing to the member as simply no availability, with no diagnostic trail",
         "Redemption search activity overstating true demand and skewing the allocation calculation",
         "Persistent low uptake on an allocated route not feeding back into the next allocation cycle"],
  extra_systems=["SAP Customer Data Cloud"])

P("AC-RM-IY-08",
  desc="Interline and codeshare inventory is controlled so that partner-sold seats on Air Canada-operated "
       "flights are managed within the same optimisation as directly sold inventory.",
  trig="The nightly inventory optimisation cycle runs, incorporating partner sales activity from the prior "
       "day.",
  out="A unified inventory position across direct, GDS, codeshare and interline sales channels, correctly "
      "reflected in the optimisation.",
  note="A codeshare seat sold by a partner and a seat sold directly both draw from the same physical "
      "aircraft, so if either channel is not correctly reflected the optimisation is working from an "
      "incomplete picture of true demand.",
  phases=["Partner sales consolidation", "Unified optimisation input", "Control distribution"],
  steps=[
    S("1.1","Consolidate partner sales activity","Revenue Management Analyst","Star Alliance Interline",
      "Prior day partner booking activity","Consolidated partner sales position",
      "Consolidated before the nightly optimisation run at 100 percent","N","N",
      "Partner sales reporting lags vary by partner and are not all same-day"),
    S("1.2","Reconcile partner sales against operated capacity","Revenue Management Analyst","Amadeus Altea Inventory",
      "Consolidated sales and operated seat map","Reconciled capacity position",
      "Reconciliation completed for 100 percent of codeshare flights nightly","N","N",
      "A partner-side booking error can show as available capacity that does not actually exist"),
    S("2.1","Feed unified position into optimisation","Revenue Management Analyst","PROS Revenue Management",
      "Reconciled capacity position","Unified demand input to nightly optimisation",
      "Unified input feeds 100 percent of codeshare flights each night","N","N",
      "A stale reconciliation feeding the optimisation produces controls based on outdated capacity"),
    S("3.1","Distribute updated controls to partner systems","Revenue Management Analyst","Star Alliance Interline",
      "Optimised controls","Controls distributed to partner booking systems",
      "Distribution completed within 2 hours of the optimisation run at 100 percent","N","N",
      "Distribution latency to a partner system can leave it selling against outdated availability"),
    S("3.2","Monitor cross-channel consistency","Revenue Management Analyst","Sabre GDS",
      "Distributed controls","Consistency confirmation across all channels",
      "Consistency confirmed within 4 hours of distribution at 100 percent","N","N",
      "A codeshare flight can show different availability on the partner's channel than on Air Canada's own"),
    S("3.3","Escalate persistent partner distribution failures","Revenue Management Analyst","Star Alliance Interline",
      "Repeated cross-channel inconsistency","Escalated case to the partner's revenue management team",
      "Persistent cases escalated within 1 business day at 100 percent","N","Y",
      "Resolution depends on the partner's own systems and is outside Air Canada's direct control"),
  ],
  kpis=["Consolidated before the nightly optimisation run at 100 percent",
        "Reconciliation completed for 100 percent of codeshare flights nightly",
        "Distribution completed within 2 hours of the optimisation run at 100 percent",
        "Consistency confirmed across all channels within 4 hours of distribution"],
  risks=["A partner-side booking error showing as available capacity that does not actually exist",
         "Distribution latency leaving a partner system selling against outdated availability",
         "A codeshare flight showing different availability depending on which carrier's channel is checked",
         "Partner sales reporting lags of more than a day feeding a stale position into optimisation"])
