# -*- coding: utf-8 -*-
"""AC-RM-PF (8), AC-RM-AN (7), AC-RM-YM (7) — remaining Revenue Management processes."""
from content_lib import P, S

# ── PF: Pricing and Fare Filing ─────────────────────────────────────────────
P("AC-RM-PF-01",
  desc="New and amended fares are constructed and filed to ATPCO, covering base fare levels, routing and "
       "fare basis codes across the network.",
  trig="A pricing decision requires a new fare or an amendment to an existing filed fare.",
  out="A correctly filed fare visible and sellable across every distribution channel that consumes ATPCO data.",
  note="ATPCO filing is the slowest link in an otherwise fast pricing chain: dynamic pricing can react "
       "within the day, but a filed fare change propagates on ATPCO's distribution cycle.",
  phases=["Fare construction", "Filing and propagation", "Verification"],
  steps=[
    S("1.1","Construct fare basis and rules","Pricing Analyst","ATPCO",
      "Pricing decision and routing requirements","Constructed fare with rules and restrictions",
      "Fares constructed within 1 business day of the pricing decision","N","N",
      "Fare rule construction requires reconciling against every existing fare on the same routing"),
    S("1.2","Validate against existing fare structure","Pricing Analyst","ATPCO",
      "Constructed fare and current filed fares","Validated fare with no unintended conflicts",
      "Validation completed for 100 percent of new filings","Y","N",
      "An unintended conflict with an existing fare is often only discovered after filing"),
    S("2.1","File fare to ATPCO","Pricing Analyst","ATPCO",
      "Validated fare","Filed fare submitted to ATPCO",
      "Filings submitted within the required lead time at 100 percent","N","N",
      "ATPCO processing and effective-date rules constrain how quickly a fare can go live"),
    S("2.2","Confirm propagation to distribution channels","Pricing Analyst","Sabre GDS",
      "Filed fare","Confirmed availability across GDS and direct channels",
      "Propagation confirmed within 24 hours of the effective date at 100 percent","N","N",
      "Channels consume the ATPCO feed on different cycles, so visibility is not simultaneous"),
    S("3.1","Verify correct pricing in test bookings","Pricing Analyst","Amadeus Altea Reservations",
      "Propagated fare","Verified correct pricing outcome",
      "Test bookings verified for 100 percent of material new filings","N","N",
      "Test coverage cannot practically span every fare and routing combination the filing enables"),
    S("3.2","Monitor for booking anomalies post-filing","Pricing Analyst","Amadeus Altea Reservations",
      "Live bookings against the new fare","Anomaly report",
      "Anomalies reviewed within 48 hours of filing effective date","N","N",
      "An anomaly can indicate a pricing error that has already sold seats at the wrong fare"),
  ],
  kpis=["Filings submitted within the required lead time at 100 percent",
        "Propagation confirmed within 24 hours of the effective date at 100 percent",
        "Test bookings verified for 100 percent of material new filings",
        "Fare filing errors caught before material revenue impact above 95 percent"],
  risks=["An unintended conflict with an existing fare only discovered after filing",
         "Channels consuming the ATPCO feed on different cycles, leaving inconsistent visibility",
         "A pricing error selling seats at the wrong fare before an anomaly is caught",
         "Test coverage unable to span every fare and routing combination a new filing enables"])

P("AC-RM-PF-02",
  desc="PROS real-time dynamic pricing models are governed to confirm the willingness-to-pay algorithms "
       "remain aligned with commercial intent and do not drift into unintended pricing behaviour.",
  trig="The recurring model governance review cycle runs, or an anomalous pricing pattern is flagged for "
       "investigation.",
  out="A validated dynamic pricing model operating within approved bounds, with any drift identified and "
      "corrected.",
  note="A dynamic pricing model optimises against the objective it is given, and a subtle misconfiguration "
      "can produce pricing that is locally optimal but commercially wrong before anyone notices.",
  phases=["Model performance review", "Drift investigation", "Governance action"],
  steps=[
    S("1.1","Review model performance against revenue targets","Revenue Management Analyst","PROS Real-Time Dynamic Pricing",
      "Model output and realised revenue","Performance review against target",
      "Reviewed each governance cycle at 100 percent","N","N",
      "Attributing revenue outcome specifically to the pricing model versus demand is inherently imprecise"),
    S("1.2","Screen for anomalous pricing patterns","Revenue Management Analyst","PROS Real-Time Dynamic Pricing",
      "Live pricing output","Flagged anomaly list",
      "Screening run daily at 100 percent","N","N",
      "Anomaly thresholds are tuned to avoid false positives and can miss a genuine slow drift"),
    S("2.1","Investigate flagged anomalies","Revenue Management Analyst","PROS Real-Time Dynamic Pricing",
      "Anomaly flag","Root cause of the pricing anomaly",
      "Root cause identified within 3 business days of flagging","N","Y",
      "Model behaviour is not always fully explainable from the output alone"),
    S("3.1","Approve or constrain model parameters","Revenue Management Analyst","PROS Real-Time Dynamic Pricing",
      "Root cause finding","Approved parameters or applied constraint",
      "Governance decision taken within 5 business days of investigation at 100 percent","Y","N",
      "A constraint applied to fix one anomaly can create an unintended effect elsewhere in the network"),
    S("3.2","Document governance decisions","Revenue Management Analyst","ITSM Platform",
      "Approved decision","Documented governance record",
      "100 percent of governance decisions documented with rationale","N","N",
      "Undocumented parameter changes accumulate and make later model behaviour hard to explain"),
  ],
  kpis=["Screening run daily at 100 percent",
        "Root cause identified within 3 business days of flagging",
        "Governance decision taken within 5 business days of investigation at 100 percent",
        "100 percent of governance decisions documented with rationale"],
  risks=["A subtle model misconfiguration producing locally optimal but commercially wrong pricing",
         "Anomaly thresholds tuned against false positives missing a genuine slow drift",
         "A constraint fixing one anomaly creating an unintended effect elsewhere in the network",
         "Undocumented parameter changes accumulating until model behaviour is no longer explainable"])

P("AC-RM-PF-03",
  desc="Competitive fare positions are monitored and a match or hold decision is made within defined "
       "delegation limits, balancing share protection against margin erosion.",
  trig="A competitor files a fare change on an overlapping route.",
  out="A documented match or hold decision issued within the competitive response window.",
  note="A fare match decision has to be made faster than the full commercial review cycle can run, so "
       "delegated authority within defined limits is what makes a timely response possible at all.",
  phases=["Competitive detection", "Response evaluation", "Decision and filing"],
  steps=[
    S("1.1","Detect competitor fare change","Revenue Management Analyst","Sabre PRISM",
      "Competitor fare filing feed","Detected fare change with route and magnitude",
      "Changes detected within 4 hours of filing at 100 percent","N","N",
      "Detection depends on the competitor filing through channels the monitoring feed actually covers"),
    S("1.2","Assess share and margin impact","Revenue Management Analyst","PROS Revenue Management",
      "Detected change and current position","Impact assessment",
      "Assessed within 1 business day of detection at 100 percent","N","N",
      "Share impact modelling assumes the competitor's new fare actually sells at meaningful volume"),
    S("2.1","Determine match or hold within delegation limits","Revenue Management Analyst","PROS Revenue Management",
      "Impact assessment and delegation authority","Match or hold decision",
      "Decisions within delegated limits made within 1 business day at 90 percent","Y","N",
      "A decision outside delegated limits requires escalation that can outlast the competitive window"),
    S("2.2","Escalate decisions beyond delegated authority","Revenue Management Analyst","PROS Revenue Management",
      "Decision beyond delegation","Escalated decision from senior management",
      "Escalations resolved within 2 business days at 90 percent","N","Y",
      "Escalation delay can mean the competitive window has closed by the time approval arrives"),
    S("3.1","File the match decision","Pricing Analyst","ATPCO",
      "Approved match decision","Filed matching fare",
      "Filed within 1 business day of decision at 100 percent","N","N",
      "A filed match still takes the same ATPCO propagation time as any other fare"),
  ],
  kpis=["Changes detected within 4 hours of filing at 100 percent",
        "Decisions within delegated limits made within 1 business day at 90 percent",
        "Escalations resolved within 2 business days at 90 percent",
        "Competitive response filed within 2 business days of detection at 85 percent"],
  risks=["A decision requiring escalation outlasting the competitive window it was meant to address",
         "Detection missing a competitor change filed through a channel outside the monitoring feed",
         "Share impact modelling assuming a competitor fare sells at a volume it may not actually achieve",
         "A filed match still subject to the same ATPCO propagation delay as any standard fare change"])

P("AC-RM-PF-04",
  desc="Promotional fare campaigns are designed, approved and launched with defined booking and travel "
       "windows, coordinated across pricing, marketing and distribution.",
  trig="A commercial campaign calendar entry comes due, or a tactical promotional opportunity is identified.",
  out="A launched promotional fare campaign with correct fares filed, marketing content live, and defined "
      "start and end dates enforced.",
  note="A promotion that launches with a pricing or system misalignment against its intended terms is "
      "visible to every customer who books it, which makes launch coordination higher stakes than routine "
      "fare filing.",
  phases=["Campaign design", "Cross-functional coordination", "Launch and monitoring"],
  steps=[
    S("1.1","Design campaign fare structure and terms","Pricing Analyst","ATPCO",
      "Campaign objective and target markets","Designed fare structure with booking and travel windows",
      "Design completed within the campaign planning lead time","N","N",
      "Ambitious campaign windows can conflict with realistic ATPCO filing lead times"),
    S("1.2","Obtain commercial approval","Revenue Management Analyst","PROS Revenue Management",
      "Designed campaign and projected impact","Approved campaign",
      "Approval obtained before filing at 100 percent","Y","N",
      "Approval cycles do not always match the marketing team's external launch commitments"),
    S("2.1","File campaign fares","Pricing Analyst","ATPCO",
      "Approved campaign structure","Filed campaign fares",
      "Filed within the required lead time before launch at 100 percent","N","N",
      "A late file forces either a launch delay or a launch without the fare actually live"),
    S("2.2","Coordinate marketing content and channel readiness","Pricing Analyst","aircanada.com",
      "Filed fares and campaign terms","Aligned marketing content across channels",
      "Content live and aligned to filed terms at launch at 100 percent","N","N",
      "Marketing content is produced on a separate timeline from fare filing and can diverge from what actually files"),
    S("3.1","Launch and monitor booking uptake","Revenue Management Analyst","PROS Revenue Management",
      "Live campaign","Uptake report against target",
      "Uptake reviewed daily during the campaign window at 100 percent","N","N",
      "Underperformance mid-campaign is observed but rarely acted on before the campaign ends"),
    S("3.2","Close the campaign and remove expired fares","Pricing Analyst","ATPCO",
      "Campaign end date reached","Expired fares removed from sale",
      "Fares removed within 1 business day of the end date at 100 percent","N","N",
      "A fare left live past its intended end date continues to be booked at the promotional rate"),
  ],
  kpis=["Filed within the required lead time before launch at 100 percent",
        "Content live and aligned to filed terms at launch at 100 percent",
        "Fares removed within 1 business day of the end date at 100 percent",
        "Campaign uptake against target reviewed daily during the campaign window"],
  risks=["Marketing content diverging from what actually files, misleading the customer at the point of sale",
         "A fare left live past its intended end date continuing to sell at the promotional rate",
         "Ambitious campaign windows conflicting with realistic ATPCO filing lead times",
         "Mid-campaign underperformance being observed but rarely acted on before the campaign closes"])

P("AC-RM-PF-05",
  desc="Negotiated corporate fares are administered for contracted accounts, covering discount structure, "
       "eligibility validation and compliance monitoring against the negotiated terms.",
  trig="A corporate account contract is signed or renewed, or a compliance review identifies a discrepancy.",
  out="Correctly configured corporate fares available only to eligible bookers, with usage monitored against "
      "contracted volume commitments.",
  note="A negotiated corporate fare is a contract enforced through system configuration, so a configuration "
      "error either leaks a discount to ineligible bookers or denies it to eligible ones.",
  phases=["Contract configuration", "Eligibility control", "Compliance monitoring"],
  steps=[
    S("1.1","Configure corporate fare structure","Pricing Analyst","ATPCO",
      "Signed corporate contract terms","Configured corporate fare",
      "Configured within 5 business days of contract signing at 100 percent","N","N",
      "Contract terms translated into fare rule logic can lose nuance present in the legal agreement"),
    S("1.2","Set eligibility and access control","Pricing Analyst","Amadeus Altea Reservations",
      "Corporate account booking tool access","Restricted fare access to eligible bookers",
      "Access restricted correctly at 100 percent of configuration","Y","N",
      "Access control depends on booking tool configuration matching the contract's eligible traveller list"),
    S("2.1","Monitor booking volume against contract commitment","Revenue Management Analyst","SAP Analytics Cloud",
      "Actual corporate booking volume","Volume tracking against commitment",
      "Tracked monthly for 100 percent of active corporate contracts","N","N",
      "Volume shortfall against commitment is a commercial signal that is not always escalated promptly"),
    S("2.2","Audit for fare leakage or misuse","Revenue Management Analyst","Amadeus Altea Reservations",
      "Booking data against eligibility rules","Leakage or misuse audit findings",
      "Audited quarterly for 100 percent of material corporate accounts","N","Y",
      "Leakage through an indirect booking channel is harder to detect than direct channel misuse"),
    S("3.1","Renew or amend fare configuration at contract change","Pricing Analyst","ATPCO",
      "Contract renewal or amendment","Updated corporate fare configuration",
      "Configuration updated within 5 business days of contract change at 100 percent","N","N",
      "A configuration not updated at renewal can leave a superseded discount active past its term"),
  ],
  kpis=["Configured within 5 business days of contract signing at 100 percent",
        "Access restricted correctly at 100 percent of configuration",
        "Tracked monthly for 100 percent of active corporate contracts",
        "Audited quarterly for 100 percent of material corporate accounts"],
  risks=["Contract terms losing nuance when translated into fare rule logic",
         "A superseded discount remaining active past its contract term because configuration was not updated",
         "Fare leakage through an indirect booking channel being harder to detect than direct misuse",
         "Volume shortfall against a commercial commitment not being escalated promptly"])

P("AC-RM-PF-06",
  desc="Government-mandated taxes, fees and carrier surcharges are maintained across every market Air "
       "Canada serves, kept current with changing regulatory rates.",
  trig="A government or airport authority changes a tax, fee or charge rate, or a scheduled periodic review "
       "runs.",
  out="Correctly filed and applied taxes, fees and surcharges across all affected fares and markets.",
  note="Tax and fee maintenance is unglamorous but has zero tolerance for error: undercharging is a direct "
       "revenue loss recovered from the airline, and overcharging is a customer-facing compliance problem.",
  phases=["Rate change monitoring", "Filing update", "Verification"],
  steps=[
    S("1.1","Monitor for tax and fee rate changes","Pricing Analyst","ATPCO",
      "Government and airport authority notifications","Identified rate change",
      "Changes identified within 5 business days of the effective notice at 100 percent","N","N",
      "Notification channels vary by jurisdiction and are not centrally aggregated"),
    S("2.1","Update tax and fee filing","Pricing Analyst","ATPCO",
      "Identified rate change","Updated filed rate",
      "Updated before the change's effective date at 95 percent","N","N",
      "Some jurisdictions provide very short notice before a rate change takes effect"),
    S("2.2","Verify correct application across fare types","Pricing Analyst","Amadeus Altea Reservations",
      "Updated filing","Verified correct application",
      "Verified for 100 percent of material rate changes","Y","N",
      "A rate can apply differently across fare types and channels in ways that are easy to miss"),
    S("3.1","Reconcile collected amounts to remittance obligation","Revenue Accounting Analyst","Revenue Accounting System",
      "Collected tax and fee amounts","Reconciled remittance position",
      "Reconciled monthly for 100 percent of applicable taxes","N","N",
      "A filing error compounds across every booking made before it is caught"),
  ],
  kpis=["Changes identified within 5 business days of the effective notice at 100 percent",
        "Updated before the change's effective date at 95 percent",
        "Verified for 100 percent of material rate changes",
        "Reconciled monthly for 100 percent of applicable taxes"],
  risks=["A short-notice jurisdiction rate change taking effect before the filing is updated",
         "A filing error compounding across every booking made before it is caught",
         "A rate applying inconsistently across fare types and channels in a way that is easy to miss",
         "Notification channels varying by jurisdiction with no central aggregation point"])

P("AC-RM-PF-07",
  desc="Fare rules and penalty structures, including change and cancellation fees, are designed to balance "
       "revenue protection against customer flexibility expectations and competitive positioning.",
  trig="A fare family redesign is undertaken, or a competitive or regulatory pressure requires the penalty "
       "structure to be reassessed.",
  out="A defined penalty structure by fare family, filed and consistently applied across booking and "
      "servicing touchpoints.",
  note="A penalty structure only has commercial value if it is applied consistently everywhere a change or "
       "cancellation can be processed; an inconsistency between the contact centre and self-service becomes "
       "a customer complaint about fairness.",
  phases=["Structure design", "Filing and system configuration", "Consistency verification"],
  steps=[
    S("1.1","Design penalty structure by fare family","Pricing Analyst","ATPCO",
      "Competitive position and revenue protection objective","Designed penalty structure",
      "Design completed within the fare family review cycle","N","N",
      "Balancing flexibility and revenue protection has no formulaic answer and depends on brand positioning"),
    S("1.2","Assess regulatory constraints on penalties","Pricing Analyst","ATPCO",
      "Draft structure and applicable regulation","Compliance-checked structure",
      "Checked against CTA and destination-market rules at 100 percent","Y","N",
      "Penalty regulation differs by market, so a single global structure will not fit every route"),
    S("2.1","File penalty rules to ATPCO","Pricing Analyst","ATPCO",
      "Approved structure","Filed fare rules with penalty terms",
      "Filed within the required lead time at 100 percent","N","N",
      "Penalty rule logic is some of the most complex fare filing content to construct correctly"),
    S("2.2","Configure servicing systems to apply penalties consistently","Pricing Analyst","Amadeus Altea Reservations",
      "Filed rules","Consistent penalty application across servicing channels",
      "Consistent application verified across all channels at 100 percent","N","N",
      "Self-service and contact centre systems can apply the same filed rule differently in practice"),
    S("3.1","Audit penalty application against filed terms","Revenue Management Analyst","Amadeus Altea Reservations",
      "Sample of change and cancellation transactions","Audit findings",
      "Audited quarterly for 100 percent of fare families","N","N",
      "An inconsistency surfaces to the customer as unfair treatment rather than a system defect"),
  ],
  kpis=["Filed within the required lead time at 100 percent",
        "Consistent application verified across all channels at 100 percent",
        "Checked against CTA and destination-market rules at 100 percent",
        "Audited quarterly for 100 percent of fare families"],
  risks=["Self-service and contact centre systems applying the same filed penalty rule differently",
         "A single global penalty structure not fitting every market's regulatory constraints",
         "An application inconsistency reaching the customer as an apparent fairness failure",
         "Penalty rule logic being complex enough that filing errors are hard to catch before they apply"])

P("AC-RM-PF-08",
  desc="Fare presentation and pricing are adjusted by currency and point of sale, reflecting local market "
       "conditions, currency movements and competitive positioning in each selling market.",
  trig="A currency movement crosses a defined threshold, or the recurring point of sale pricing review runs.",
  out="Correctly localised fares by point of sale, appropriately reflecting currency and local market "
      "conditions without arbitrage opportunity across markets.",
  note="A fare priced identically in every currency at the spot exchange rate ignores local price "
      "positioning; priced too far from spot, it creates an arbitrage opportunity between markets.",
  phases=["Currency and market monitoring", "Localisation adjustment", "Arbitrage control"],
  steps=[
    S("1.1","Monitor currency movement against filing baseline","Pricing Analyst","ATPCO",
      "Current exchange rates","Currency movement report",
      "Monitored daily for 100 percent of active point of sale currencies","N","N",
      "Some currencies move enough intraday that a daily check already lags the market"),
    S("1.2","Assess local competitive positioning","Revenue Management Analyst","PROS Revenue Management",
      "Local market fare comparison","Positioning assessment by point of sale",
      "Assessed for each point of sale each review cycle","N","N",
      "Local competitive data quality varies significantly by market"),
    S("2.1","Adjust localised fare levels","Pricing Analyst","ATPCO",
      "Currency movement and positioning assessment","Adjusted localised fares",
      "Adjustments filed within the review cycle at 100 percent","N","N",
      "Frequent adjustment creates a filing burden that competes with other pricing priorities"),
    S("3.1","Screen for cross-market arbitrage opportunity","Revenue Management Analyst","PROS Revenue Management",
      "Localised fares across all points of sale","Arbitrage risk assessment",
      "Screened each review cycle for 100 percent of markets","Y","N",
      "A large enough spread between markets creates an incentive for point of sale gaming"),
    S("3.2","Correct identified arbitrage exposure","Pricing Analyst","ATPCO",
      "Flagged arbitrage risk","Corrected fare filing closing the gap",
      "Material arbitrage exposure corrected within 5 business days at 100 percent","N","Y",
      "Closing a gap in one market can open a different one against a market not previously compared"),
  ],
  kpis=["Monitored daily for 100 percent of active point of sale currencies",
        "Screened each review cycle for 100 percent of markets",
        "Material arbitrage exposure corrected within 5 business days at 100 percent",
        "Adjustments filed within the review cycle at 100 percent"],
  risks=["A currency moving intraday enough that daily monitoring already lags the real exposure",
         "A large cross-market spread creating an incentive for point of sale gaming",
         "Closing an arbitrage gap in one market opening a different one elsewhere",
         "Local competitive data quality varying enough by market to skew the positioning assessment"])

# ── AN: Ancillary and Merchandising ─────────────────────────────────────────
P("AC-RM-AN-01",
  desc="Seat selection is priced by cabin zone and route, balancing incremental ancillary revenue against "
       "customer perception of a fair pricing structure.",
  trig="The recurring seat pricing review cycle runs, or a cabin reconfiguration changes the available "
      "zone map.",
  out="A seat pricing structure by zone and route filed into Anytime Merchandising and visible at the "
      "point of sale.",
  note="Seat pricing sits close to customer perception of fairness: a price that looks arbitrary by zone "
      "generates contact volume even when it is revenue-optimal.",
  phases=["Zone and demand analysis", "Price structure design", "Filing and monitoring"],
  steps=[
    S("1.1","Analyse seat selection demand by zone","Revenue Management Analyst","Amadeus Anytime Merchandising",
      "Historical seat selection purchase data","Demand by zone and route",
      "Analysed each review cycle for 100 percent of route groups","N","N",
      "Demand patterns differ by route length and cabin configuration in ways a single price grid cannot capture"),
    S("2.1","Design zone pricing structure","Revenue Management Analyst","Amadeus Anytime Merchandising",
      "Zone demand analysis","Designed pricing structure by zone",
      "Structure designed within the review cycle at 100 percent","N","N",
      "A price set too high on a popular zone can suppress purchase enough to reduce total revenue"),
    S("2.2","Validate against Altitude tier entitlements","Revenue Management Analyst","Aeroplan Platform",
      "Designed structure and tier benefit rules","Validated structure honouring tier entitlements",
      "Validated for 100 percent of Altitude tiers before filing","Y","N",
      "A pricing error that charges an entitled elite member breaks a core loyalty promise"),
    S("3.1","File pricing to Anytime Merchandising","Revenue Management Analyst","Amadeus Anytime Merchandising",
      "Validated structure","Filed and live seat pricing",
      "Filed within the required lead time at 100 percent","N","N",
      "A filing error can charge for a seat that should be included in the fare"),
    S("3.2","Monitor purchase rate and complaint volume","Revenue Management Analyst","Salesforce Service Cloud",
      "Post-launch purchase and complaint data","Performance review against target",
      "Reviewed within 30 days of a pricing change at 100 percent","N","N",
      "Complaint volume is a lagging signal that a pricing structure feels unfair"),
  ],
  kpis=["Structure designed within the review cycle at 100 percent",
        "Validated for 100 percent of Altitude tiers before filing",
        "Filed within the required lead time at 100 percent",
        "Complaint volume attributable to seat pricing below target threshold"],
  risks=["A pricing error charging an entitled Altitude member for a seat that should be included",
         "A price set too high on a popular zone suppressing purchase enough to reduce total revenue",
         "A filing error charging for a seat that the fare should have included at no cost",
         "Complaint volume being a lagging rather than a leading indicator of a pricing structure problem"])

P("AC-RM-AN-02",
  desc="Checked baggage fees are managed across fare families, markets and Altitude tiers, reflecting "
       "included-baggage entitlements and market-specific competitive positioning.",
  trig="The recurring baggage fee review cycle runs, or a competitive baggage policy change requires "
       "reassessment.",
  out="Correctly filed baggage fees honouring fare family inclusions and Altitude entitlements, competitive "
      "in each market.",
  note="Baggage fee logic intersects fare family, market, and loyalty tier simultaneously, which makes it "
      "one of the more complex ancillary configurations to get right and to keep right.",
  phases=["Entitlement and market review", "Fee structure design", "Filing and verification"],
  steps=[
    S("1.1","Review fare family baggage inclusions","Revenue Management Analyst","Amadeus Anytime Merchandising",
      "Current fare family definitions","Documented inclusion matrix",
      "Inclusion matrix current for 100 percent of active fare families","N","N",
      "Fare family definitions change independently of the baggage fee review cycle"),
    S("1.2","Assess competitive baggage positioning by market","Revenue Management Analyst","PROS Revenue Management",
      "Competitor baggage fee data","Positioning assessment by market",
      "Assessed each review cycle for priority markets","N","N",
      "Competitor baggage policy data is less consistently available than fare data"),
    S("2.1","Design fee structure by fare family and market","Revenue Management Analyst","Amadeus Anytime Merchandising",
      "Inclusion matrix and competitive position","Designed fee structure",
      "Structure designed within the review cycle at 100 percent","N","N",
      "A structure that is competitive in one market can be out of step in another"),
    S("2.2","Validate Altitude tier entitlements","Revenue Management Analyst","Aeroplan Platform",
      "Designed structure and tier benefits","Validated structure honouring entitlements",
      "Validated for 100 percent of Altitude tiers before filing","Y","N",
      "Entitled bag allowances by tier must be correctly reflected at check-in, not only at booking"),
    S("3.1","File and verify fee application","Revenue Management Analyst","Amadeus Altea DCS",
      "Validated structure","Filed and verified fee application at check-in",
      "Verified consistent between booking and check-in at 100 percent","N","N",
      "A fee charged correctly at booking but incorrectly at check-in is a common source of dispute"),
  ],
  kpis=["Inclusion matrix current for 100 percent of active fare families",
        "Validated for 100 percent of Altitude tiers before filing",
        "Verified consistent between booking and check-in at 100 percent",
        "Baggage fee dispute volume below target threshold"],
  risks=["A fee charged correctly at booking but incorrectly at check-in creating a recurring dispute pattern",
         "Entitled bag allowances by Altitude tier not correctly reflected at the point of check-in",
         "Fare family definitions changing independently of the baggage fee review cycle",
         "A structure competitive in one market being out of step with local expectations in another"])

P("AC-RM-AN-03",
  desc="Branded fare families are designed and merchandised, bundling included features to create clear "
       "differentiation between fare tiers at the point of sale.",
  trig="A fare family redesign is scheduled, or competitive positioning requires a bundle to be revised.",
  out="A defined fare family structure with clear, correctly merchandised differentiation, filed and "
      "consistently presented across channels.",
  note="Fare family differentiation only works commercially if the customer can actually perceive the "
       "difference at the point of sale; a bundle that reads the same as the tier below it does not sell up.",
  phases=["Bundle design", "Merchandising configuration", "Presentation verification"],
  steps=[
    S("1.1","Design fare family feature bundles","Revenue Management Analyst","Amadeus Anytime Merchandising",
      "Competitive positioning and customer research","Designed bundle by fare family",
      "Design completed within the redesign cycle","N","N",
      "Bundle design trades off simplicity for the customer against maximising differentiated revenue"),
    S("1.2","Price the differentiation between tiers","Revenue Management Analyst","PROS Revenue Management",
      "Bundle design and elasticity data","Priced fare family tiers",
      "Pricing completed for 100 percent of tiers in the redesign","N","N",
      "Pricing the gap between tiers too small removes the incentive to buy up"),
    S("2.1","Configure merchandising presentation","Revenue Management Analyst","Amadeus Anytime Merchandising",
      "Priced tiers","Configured presentation at point of sale",
      "Configuration matches design intent at 100 percent","N","N",
      "Presentation configuration in the booking flow is a separate system from the pricing configuration"),
    S("2.2","Validate cross-channel presentation consistency","Revenue Management Analyst","aircanada.com",
      "Configured presentation","Verified consistency across channels",
      "Consistency verified across all channels at 100 percent","N","N",
      "The GDS presentation of a fare family bundle is often less rich than the direct channel"),
    S("3.1","Monitor buy-up rate against target","Revenue Management Analyst","SAP Analytics Cloud",
      "Post-launch booking data by tier","Buy-up rate report",
      "Reviewed within 60 days of launch at 100 percent","N","N",
      "A low buy-up rate can indicate a pricing or presentation problem without clearly distinguishing which"),
  ],
  kpis=["Design completed within the redesign cycle at 100 percent",
        "Consistency verified across all channels at 100 percent",
        "Buy-up rate to the next tier meeting target on launch",
        "Configuration matching design intent at 100 percent"],
  risks=["A bundle that reads the same as the tier below it failing to generate buy-up revenue",
         "The GDS presentation being materially less rich than the direct channel for the same fare family",
         "Pricing the gap between tiers too small to create a genuine incentive to trade up",
         "A low buy-up rate not clearly distinguishing a pricing problem from a presentation problem"])

P("AC-RM-AN-04",
  desc="Upgrade offers and cabin buy-up are managed from booking through to close-in clearance, balancing "
       "ancillary revenue against protected premium cabin inventory.",
  trig="A booking becomes eligible for an upgrade offer, or the close-in clearance window opens ahead of "
       "departure.",
  out="Upgrade offers correctly priced and presented, with close-in premium inventory cleared to maximise "
      "revenue from otherwise unsold seats.",
  note="Upgrade offer pricing has to move as departure approaches: early in the booking window it competes "
       "with full-fare premium sales, and close to departure an empty premium seat earns nothing at all.",
  phases=["Offer eligibility and pricing", "Presentation", "Close-in clearance"],
  steps=[
    S("1.1","Determine upgrade offer eligibility","Revenue Management Analyst","Amadeus Anytime Merchandising",
      "Booking fare class and cabin availability","Eligible offer population",
      "Eligibility calculated for 100 percent of qualifying bookings","N","N",
      "Eligibility rules interact with Altitude tier and fare class in ways that are easy to misconfigure"),
    S("1.2","Price the upgrade offer dynamically","Revenue Management Analyst","PROS Real-Time Dynamic Pricing",
      "Premium cabin demand and time to departure","Dynamically priced offer",
      "Priced dynamically for 100 percent of eligible bookings","N","N",
      "Offer pricing that does not account for premium cabin demand can cannibalise full-fare sales"),
    S("2.1","Present offer across channels","Revenue Management Analyst","Air Canada Mobile App",
      "Priced offer","Offer presented at appropriate touchpoints",
      "Offer presented at check-in and pre-departure for 100 percent of eligible bookings","N","N",
      "Offer timing that arrives too late in the booking journey reduces conversion"),
    S("3.1","Clear close-in premium inventory","Revenue Management Analyst","Amadeus Altea Inventory",
      "Unsold premium inventory near departure","Cleared inventory via upgrade or complimentary offer",
      "Close-in clearance decision made within 24 hours of departure at 100 percent","Y","N",
      "A seat cleared too aggressively forgoes revenue that a later-arriving full fare passenger would have paid"),
    S("3.2","Reconcile upgrade revenue and cabin utilisation","Revenue Management Analyst","SAP Analytics Cloud",
      "Upgrade transactions and cabin load","Reconciled revenue and utilisation report",
      "Reconciled monthly at 100 percent","N","N",
      "Attributing incremental revenue to the upgrade programme versus organic full-fare sales is imprecise"),
  ],
  kpis=["Eligibility calculated for 100 percent of qualifying bookings",
        "Priced dynamically for 100 percent of eligible bookings",
        "Close-in clearance decision made within 24 hours of departure at 100 percent",
        "Premium cabin load factor improvement attributable to upgrade offers meeting target"],
  risks=["Offer pricing that does not reflect premium cabin demand cannibalising full-fare sales",
         "A seat cleared too aggressively close-in forgoing revenue from a later full-fare passenger",
         "Offer presentation arriving too late in the booking journey to convert",
         "Incremental upgrade revenue being imprecisely attributed against organic full-fare sales"])

P("AC-RM-AN-05",
  desc="Third-party ancillary partners, including insurance, car rental and hotel offers presented at "
       "booking, are managed for commercial terms, presentation and performance.",
  trig="A new third-party ancillary partnership is onboarded, or the recurring partner performance review "
       "runs.",
  out="Correctly configured third-party offers presented at the appropriate point in the booking journey, "
      "with commercial terms and performance tracked.",
  note="Third-party ancillary offers are a booking-flow addition that has to compete for customer attention "
      "without degrading the core booking conversion the airline actually depends on.",
  phases=["Partner and offer configuration", "Presentation integration", "Performance management"],
  steps=[
    S("1.1","Configure partner commercial terms","Revenue Management Analyst","Amadeus Anytime Merchandising",
      "Signed partner agreement","Configured commission and settlement terms",
      "Configured within 10 business days of agreement signing at 100 percent","N","N",
      "Settlement terms across multiple third-party partners are not standardised"),
    S("2.1","Integrate offer presentation into the booking flow","Revenue Management Analyst","aircanada.com",
      "Partner offer content","Integrated presentation at the appropriate step",
      "Integration tested before go-live at 100 percent","N","N",
      "Offer placement that adds friction to the core booking flow risks reducing overall conversion"),
    S("2.2","Validate booking conversion impact","Revenue Management Analyst","Adobe Analytics",
      "Pre and post-integration conversion data","Conversion impact assessment",
      "Assessed within 30 days of integration at 100 percent","Y","N",
      "A conversion drop attributable to the new offer is not always immediately obvious from aggregate data"),
    S("3.1","Track partner offer performance","Revenue Management Analyst","SAP Analytics Cloud",
      "Offer uptake and commission data","Performance report against target",
      "Reviewed quarterly for 100 percent of active partners","N","N",
      "Underperforming partner placements are not automatically reconsidered without an active review"),
    S("3.2","Renew, adjust or terminate partner placement","Revenue Management Analyst","Amadeus Anytime Merchandising",
      "Performance report","Renewal, adjustment or termination decision",
      "Decisions taken within the performance review cycle at 100 percent","N","N",
      "Terminating a placement requires coordinating removal across every channel it was integrated into"),
  ],
  kpis=["Configured within 10 business days of agreement signing at 100 percent",
        "Integration tested before go-live at 100 percent",
        "Reviewed quarterly for 100 percent of active partners",
        "Zero material core booking conversion decline attributable to a partner offer"],
  risks=["Offer placement adding enough friction to the booking flow to reduce core conversion",
         "A conversion drop attributable to a new offer not being immediately visible in aggregate data",
         "Underperforming partner placements persisting without an active review forcing a decision",
         "Settlement terms across multiple partners being inconsistent and error-prone to administer"])

P("AC-RM-AN-06",
  desc="Ancillary revenue performance is tracked across all product lines, attributing results to specific "
       "pricing, merchandising and channel decisions to inform the next optimisation cycle.",
  trig="The recurring ancillary performance reporting cycle runs.",
  out="A consolidated ancillary revenue report by product line and channel, with performance attributed to "
      "specific commercial decisions.",
  note="Ancillary revenue spans seat selection, baggage, upgrades and third-party offers managed by "
       "different teams, so consolidated reporting is the only place the full picture actually comes "
       "together.",
  phases=["Data consolidation", "Attribution analysis", "Distribution and action"],
  steps=[
    S("1.1","Consolidate ancillary revenue by product line","Revenue Management Analyst","SAP Analytics Cloud",
      "Transaction data across ancillary products","Consolidated revenue by product line",
      "Consolidated within 5 business days of period close at 100 percent","N","N",
      "Product lines are tracked in different source systems with inconsistent granularity"),
    S("2.1","Attribute performance to pricing and merchandising decisions","Revenue Management Analyst","PROS Revenue Management",
      "Consolidated revenue and decision history","Attributed performance by decision",
      "Attribution completed for 100 percent of material product lines","N","N",
      "Several concurrent changes to the same product line make individual attribution genuinely difficult"),
    S("2.2","Compare performance to target by channel","Revenue Management Analyst","Adobe Analytics",
      "Attributed performance","Channel performance against target",
      "Compared each reporting cycle for 100 percent of channels","N","N",
      "Channel-level target setting does not always account for structurally different conversion rates"),
    S("3.1","Distribute findings and recommend action","Revenue Management Analyst","SAP Analytics Cloud",
      "Full performance analysis","Distributed report with recommendations",
      "Distributed within 10 business days of period close at 100 percent","N","N",
      "Recommendations are produced regularly but implementation tracking against them is inconsistent"),
  ],
  kpis=["Consolidated within 5 business days of period close at 100 percent",
        "Attribution completed for 100 percent of material product lines",
        "Distributed within 10 business days of period close at 100 percent",
        "Total ancillary revenue per passenger tracked against target each period"],
  risks=["Product lines tracked in different source systems with inconsistent granularity",
         "Concurrent changes to the same product line making individual attribution genuinely difficult",
         "Channel-level targets not accounting for structurally different conversion rates",
         "Recommendations produced regularly without consistent tracking of whether they were implemented"])

P("AC-RM-AN-07",
  desc="A new ancillary product is developed and launched, from initial concept and demand validation "
       "through pricing, systems configuration and post-launch performance review.",
  trig="A new ancillary product opportunity is identified through customer research or competitive "
       "benchmarking.",
  out="A launched ancillary product with validated demand, correct pricing and system configuration, and a "
      "structured post-launch review.",
  note="Every ancillary product launch touches merchandising, pricing, distribution and often departure "
       "control systems, which makes cross-functional sequencing the main determinant of a clean launch.",
  phases=["Concept validation", "Build and configuration", "Launch and review"],
  steps=[
    S("1.1","Validate demand for the product concept","Revenue Management Analyst","Adobe Analytics",
      "Customer research and competitive benchmark","Validated demand estimate",
      "Demand validated before build begins at 100 percent","N","N",
      "Stated preference in research does not always predict actual willingness to pay"),
    S("1.2","Build the commercial and pricing case","Revenue Management Analyst","PROS Revenue Management",
      "Validated demand","Approved commercial case",
      "Case approved before system build begins at 100 percent","Y","N",
      "The business case is built on a demand estimate that has not yet been tested against real bookings"),
    S("2.1","Configure system support for the product","Revenue Management Analyst","Amadeus Anytime Merchandising",
      "Approved case","Configured product across booking and servicing systems",
      "Configuration tested end to end before launch at 100 percent","N","N",
      "A genuinely new product type can require configuration in systems not originally designed for it"),
    S("2.2","Train front-line and contact centre staff","Training Coordinator","Salesforce Service Cloud",
      "Configured product","Trained staff ready to service the product",
      "Training completed before launch at 100 percent","N","N",
      "A product launch without adequate staff training generates avoidable contact centre volume"),
    S("3.1","Launch and monitor early performance","Revenue Management Analyst","SAP Analytics Cloud",
      "Live product","Early performance report",
      "Reviewed within 30 days of launch at 100 percent","N","N",
      "Early performance can be distorted by launch-period promotional activity"),
    S("3.2","Conduct structured post-launch review","Revenue Management Analyst","SAP Analytics Cloud",
      "Sustained performance data","Post-launch review with scale or retire recommendation",
      "Review conducted within 90 days of launch at 100 percent","N","N",
      "Without a forced review point, an underperforming product can simply persist rather than being retired"),
  ],
  kpis=["Demand validated before build begins at 100 percent",
        "Configuration tested end to end before launch at 100 percent",
        "Training completed before launch at 100 percent",
        "Post-launch review conducted within 90 days of launch at 100 percent"],
  risks=["Stated research preference not predicting actual willingness to pay once the product is live",
         "A product launch without adequate staff training generating avoidable contact centre volume",
         "Early performance distorted by launch-period promotional activity, masking the sustained result",
         "An underperforming product persisting indefinitely without a forced scale-or-retire decision point"])

# ── YM: RM Analytics and Performance ────────────────────────────────────────
P("AC-RM-YM-01",
  desc="Revenue management analysts run a structured daily review cycle across their assigned markets, "
       "checking forecast quality, override activity and competitive movement before the next optimisation "
       "run.",
  trig="Each business day, following the completion of the nightly optimisation batch.",
  out="A reviewed market position for each analyst's portfolio, with exceptions actioned before the next "
      "nightly cycle.",
  note="The daily cycle is where human judgement is layered onto the automated optimisation, and its "
       "consistency across analysts is what keeps the overall RM function coherent rather than a set of "
       "individually managed portfolios.",
  phases=["Overnight review", "Exception handling", "Preparation for the next cycle"],
  steps=[
    S("1.1","Review overnight optimisation output","Revenue Management Analyst","PROS Revenue Management",
      "Completed nightly optimisation run","Reviewed output for the assigned portfolio",
      "Review completed before market open for 100 percent of assigned routes","N","N",
      "Portfolio size can exceed what a thorough manual review can cover in the available time"),
    S("1.2","Check standing overrides for continued relevance","Revenue Management Analyst","Amadeus Altea Inventory",
      "Active override list","Confirmed or released overrides",
      "Reviewed daily for 100 percent of standing overrides","N","N",
      "An override applied for a since-resolved situation is easy to overlook in a busy queue"),
    S("2.1","Investigate flagged forecast exceptions","Revenue Management Analyst","PROS Revenue Management",
      "System-flagged exception list","Resolved or escalated exception",
      "Exceptions actioned within the trading day at 90 percent","N","Y",
      "Exception volume spikes around irregular operations events and competes with routine review time"),
    S("2.2","Scan competitive fare movement","Revenue Management Analyst","Sabre PRISM",
      "Overnight competitor filing activity","Reviewed competitive position",
      "Scanned daily for 100 percent of the assigned portfolio","N","N",
      "Manual scanning cannot cover the full portfolio with the same depth every single day"),
    S("3.1","Prepare notes for the next optimisation cycle","Revenue Management Analyst","PROS Revenue Management",
      "Day's findings","Documented input for tomorrow's cycle",
      "Notes prepared for 100 percent of material findings at end of day","N","N",
      "Undocumented context is lost between analysts on days with a portfolio handover"),
  ],
  kpis=["Review completed before market open for 100 percent of assigned routes",
        "Exceptions actioned within the trading day at 90 percent",
        "Reviewed daily for 100 percent of standing overrides",
        "Scanned daily for 100 percent of the assigned portfolio"],
  risks=["Portfolio size exceeding what a thorough manual review can genuinely cover each day",
         "An override applied for a since-resolved situation persisting unnoticed in a busy review queue",
         "Exception volume spikes around disruption events crowding out routine daily review",
         "Undocumented context being lost between analysts during a portfolio handover"])

P("AC-RM-YM-02",
  desc="Forecast accuracy is tracked and model drift is monitored across the demand forecasting engine, "
       "identifying when a model's error pattern has moved beyond normal variance.",
  trig="The recurring model accuracy monitoring cycle runs, or a sustained accuracy decline is flagged.",
  out="A forecast accuracy report with any drifting model or market segment identified for model team "
      "action.",
  note="Forecast error is expected within a normal range; the discipline here is distinguishing ordinary "
       "noise from a genuine, sustained drift that means the model itself needs retuning.",
  phases=["Accuracy measurement", "Drift detection", "Escalation to model owners"],
  steps=[
    S("1.1","Measure forecast accuracy against actuals","Revenue Management Analyst","PROS Revenue Management",
      "Forecast history and actual bookings","Accuracy measurement by market segment",
      "Measured for 100 percent of market segments each cycle","N","N",
      "Accuracy at different booking horizons can move in opposite directions simultaneously"),
    S("2.1","Compare accuracy trend against normal variance range","Revenue Management Analyst","Databricks Lakehouse",
      "Accuracy history","Flagged segments outside normal variance",
      "Flagged within one monitoring cycle of drift beginning at 90 percent","Y","N",
      "The normal variance range itself needs periodic recalibration as the network changes"),
    S("2.2","Investigate flagged drift root cause","Revenue Management Analyst","PROS Revenue Management",
      "Flagged segment","Root cause hypothesis",
      "Investigated within 5 business days of flagging","N","Y",
      "Drift root cause can be external market change rather than a genuine model defect"),
    S("3.1","Escalate confirmed drift to model owners","Revenue Management Analyst","PROS Revenue Management",
      "Confirmed drift finding","Escalated case for model retuning",
      "Escalated within 2 business days of confirmation at 100 percent","N","N",
      "Retuning cadence is set by the model owner's own release cycle, not by the urgency of the finding"),
  ],
  kpis=["Measured for 100 percent of market segments each cycle",
        "Flagged within one monitoring cycle of drift beginning at 90 percent",
        "Escalated within 2 business days of confirmation at 100 percent",
        "Confirmed drift cases resolved within one model release cycle"],
  risks=["Accuracy at different booking horizons moving in opposite directions and masking each other in aggregate",
         "The normal variance range itself going stale as the network changes around it",
         "Drift root cause being an external market shift rather than an actual model defect",
         "Model retuning cadence lagging the urgency of a confirmed drift finding"])

P("AC-RM-YM-03",
  desc="Spill, demand turned away by a closed class that could have been sold, and spoilage, seats flown "
       "empty that could have been sold, are measured and analysed to tune future inventory decisions.",
  trig="The recurring spill and spoilage analysis cycle runs.",
  out="A spill and spoilage report by route quantifying revenue opportunity lost in both directions, "
      "feeding back into forecast and optimisation tuning.",
  note="Spill and spoilage are opposite failure modes of the same decision, so analysing them together, "
      "rather than separately, is what actually identifies whether a route's controls are too tight or too "
      "loose.",
  phases=["Measurement", "Root cause analysis", "Feedback to optimisation"],
  steps=[
    S("1.1","Measure spill by route and class","Revenue Management Analyst","PROS Revenue Management",
      "Closed-class denial data","Spill estimate by route and class",
      "Measured for 100 percent of routes each cycle","N","N",
      "True spill is inherently an estimate, since a denied customer's true willingness to pay is unobserved"),
    S("1.2","Measure spoilage by route and class","Revenue Management Analyst","PROS Revenue Management",
      "Unsold seat data at departure","Spoilage measurement by route and class",
      "Measured for 100 percent of routes each cycle","N","N",
      "Spoilage in a low cabin, such as premium economy, can be masked by strong overall load factor"),
    S("2.1","Identify routes with structural imbalance","Revenue Management Analyst","Databricks Lakehouse",
      "Spill and spoilage measurements","Flagged routes with persistent imbalance",
      "Flagged each review cycle for 100 percent of material routes","N","N",
      "A route can show acceptable spill and spoilage in aggregate while a specific date pattern is badly imbalanced"),
    S("3.1","Feed findings back into forecast and control tuning","Revenue Management Analyst","PROS Revenue Management",
      "Flagged imbalance findings","Adjusted forecast or control parameters",
      "Findings incorporated into the next optimisation cycle at 100 percent","N","N",
      "The feedback loop from this analysis to actual parameter change is manual and can be slow"),
  ],
  kpis=["Measured for 100 percent of routes each cycle",
        "Flagged each review cycle for 100 percent of material routes",
        "Findings incorporated into the next optimisation cycle at 100 percent",
        "Combined spill and spoilage revenue opportunity reduced year over year"],
  risks=["True spill being inherently an estimate of unobserved customer willingness to pay",
         "Aggregate load factor masking spoilage concentrated in a specific cabin such as premium economy",
         "A route showing acceptable aggregate figures while a specific date pattern is badly imbalanced",
         "The manual feedback loop from finding to parameter change being slow relative to the revenue at stake"])

P("AC-RM-YM-04",
  desc="Revenue integrity monitoring detects fare abuse patterns, including hidden-city ticketing, "
       "point-of-sale manipulation and unauthorised fare combination, to protect filed fare revenue.",
  trig="The recurring revenue integrity screening cycle runs, or a specific abuse pattern is reported.",
  out="Detected fare abuse cases investigated and actioned according to policy, with systemic patterns fed "
      "back into fare rule design.",
  note="Revenue integrity is adversarial by nature: abuse patterns adapt as soon as a specific loophole is "
      "closed, so screening has to be an ongoing discipline rather than a one-time fix.",
  phases=["Pattern detection", "Case investigation", "Action and prevention"],
  steps=[
    S("1.1","Screen for hidden-city and point-of-sale abuse patterns","Revenue Management Analyst","Amadeus Altea Reservations",
      "Booking pattern data","Flagged suspicious booking pattern list",
      "Screened weekly for 100 percent of the network","N","N",
      "Screening rules generate false positives that consume investigation capacity"),
    S("2.1","Investigate flagged cases","Revenue Management Analyst","Amadeus Altea Reservations",
      "Flagged pattern","Confirmed or dismissed abuse case",
      "Investigated within 10 business days of flagging at 90 percent","N","Y",
      "Distinguishing genuine abuse from an unusual but legitimate travel pattern requires judgement"),
    S("2.2","Apply policy action to confirmed cases","Revenue Management Analyst","Amadeus Altea Reservations",
      "Confirmed abuse case","Applied action per policy",
      "Action applied within 5 business days of confirmation at 100 percent","Y","N",
      "Policy action has to be applied consistently or it becomes commercially and reputationally exposed"),
    S("3.1","Identify systemic patterns for fare rule prevention","Revenue Management Analyst","ATPCO",
      "Case history across the review period","Fare rule prevention recommendation",
      "Systemic patterns reviewed each quarter at 100 percent","N","N",
      "Closing one loophole through fare rule design can shift abuse to a different pattern"),
  ],
  kpis=["Screened weekly for 100 percent of the network",
        "Investigated within 10 business days of flagging at 90 percent",
        "Action applied within 5 business days of confirmation at 100 percent",
        "Revenue recovered or protected through revenue integrity action tracked each quarter"],
  risks=["Screening rules generating enough false positives to consume genuine investigation capacity",
         "Confirmed abuse action applied inconsistently, creating commercial and reputational exposure",
         "Closing one abuse loophole through fare rule design simply shifting the pattern elsewhere",
         "Distinguishing genuine abuse from an unusual but entirely legitimate travel pattern"])

P("AC-RM-YM-05",
  desc="Exceptions and alerts raised by the revenue management systems are triaged, resolved or escalated "
       "within defined service levels to prevent a backlog from degrading inventory quality.",
  trig="The revenue management system generates an exception or alert requiring human review.",
  out="Exceptions resolved or escalated within service level, with a clear queue position and no unbounded "
      "backlog.",
  note="An unresolved system exception is not neutral: it means the automated optimisation is working from "
      "an assumption a human has not yet validated, so backlog directly degrades inventory quality.",
  phases=["Exception intake and triage", "Resolution", "Backlog management"],
  steps=[
    S("1.1","Triage incoming exceptions by severity","Revenue Management Analyst","PROS Revenue Management",
      "System-generated exception queue","Triaged queue by severity and route materiality",
      "Triage completed within 2 hours of generation at 100 percent","N","N",
      "Severity scoring does not always correlate with actual revenue materiality"),
    S("2.1","Resolve high-severity exceptions","Revenue Management Analyst","PROS Revenue Management",
      "Triaged high-severity exception","Resolved exception",
      "Resolved within the defined service level at 90 percent","N","Y",
      "High-severity exceptions cluster around irregular operations events, straining capacity exactly when it is scarcest"),
    S("2.2","Resolve or defer lower-severity exceptions","Revenue Management Analyst","PROS Revenue Management",
      "Triaged lower-severity exception","Resolved exception or documented deferral",
      "Zero exceptions deferred past the defined maximum age","N","N",
      "A lower-severity exception left unresolved indefinitely quietly accumulates into a real backlog"),
    S("3.1","Monitor backlog size and age","Revenue Management Analyst","PROS Revenue Management",
      "Current exception queue","Backlog status report",
      "Reported daily at 100 percent","N","N",
      "Backlog trend is not proactively reviewed against staffing capacity"),
  ],
  kpis=["Triage completed within 2 hours of generation at 100 percent",
        "Resolved within the defined service level at 90 percent",
        "Zero exceptions deferred past the defined maximum age",
        "Backlog size trending flat or down over the reporting period"],
  risks=["An unresolved exception meaning automated optimisation runs on an unvalidated assumption",
         "High-severity exceptions clustering around irregular operations exactly when review capacity is scarcest",
         "Severity scoring not correlating reliably with actual revenue materiality",
         "Backlog trend not being reviewed proactively against available staffing capacity"])

P("AC-RM-YM-06",
  desc="Revenue management and pricing data feeds are validated and delivered into the Databricks "
       "lakehouse, providing the grounding data for analytics and machine learning use cases across the "
       "function.",
  trig="The recurring data pipeline cycle runs, or a schema or source system change requires pipeline "
       "validation.",
  out="Validated, current revenue management data available in the lakehouse for downstream analytics and "
      "AI model use.",
  note="Every model and dashboard downstream of revenue management is only as trustworthy as this pipeline, "
      "which makes data quality validation here a control point rather than a routine data engineering task.",
  phases=["Pipeline execution", "Quality validation", "Availability confirmation"],
  steps=[
    S("1.1","Execute scheduled data pipeline runs","Data Engineer","Databricks Lakehouse",
      "Source system data from PROS and Altea Inventory","Ingested raw data in the lakehouse",
      "Pipelines complete within the scheduled window at 99 percent","N","N",
      "A source system schema change can silently break a downstream pipeline transformation"),
    S("2.1","Validate data quality against defined rules","Data Engineer","Databricks Lakehouse",
      "Ingested data","Quality validation report",
      "Validated for 100 percent of scheduled runs","N","N",
      "Quality rules cover known failure modes but cannot anticipate every new data issue"),
    S("2.2","Investigate and remediate quality failures","Data Engineer","Unity Catalog",
      "Quality validation failure","Remediated data or documented known issue",
      "Remediated within 1 business day of detection at 90 percent","N","Y",
      "Remediation sometimes requires a source system fix outside the data team's direct control"),
    S("3.1","Confirm data availability to downstream consumers","Data Engineer","Databricks Lakehouse",
      "Validated data","Confirmed availability for analytics and model use",
      "Confirmed within the scheduled window at 100 percent","N","N",
      "Downstream consumers are not always notified when an upstream quality issue delays availability"),
  ],
  kpis=["Pipelines complete within the scheduled window at 99 percent",
        "Validated for 100 percent of scheduled runs",
        "Remediated within 1 business day of detection at 90 percent",
        "Confirmed within the scheduled window at 100 percent"],
  risks=["A source system schema change silently breaking a downstream pipeline transformation",
         "Quality rules covering known failure modes but missing an entirely new class of data issue",
         "Remediation depending on a source system fix outside the data team's direct control",
         "Downstream model and dashboard consumers not being notified when data availability is delayed"])

P("AC-RM-YM-07",
  desc="Incremental revenue attributable to revenue management decisions is measured and reported, "
       "distinguishing the RM function's contribution from underlying market demand movement.",
  trig="The recurring revenue uplift attribution reporting cycle runs.",
  out="A quantified revenue uplift estimate attributable to revenue management decisions, distinguished from "
      "market-driven demand change.",
  note="Attribution here is genuinely hard: revenue can rise or fall for reasons entirely outside revenue "
      "management's control, and the value of this process is in honestly separating the two rather than "
      "in producing a flattering number.",
  phases=["Baseline and actual comparison", "Attribution modelling", "Reporting"],
  steps=[
    S("1.1","Establish a counterfactual baseline","Revenue Management Analyst","PROS Revenue Management",
      "Historical performance absent RM intervention","Constructed counterfactual baseline",
      "Baseline constructed each reporting cycle at 100 percent","N","N",
      "A counterfactual is inherently a modelling assumption, not an observed fact"),
    S("2.1","Compare actual to counterfactual performance","Revenue Management Analyst","SAP Analytics Cloud",
      "Actual and counterfactual revenue","Gross uplift estimate",
      "Compared for 100 percent of the network each cycle","N","N",
      "Gross uplift before attribution overstates the RM function's true contribution"),
    S("2.2","Separate market-driven from decision-driven uplift","Revenue Management Analyst","Databricks Lakehouse",
      "Gross uplift and market demand data","Attributed uplift by driver",
      "Attribution completed for 100 percent of material uplift each cycle","N","N",
      "Market demand movement and RM decisions are correlated in ways that resist clean separation"),
    S("3.1","Report attributed uplift to leadership","Revenue Management Analyst","SAP Analytics Cloud",
      "Attributed uplift","Distributed leadership report",
      "Reported within the standard reporting cycle at 100 percent","N","N",
      "A report that overstates RM's contribution undermines the credibility of future investment cases"),
  ],
  kpis=["Baseline constructed each reporting cycle at 100 percent",
        "Attribution completed for 100 percent of material uplift each cycle",
        "Reported within the standard reporting cycle at 100 percent",
        "Attribution methodology reviewed and validated at least annually"],
  risks=["A counterfactual baseline being a modelling assumption rather than an observed fact",
         "Gross uplift overstating the RM function's true contribution before proper attribution",
         "Market demand movement and RM decisions being correlated in ways that resist clean separation",
         "An inflated attribution report undermining the credibility of future RM investment cases"])
