# -*- coding: utf-8 -*-
"""
Main orchestration loop: taxonomy -> Ollama (qwen2.5-coder:14b) -> validated
content -> rendered site -> pushed to GitHub Pages.

Runs entirely from the terminal. Resumable: a process only counts as done if
it was generated by the current model and meets the depth floor, so restarting
after an interruption picks up exactly where it left off, and never skips a
process that still only has old thin content.

Usage:
  python3 scripts/run_ollama_pipeline.py                     # run everything remaining
  python3 scripts/run_ollama_pipeline.py --max 20             # stop after 20 successes
  python3 scripts/run_ollama_pipeline.py --only AC-NP-SP-01,AC-CX-CR-02
  python3 scripts/run_ollama_pipeline.py --push-every 5        # push every 5 instead of every 1
  python3 scripts/run_ollama_pipeline.py --dry-run             # print the plan, generate nothing
"""
import argparse, json, os, subprocess, sys, time, datetime, signal, urllib.request, urllib.error

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)

from taxonomy import all_processes
import llm_content

DATA = os.path.join(ROOT, "data", "processes.json")
FAILLOG = os.path.join(ROOT, "data", ".generation_failures.json")

GIT_NAME = os.environ.get("AC_GIT_NAME", "ghatk047")
GIT_EMAIL = os.environ.get("AC_GIT_EMAIL", "samikghatak@gmail.com")

_stop_requested = False


def _handle_signal(signum, frame):
    global _stop_requested
    _stop_requested = True
    log(f"\n[signal] received {signal.Signals(signum).name} -- finishing current process, then stopping cleanly")


def log(msg):
    ts = datetime.datetime.now().strftime("%H:%M:%S")
    print(f"[{ts}] {msg}", flush=True)


def load_content():
    if os.path.exists(DATA):
        with open(DATA, encoding="utf-8") as f:
            return json.load(f)
    return {}


def save_content(content):
    tmp = DATA + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        json.dump(content, f, ensure_ascii=False, indent=1)
    os.replace(tmp, DATA)


def load_failures():
    if os.path.exists(FAILLOG):
        with open(FAILLOG, encoding="utf-8") as f:
            return json.load(f)
    return {}


def save_failures(fails):
    with open(FAILLOG, "w", encoding="utf-8") as f:
        json.dump(fails, f, ensure_ascii=False, indent=1)


def check_ollama():
    try:
        req = urllib.request.Request(llm_content.OLLAMA_HOST + "/api/tags")
        with urllib.request.urlopen(req, timeout=25) as resp:
            tags = json.loads(resp.read())
        names = [m["name"] for m in tags.get("models", [])]
        if llm_content.MODEL not in names and not any(n.startswith(llm_content.MODEL.split(":")[0]) for n in names):
            log(f"WARNING: {llm_content.MODEL} not found in `ollama list`. Available: {names}")
        return True
    except Exception as e:
        log(f"ERROR: cannot reach Ollama at {llm_content.OLLAMA_HOST}: {e}")
        log("Start it yourself first: ollama serve   (see run_overnight.sh)")
        return False


def run(cmd, **kw):
    log(f"  $ {' '.join(cmd)}")
    r = subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True, **kw)
    if r.returncode != 0:
        log(f"  ! exit {r.returncode}: {(r.stderr or r.stdout).strip()[-800:]}")
    return r.returncode == 0


def push_batch(pids_since_push, done_count, total, run_excel=False):
    if not pids_since_push:
        return
    log(f"-- checkpoint: rendering {len(pids_since_push)} diagram(s), rebuilding site, pushing --")
    run([sys.executable, "scripts/render_diagrams.py", "--only", ",".join(p.lower() for p in pids_since_push)])
    if run_excel:
        run([sys.executable, "scripts/write_excel.py"])
    run([sys.executable, "scripts/build_site.py"])

    run(["git", "add", "-A"])
    msg = (f"Ollama {llm_content.MODEL}: {len(pids_since_push)} processes "
           f"({done_count}/{total} total) -- {pids_since_push[0]}"
           + (f" .. {pids_since_push[-1]}" if len(pids_since_push) > 1 else ""))
    committed = run(["git", "-c", f"user.name={GIT_NAME}", "-c", f"user.email={GIT_EMAIL}",
                      "commit", "-q", "-m", msg])
    if committed:
        pushed = run(["git", "push", "-q", "origin", "main"])
        log(f"-- pushed: {'yes' if pushed else 'NO - will retry next checkpoint'} --")
    else:
        log("-- nothing to commit (render/build produced no changes) --")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--max", type=int, default=None, help="stop after this many successful generations")
    ap.add_argument("--start", help="skip taxonomy order and start from this PID")
    ap.add_argument("--only", help="comma-separated PIDs to (re)generate, ignoring done-check")
    ap.add_argument("--push-every", type=int, default=1, help="checkpoint/push after this many successes")
    ap.add_argument("--excel-every", type=int, default=10, help="rebuild the Excel catalog every N checkpoints")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    signal.signal(signal.SIGINT, _handle_signal)
    signal.signal(signal.SIGTERM, _handle_signal)

    if not args.dry_run and not check_ollama():
        sys.exit(1)

    procs = all_processes()
    if args.only:
        want = set(args.only.split(","))
        procs = [p for p in procs if p["pid"] in want]
    elif args.start:
        idx = next((i for i, p in enumerate(procs) if p["pid"] == args.start), None)
        if idx is None:
            log(f"ERROR: {args.start} not found in taxonomy"); sys.exit(1)
        procs = procs[idx:]

    content = load_content()
    failures = load_failures()
    total = len(all_processes())

    todo = [p for p in procs if not llm_content.is_done(content.get(p["pid"]))]
    done_at_start = total - len(todo) if not (args.only or args.start) else sum(
        1 for p in all_processes() if llm_content.is_done(content.get(p["pid"])))

    log(f"Model: {llm_content.MODEL}  Host: {llm_content.OLLAMA_HOST}")
    log(f"Taxonomy: {total} processes.  Already done (this model, full depth): {done_at_start}.")
    log(f"To generate this run: {len(todo)}" + (f" (capped at --max {args.max})" if args.max else ""))

    if args.dry_run:
        for p in todo[: args.max or len(todo)]:
            log(f"  would generate: {p['pid']}  {p['l3_name']}")
        return

    pids_since_push = []
    checkpoints_done = 0
    n_ok = n_fail = 0
    t_start = time.time()

    for i, p in enumerate(todo):
        if args.max and n_ok >= args.max:
            log(f"Reached --max {args.max}, stopping.")
            break
        if _stop_requested:
            log("Stop requested, exiting cleanly before starting the next process.")
            break

        pid = p["pid"]
        log(f"[{done_at_start + n_ok + 1}/{total}] {pid}  {p['l3_name']}  ({i+1}/{len(todo)} this run)")
        result = llm_content.generate_process(p, log=log)

        if result is None:
            n_fail += 1
            failures[pid] = {"time": datetime.datetime.now().isoformat(), "attempts": llm_content.MAX_ATTEMPTS}
            save_failures(failures)
            continue

        content[pid] = result
        save_content(content)
        failures.pop(pid, None)
        save_failures(failures)
        n_ok += 1
        pids_since_push.append(pid)

        gates = sum(1 for s in result["l4_steps"]
                    if s["decision_point"] == "Y" or s["exception"] == "Y")
        log(f"  ok: {len(result['phases'])} phases, {len(result['l4_steps'])} steps, "
            f"{gates} gates, {result['gen_seconds']}s, attempt {result['gen_attempts']}")

        if len(pids_since_push) >= args.push_every:
            checkpoints_done += 1
            push_batch(pids_since_push, done_at_start + n_ok, total,
                       run_excel=(checkpoints_done % args.excel_every == 0))
            pids_since_push = []

    push_batch(pids_since_push, done_at_start + n_ok, total, run_excel=True)

    elapsed = time.time() - t_start
    log(f"=== run complete: {n_ok} generated, {n_fail} failed, "
        f"{done_at_start + n_ok}/{total} total done, {elapsed/60:.1f} min this run ===")
    if failures:
        log(f"Failed PIDs (see {FAILLOG}): {', '.join(sorted(failures.keys()))}")
        log("Re-run the same command to retry them along with anything else remaining.")


if __name__ == "__main__":
    main()
